/** Shared catalog of all static lab courses and virtual labs.
 *  Used by LabCourses, InteractiveVirtualLabs, and LabAssignmentManager.
 */

export const LAB_COURSES = [
  {
    id: "social-engineering",
    route: "/labs/social-engineering",
    title: "Social Engineering & Phishing Analysis",
    description: "Analyze phishing campaigns, craft awareness emails, and examine real-world social engineering tactics using SET and open-source intelligence tools.",
    difficulty: "Beginner",
    duration: 45,
    category: "Protect and Defend",
    tags: ["SET", "Phishing", "Email Analysis", "Threat Intel"],
  },
  {
    id: "digital-forensics",
    route: "/labs/digital-forensics",
    title: "Digital Forensics & Incident Response",
    description: "Acquire disk images, recover deleted files, and perform timeline analysis using industry-standard DFIR tools like dd, Autopsy, and exiftool.",
    difficulty: "Intermediate",
    duration: 60,
    category: "Investigate",
    tags: ["dd", "Autopsy", "exiftool", "Forensics"],
  },
  {
    id: "cybersecurity-essentials",
    route: "/labs/cybersecurity-essentials",
    title: "Cybersecurity Essentials",
    description: "Master foundational security tasks: port scanning, firewall configuration, rootkit detection, and basic incident response on Linux systems.",
    difficulty: "Beginner",
    duration: 45,
    category: "Operate and Maintain",
    tags: ["Nmap", "UFW", "rkhunter", "Incident Response"],
  },
  {
    id: "cryptography",
    route: "/labs/cryptography",
    title: "Introduction to Cryptography",
    description: "Generate RSA keys, encrypt files with AES-256, verify integrity with hashing, and inspect TLS certificates using OpenSSL and GPG.",
    difficulty: "Intermediate",
    duration: 50,
    category: "Securely Provision",
    tags: ["OpenSSL", "GPG", "Encryption", "Hashing"],
  },
  {
    id: "password-attacks",
    route: "/labs/password-attacks",
    title: "Password Attacks & Credential Exploitation",
    description: "Crack NTLM hashes with hashcat, perform brute-force attacks using Hydra, and exploit credential reuse with Impacket tools.",
    difficulty: "Advanced",
    duration: 75,
    category: "Collect and Operate",
    tags: ["hashcat", "Hydra", "Impacket", "NTLM"],
  },
  {
    id: "web-app-pentest",
    route: "/labs/web-app-pentest",
    title: "Web Application Penetration Testing",
    description: "Exploit SQL injection, identify XSS vulnerabilities, fuzz web directories, and perform full-scope web assessments using sqlmap, gobuster, and Nikto.",
    difficulty: "Advanced",
    duration: 80,
    category: "Analyze",
    tags: ["sqlmap", "XSS", "gobuster", "Nikto"],
  },
  {
    id: "network-traffic-analysis",
    route: "/labs/network-traffic-analysis",
    title: "Network Traffic Analysis",
    description: "Capture live packets, filter and decode protocols, identify DNS exfiltration, and reconstruct TCP streams using tcpdump and tshark.",
    difficulty: "Intermediate",
    duration: 55,
    category: "Analyze",
    tags: ["tcpdump", "tshark", "Wireshark", "DNS"],
  },
  {
    id: "network-security-monitoring",
    route: "/labs/network-security-monitoring",
    title: "Network Security Monitoring",
    description: "Deploy Suricata IDS rules, analyze Zeek logs, and configure Snort to detect and alert on real network threats in a live environment.",
    difficulty: "Intermediate",
    duration: 65,
    category: "Protect and Defend",
    tags: ["Suricata", "Zeek", "Snort", "NSM"],
  },
  {
    id: "vulnerability-assessment",
    route: "/labs/vulnerability-assessment",
    title: "Vulnerability Assessment",
    description: "Run authenticated OpenVAS scans, interpret CVSS scores, and identify critical exposures including Log4Shell across enterprise systems.",
    difficulty: "Intermediate",
    duration: 60,
    category: "Analyze",
    tags: ["OpenVAS", "Nessus", "CVE", "Log4Shell"],
  },
  {
    id: "siem",
    route: "/labs/siem",
    title: "SIEM Operations & Threat Hunting",
    description: "Write Splunk SPL queries, build detection dashboards, hunt for lateral movement with EQL, and correlate multi-source security events.",
    difficulty: "Advanced",
    duration: 70,
    category: "Analyze",
    tags: ["Splunk", "Elastic", "EQL", "Threat Hunting"],
  },
  {
    id: "firewall-evasion",
    route: "/labs/firewall-evasion",
    title: "Firewall Evasion Techniques",
    description: "Bypass packet filters using fragmentation, tunnel traffic over DNS, exploit IPv6 blind spots, and establish covert C2 channels.",
    difficulty: "Expert",
    duration: 90,
    category: "Collect and Operate",
    tags: ["Nmap", "DNS Tunnel", "IPv6", "C2"],
  },
  {
    id: "endpoint-detection",
    route: "/labs/endpoint-detection",
    title: "Endpoint Detection & Response",
    description: "Deploy Wazuh EDR agents, simulate persistence-based threats, trigger FIM alerts, isolate compromised endpoints, and generate incident reports.",
    difficulty: "Intermediate",
    duration: 60,
    category: "Protect and Defend",
    tags: ["Wazuh", "EDR", "FIM", "Containment", "MITRE ATT&CK"],
  },
  {
    id: "cloud-incident-response",
    route: "/labs/cloud-incident-response",
    title: "Cloud Incident Response",
    description: "Investigate suspicious AWS API calls via CloudTrail, revoke compromised IAM credentials, perform blast radius analysis, and apply preventive controls.",
    difficulty: "Advanced",
    duration: 70,
    category: "Investigate",
    tags: ["AWS", "CloudTrail", "IAM", "GuardDuty", "DFIR"],
  },
  {
    id: "linux-hardening",
    route: "/labs/linux-hardening",
    title: "Linux Server Hardening",
    description: "Harden SSH, apply kernel security parameters with sysctl, remove unnecessary services, enable auditd file integrity monitoring, and score posture with Lynis.",
    difficulty: "Intermediate",
    duration: 55,
    category: "Operate and Maintain",
    tags: ["Lynis", "auditd", "sysctl", "SSH", "CIS Benchmark"],
  },
  {
    id: "devsecops",
    route: "/labs/devsecops",
    title: "DevSecOps Pipeline Security",
    description: "Integrate SAST with Semgrep, SCA with OWASP Dependency-Check, container scanning with Trivy, and DAST with OWASP ZAP into a CI/CD security pipeline.",
    difficulty: "Advanced",
    duration: 75,
    category: "Securely Provision",
    tags: ["Semgrep", "Trivy", "OWASP ZAP", "SAST", "DAST", "CI/CD"],
  },
  {
    id: "wireless-exploitation",
    route: "/labs/wireless-exploitation",
    title: "Wireless Network Exploitation",
    description: "Enable monitor mode, capture WPA2 handshakes, execute deauthentication attacks with Aireplay-ng, and crack PSKs via offline dictionary attacks.",
    difficulty: "Advanced",
    duration: 80,
    category: "Collect and Operate",
    tags: ["Aircrack-ng", "WPA2", "Deauth", "Handshake", "802.11"],
  },
  {
    id: "log-correlation",
    route: "/labs/log-correlation",
    title: "Log Aggregation & Correlation",
    description: "Deploy Filebeat for centralized log collection, parse auth logs for brute-force patterns, write SIEM correlation rules, and automate IP blocking with fail2ban.",
    difficulty: "Intermediate",
    duration: 65,
    category: "Analyze",
    tags: ["Filebeat", "Elastic", "fail2ban", "SIEM", "Correlation Rules"],
  },
  {
    id: "bgp",
    route: "/labs/bgp",
    title: "BGP Border Gateway Protocol",
    description: "Establish eBGP peering between two autonomous systems, apply outbound prefix-list route policies, and enable MD5 session authentication to prevent hijacking.",
    difficulty: "Advanced",
    duration: 70,
    category: "Routing",
    tags: ["BGP", "Cisco IOS", "AS", "Prefix List", "Route Policy", "MD5"],
  },
  {
    id: "zero-trust",
    route: "/labs/zero-trust",
    title: "Zero Trust Architecture",
    description: "Deploy Istio service mesh, enforce strict mTLS between services, implement micro-segmentation with AuthorizationPolicy, and verify denied lateral movement.",
    difficulty: "Expert",
    duration: 90,
    category: "Security",
    tags: ["Istio", "mTLS", "Kubernetes", "Micro-segmentation", "Zero Trust", "RBAC"],
  },
];

export const VIRTUAL_LABS = [
  {
    id: "ospf-lab",
    route: "/OspfLab",
    title: "Cisco OSPF Virtual Lab",
    description: "Configure an 8-router OSPF Area 0 topology using Cisco IOS commands. Select a router, configure interfaces, enable OSPF, and ping 8.8.8.8.",
    difficulty: "Intermediate",
    duration: 60,
    category: "Routing",
    tags: ["OSPF", "Cisco IOS", "Routing", "Area 0", "CLI"],
  },
  {
    id: "eigrp-lab",
    route: "/EigrpLab",
    title: "Cisco EIGRP Virtual Lab",
    description: "Configure a 6-router EIGRP AS 100 topology using Cisco IOS commands. Set up interfaces, enable EIGRP, run no auto-summary, and verify adjacencies.",
    difficulty: "Intermediate",
    duration: 55,
    category: "Routing",
    tags: ["EIGRP", "Cisco IOS", "Routing", "AS 100", "CLI"],
  },
  {
    id: "firewall-lab",
    route: "/FirewallLab",
    title: "Multi-Vendor Firewall Hardening Lab",
    description: "Harden a firewall using real CLI syntax across 4 vendors: Cisco ASA, Juniper SRX, Fortinet FortiGate, and Palo Alto PAN-OS. Apply 6 hardening objectives.",
    difficulty: "Advanced",
    duration: 75,
    category: "Security",
    tags: ["Firewall", "Cisco ASA", "Juniper", "Fortinet", "Palo Alto", "Hardening"],
  },
];

export { LINUX_LABS } from "./linuxLabData";
export { POWERSHELL_LABS } from "./powershellLabData";