/** Linux PC & Server Interactive Virtual Labs — 5 Basic + 5 Intermediate */

export const LINUX_LABS = [
  // ── BASIC ──────────────────────────────────────────────────────────────────
  {
    id: "linux-filesystem",
    route: "/linux-labs/filesystem",
    title: "Linux File System Navigation",
    description: "Learn to navigate the Linux directory tree, list files, view contents, and understand absolute vs relative paths.",
    difficulty: "Beginner",
    duration: 20,
    category: "Linux Basics",
    tags: ["ls", "cd", "pwd", "cat", "Linux"],
  },
  {
    id: "linux-permissions",
    route: "/linux-labs/permissions",
    title: "Linux File Permissions",
    description: "Understand and modify file permissions using chmod and chown. Learn the rwx permission model and octal notation.",
    difficulty: "Beginner",
    duration: 25,
    category: "Linux Basics",
    tags: ["chmod", "chown", "permissions", "Linux"],
  },
  {
    id: "linux-packages",
    route: "/linux-labs/packages",
    title: "Package Management with APT",
    description: "Install, update, and remove software packages using the APT package manager on Debian/Ubuntu systems.",
    difficulty: "Beginner",
    duration: 20,
    category: "Linux Basics",
    tags: ["apt", "dpkg", "packages", "Linux"],
  },
  {
    id: "linux-users",
    route: "/linux-labs/users",
    title: "User & Group Management",
    description: "Create and manage Linux user accounts and groups. Set passwords, modify user properties, and switch users.",
    difficulty: "Beginner",
    duration: 25,
    category: "Linux Basics",
    tags: ["useradd", "usermod", "groups", "Linux"],
  },
  {
    id: "linux-text",
    route: "/linux-labs/text",
    title: "Text Processing Fundamentals",
    description: "Use grep, awk, sed, and pipes to search, filter, and manipulate text files from the command line.",
    difficulty: "Beginner",
    duration: 25,
    category: "Linux Basics",
    tags: ["grep", "sed", "awk", "pipes", "Linux"],
  },
  // ── INTERMEDIATE ───────────────────────────────────────────────────────────
  {
    id: "linux-networking",
    route: "/linux-labs/networking",
    title: "Linux Networking Essentials",
    description: "Configure network interfaces, inspect connections, test DNS, and monitor open ports using ip, ss, and dig.",
    difficulty: "Intermediate",
    duration: 35,
    category: "Linux Server",
    tags: ["ip", "ss", "dig", "netstat", "Linux"],
  },
  {
    id: "linux-services",
    route: "/linux-labs/services",
    title: "Service Management with systemctl",
    description: "Start, stop, enable, and inspect systemd services. Read journal logs and understand service unit files.",
    difficulty: "Intermediate",
    duration: 30,
    category: "Linux Server",
    tags: ["systemctl", "journalctl", "systemd", "Linux"],
  },
  {
    id: "linux-scripting",
    route: "/linux-labs/scripting",
    title: "Bash Scripting Basics",
    description: "Write shell scripts using variables, conditionals, loops, and functions. Make scripts executable and schedule them.",
    difficulty: "Intermediate",
    duration: 40,
    category: "Linux Server",
    tags: ["bash", "scripting", "cron", "Linux"],
  },
  {
    id: "linux-sysadmin",
    route: "/linux-labs/sysadmin",
    title: "System Administration",
    description: "Monitor processes, check disk usage, manage system resources, and inspect system logs like a Linux sysadmin.",
    difficulty: "Intermediate",
    duration: 35,
    category: "Linux Server",
    tags: ["top", "df", "du", "ps", "logs", "Linux"],
  },
  {
    id: "linux-ssh",
    route: "/linux-labs/ssh",
    title: "SSH & Remote Access",
    description: "Generate SSH key pairs, configure authorized keys, and securely connect to remote Linux servers.",
    difficulty: "Intermediate",
    duration: 30,
    category: "Linux Server",
    tags: ["ssh", "ssh-keygen", "scp", "Linux"],
  },
];