/** PowerShell Windows Labs — 5 Beginner + 5 Intermediate */

export const POWERSHELL_LABS = [
  // ── BEGINNER ───────────────────────────────────────────────────────────────
  {
    id: "ps-basics",
    route: "/windows-labs/ps-basics",
    title: "PowerShell Basics & Navigation",
    description: "Learn to navigate the Windows filesystem, list directories, and use core PowerShell cmdlets like Get-ChildItem, Set-Location, and Get-Content.",
    difficulty: "Beginner",
    duration: 20,
    category: "PowerShell Basics",
    tags: ["Get-ChildItem", "Set-Location", "Get-Content", "PowerShell"],
  },
  {
    id: "ps-variables",
    route: "/windows-labs/ps-variables",
    title: "Variables, Objects & the Pipeline",
    description: "Understand PowerShell's object-oriented pipeline. Create variables, use Select-Object, Where-Object, and pipe data between cmdlets.",
    difficulty: "Beginner",
    duration: 25,
    category: "PowerShell Basics",
    tags: ["Variables", "Pipeline", "Where-Object", "Select-Object", "PowerShell"],
  },
  {
    id: "ps-files",
    route: "/windows-labs/ps-files",
    title: "File & Directory Operations",
    description: "Create, copy, move, rename, and delete files and directories. Read and write file content using PowerShell cmdlets.",
    difficulty: "Beginner",
    duration: 25,
    category: "PowerShell Basics",
    tags: ["New-Item", "Copy-Item", "Move-Item", "Remove-Item", "PowerShell"],
  },
  {
    id: "ps-processes",
    route: "/windows-labs/ps-processes",
    title: "Process & Service Management",
    description: "List, filter, and manage running processes and Windows services using Get-Process, Get-Service, Stop-Process, and Set-Service.",
    difficulty: "Beginner",
    duration: 25,
    category: "PowerShell Basics",
    tags: ["Get-Process", "Get-Service", "Stop-Process", "PowerShell"],
  },
  {
    id: "ps-users",
    route: "/windows-labs/ps-users",
    title: "Local User & Group Management",
    description: "Create local user accounts, manage group memberships, and set passwords using PowerShell on a Windows workstation.",
    difficulty: "Beginner",
    duration: 30,
    category: "PowerShell Basics",
    tags: ["New-LocalUser", "Add-LocalGroupMember", "Set-LocalUser", "PowerShell"],
  },
  // ── INTERMEDIATE ───────────────────────────────────────────────────────────
  {
    id: "ps-scripting",
    route: "/windows-labs/ps-scripting",
    title: "PowerShell Scripting Fundamentals",
    description: "Write reusable scripts using functions, parameters, conditionals, loops, and error handling. Learn execution policy management.",
    difficulty: "Intermediate",
    duration: 40,
    category: "PowerShell Scripting",
    tags: ["Functions", "Loops", "Try-Catch", "Execution Policy", "PowerShell"],
  },
  {
    id: "ps-registry",
    route: "/windows-labs/ps-registry",
    title: "Windows Registry Operations",
    description: "Navigate, read, and modify the Windows Registry using PowerShell. Identify persistence mechanisms and audit registry keys.",
    difficulty: "Intermediate",
    duration: 35,
    category: "PowerShell Scripting",
    tags: ["Registry", "Get-ItemProperty", "Set-ItemProperty", "HKLM", "PowerShell"],
  },
  {
    id: "ps-eventlogs",
    route: "/windows-labs/ps-eventlogs",
    title: "Windows Event Log Analysis",
    description: "Query Security, System, and Application event logs using Get-WinEvent. Filter by event ID, time range, and severity to hunt threats.",
    difficulty: "Intermediate",
    duration: 35,
    category: "PowerShell Scripting",
    tags: ["Get-WinEvent", "Event Logs", "Threat Hunting", "4624", "PowerShell"],
  },
  {
    id: "ps-networking",
    route: "/windows-labs/ps-networking",
    title: "Network Configuration & Diagnostics",
    description: "Inspect network adapters, test connectivity, resolve DNS, and audit listening ports using PowerShell networking cmdlets.",
    difficulty: "Intermediate",
    duration: 30,
    category: "PowerShell Scripting",
    tags: ["Get-NetAdapter", "Test-NetConnection", "Resolve-DnsName", "netstat", "PowerShell"],
  },
  {
    id: "ps-remoting",
    route: "/windows-labs/ps-remoting",
    title: "PowerShell Remoting & WMI",
    description: "Enable and use PowerShell Remoting (WinRM), run commands on remote hosts with Invoke-Command, and query system info via WMI/CIM.",
    difficulty: "Intermediate",
    duration: 40,
    category: "PowerShell Scripting",
    tags: ["Invoke-Command", "WinRM", "WMI", "CIM", "PowerShell"],
  },
];