import React from "react";
import { X, Cpu, Server, Shield, Router, Network, Wifi, MonitorSpeaker, Phone, Scale, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";

const TYPE_META = {
  router: {
    icon: Router,
    color: "#0ea5e9",
    title: "Router",
    description: "Forwards packets between networks using routing protocols.",
  },
  switch: {
    icon: Network,
    color: "#22d3ee",
    title: "Switch",
    description: "Connects devices within the same network segment at Layer 2/3.",
  },
  firewall: {
    icon: Shield,
    color: "#f43f5e",
    title: "Firewall",
    description: "Inspects and filters traffic to protect the network perimeter.",
  },
  server: {
    icon: Server,
    color: "#a855f7",
    title: "Server",
    description: "Provides services such as web, file, database, or application hosting.",
  },
  internet: {
    icon: Cpu,
    color: "#64748b",
    title: "Internet / Cloud",
    description: "External network or ISP uplink.",
  },
  loadbalancer: {
    icon: Scale,
    color: "#f59e0b",
    title: "Load Balancer",
    description: "Distributes incoming traffic across multiple servers for high availability.",
  },
  wireless: {
    icon: Wifi,
    color: "#10b981",
    title: "Wireless Access Point",
    description: "Provides Wi-Fi connectivity to wireless end devices.",
  },
  workstation: {
    icon: MonitorSpeaker,
    color: "#6ab7e8",
    title: "Workstation / PC",
    description: "End-user desktop or laptop computer.",
  },
  phone: {
    icon: Phone,
    color: "#7ba7c7",
    title: "IP Phone",
    description: "VoIP endpoint for voice communication over the network.",
  },
  ot: {
    icon: Cpu,
    color: "#dc2626",
    title: "OT/ICS Device",
    description: "Operational Technology device such as PLC, SCADA, or industrial controller.",
  },
};

function generateFullConfig(node, design) {
  const hostname = node.label.replace(/\n/g, " ").replace(/\s+/g, "-");
  const domain = design?.domain_name || "corp.local";
  const ntp = design?.ntp_server || "pool.ntp.org";
  const dns = (design?.dns_servers || ["8.8.8.8"]).join(" ");
  const username = design?.device_username || "admin";
  const password = design?.device_password || "cisco";
  const enable = design?.enable_password || "enable123";
  
  // Security warning note
  const pwWarning = `! ⚠️  CRITICAL: DEFAULT CREDENTIALS IN THIS CONFIG\n! ⚠️  Username: ${username} | Enable Secret: ${enable}\n! ⚠️  Change IMMEDIATELY before any production deployment\n`;

  const isJuniper = (design?.router_model || design?.switch_model || "").match(/Juniper|vMX|EX/i);

  if (node.type === "router") {
    if (isJuniper) {
      let cfg = `## ${hostname} — Juniper JunOS Router Configuration
system {
    host-name ${hostname};
    domain-name ${domain};
    time-zone UTC;
    name-server { ${dns}; }
    ntp { server ${ntp}; }
    login {
        user ${username} {
            class super-user;
            authentication { encrypted-password "${password}"; }
        }
    }
    services { ssh { protocol-version v2; } netconf { ssh; } }
    syslog { file messages { any notice; } }
}
protocols {
`;
      if (design?.routing_protocol === "OSPF" || !design?.routing_protocol)
        cfg += `    ospf { area 0.0.0.0 { interface all; } }\n`;
      else if (design?.routing_protocol === "BGP")
        cfg += `    bgp { group IBGP { type internal; local-as 65001; } }\n`;
      else if (design?.routing_protocol === "EIGRP")
        cfg += `    # EIGRP not native in JunOS — use OSPF or BGP\n`;
      cfg += `}\n## End of configuration`;
      return cfg;
    }

    let cfg = `! ${hostname} — Cisco IOS Router Configuration
! Generated by Xtreme I.C.E. Network Designer
! ============================================
${pwWarning}
hostname ${hostname}
ip domain-name ${domain}
!
! === Security ===
enable secret ${enable}
username ${username} privilege 15 secret ${password}
!
service password-encryption
no ip http server
no ip http secure-server
!
! === SSH ===
crypto key generate rsa modulus 2048
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3
!
! === AAA ===
aaa new-model
aaa authentication login default local
aaa authorization exec default local
!
! === Management ===
line con 0
 login local
 logging synchronous
line vty 0 4
 login local
 transport input ssh
 exec-timeout 10 0
!
! === NTP ===
ntp server ${ntp}
clock timezone UTC 0
!
! === DNS ===
ip name-server ${dns}
!
! === Routing (${design?.routing_protocol || "OSPF"}) ===
`;
    if (design?.routing_protocol === "OSPF" || !design?.routing_protocol)
      cfg += `router ospf 1\n auto-cost reference-bandwidth 10000\n passive-interface default\n!\n`;
    else if (design?.routing_protocol === "BGP")
      cfg += `router bgp 65001\n bgp log-neighbor-changes\n no auto-summary\n!\n`;
    else if (design?.routing_protocol === "EIGRP")
      cfg += `router eigrp 100\n no auto-summary\n!\n`;
    else
      cfg += `! Static routes — configure manually\n!\n`;

    if (design?.wan_technology === "IPSec VPN") {
      cfg += `! === IPSec VPN ===
crypto isakmp policy 10
 encr aes 256
 hash sha256
 authentication pre-share
 group 14
!
crypto ipsec transform-set TS esp-aes 256 esp-sha256-hmac
 mode tunnel
!
`;
    }
    cfg += `! === Logging ===
logging buffered 16384 informational
logging console warnings
!
! === SNMP ===
snmp-server community public RO
snmp-server location Lab
snmp-server contact admin@${domain}
!
end`;
    return cfg;
  }

  if (node.type === "switch") {
    if (isJuniper) {
      const vlans = design?.vlan_names || [];
      let cfg = `## ${hostname} — Juniper JunOS Switch Configuration
system {
    host-name ${hostname};
    domain-name ${domain};
    ntp { server ${ntp}; }
    login {
        user ${username} {
            class super-user;
            authentication { encrypted-password "${password}"; }
        }
    }
    services { ssh { protocol-version v2; } }
}
vlans {
`;
      vlans.forEach((vlan, i) => {
        cfg += `    ${vlan.replace(/\s+/g, "_")} { vlan-id ${i + 10}; }\n`;
      });
      cfg += `}\nprotocols { rstp; }\n## End of configuration`;
      return cfg;
    }

    const vlans = design?.vlan_names || [];
    let cfg = `! ${hostname} — Cisco IOS Switch Configuration
! Generated by Xtreme I.C.E. Network Designer
! ============================================
${pwWarning}
hostname ${hostname}
ip domain-name ${domain}
!
! === Security ===
enable secret ${enable}
username ${username} privilege 15 secret ${password}
!
service password-encryption
!
! === SSH ===
crypto key generate rsa modulus 2048
ip ssh version 2
!
! === AAA ===
aaa new-model
aaa authentication login default local
aaa authorization exec default local
!
line con 0
 login local
 logging synchronous
line vty 0 4
 login local
 transport input ssh
 exec-timeout 10 0
!
! === VLANs ===
`;
    vlans.forEach((vlan, i) => {
      cfg += `vlan ${i + 10}\n name ${vlan.replace(/\s+/g, "_")}\n!\n`;
    });
    if (!vlans.length) cfg += `! No VLANs configured\n!\n`;
    cfg += `! === Spanning Tree ===
spanning-tree mode rapid-pvst
spanning-tree portfast default
!
! === Port Security (apply per interface) ===
! switchport port-security maximum 2
! switchport port-security violation restrict
!
! === NTP ===
ntp server ${ntp}
!
! === DNS ===
ip name-server ${dns}
!
! === Logging ===
logging buffered 16384 informational
!
! === SNMP ===
snmp-server community public RO
snmp-server location Lab
snmp-server contact admin@${domain}
!
end`;
    return cfg;
  }

  if (node.type === "firewall") {
    const vendor = design?.firewall_vendor || "Cisco ASA";
    if (vendor.includes("Palo")) {
      return `## ${hostname} — Palo Alto Firewall Configuration
set deviceconfig system hostname ${hostname}
set deviceconfig system domain ${domain}
set deviceconfig system dns-setting servers primary ${dns.split(" ")[0]}
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address ${ntp}
!
set network interface ethernet ethernet1/1 layer3 ip 203.0.113.1/30
set network interface ethernet ethernet1/2 layer3 ip 10.0.0.1/24
!
set zone trust network layer3 ethernet1/2
set zone untrust network layer3 ethernet1/1
!
set security policy-rule "Allow-Outbound" from trust to untrust action allow
set security policy-rule "Deny-All" from any to any action deny
!
set network virtual-router default routing-table ip static-route default-route nexthop ip-address 203.0.113.254`;
    }
    if (vendor.includes("Fortinet")) {
      return `## ${hostname} — Fortinet FortiGate Configuration
config system global
    set hostname ${hostname}
    set domain ${domain}
end
config system dns
    set primary ${dns.split(" ")[0]}
end
config system ntp
    set server ${ntp}
end
config firewall policy
    edit 1
        set name "Allow-LAN-WAN"
        set srcintf "internal"
        set dstintf "wan1"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
    next
end`;
    }
    // Default: Cisco ASA
    return `! ${hostname} — Cisco ASA Firewall Configuration
! Generated by Xtreme I.C.E. Network Designer
! ============================================
${pwWarning}
hostname ${hostname}
domain-name ${domain}
!
! === Credentials ===
enable password ${enable} encrypted
username ${username} password ${password} privilege 15
!
! === Interfaces ===
interface GigabitEthernet0/0
 nameif outside
 security-level 0
 ip address dhcp
!
interface GigabitEthernet0/1
 nameif inside
 security-level 100
 ip address 10.0.0.1 255.255.255.0
!
${design?.dmz_required ? `interface GigabitEthernet0/2
 nameif dmz
 security-level 50
 ip address 172.16.0.1 255.255.255.0
!` : ""}
! === NAT ===
object network OBJ-INSIDE
 subnet 10.0.0.0 255.255.255.0
 nat (inside,outside) dynamic interface
!
! === Access Control ===
access-list OUTSIDE-IN extended permit tcp any any established
access-list OUTSIDE-IN extended deny ip any any log
access-group OUTSIDE-IN in interface outside
!
! === NTP ===
ntp server ${ntp} source outside
!
! === DNS ===
dns name-server ${dns}
!
! === SSH ===
ssh timeout 10
ssh version 2
aaa authentication ssh console LOCAL
!
! === Logging ===
logging enable
logging buffered informational
!
end`;
  }

  if (node.type === "server") {
    return `# ${hostname} — Server Configuration
# Generated by Xtreme I.C.E. Network Designer
# ============================================
#
hostname: ${hostname}.${domain}
#
# === Network ===
ip_address: (assign from ${design?.ip_scheme || "10.0.0.0/8"})
gateway: 10.0.0.1
dns_servers:
${(design?.dns_servers || ["8.8.8.8"]).map(d => `  - ${d}`).join("\n")}
#
# === Time ===
ntp_server: ${ntp}
timezone: UTC
#
# === Services ===
ssh: enabled
snmp_community: public
syslog_server: (configure as needed)`;
  }

  if (node.type === "wireless") {
    return `! ${hostname} — Cisco Wireless AP Configuration
!
hostname ${hostname}
ip domain-name ${domain}
!
dot11 ssid ${design?.company_name?.replace(/\s/g, "-") || "CorpWLAN"}
   vlan 10
   authentication open
   authentication key-management wpa version 2
   wpa-psk ascii ${password}
!
interface Dot11Radio0
 encryption vlan 10 mode ciphers aes-ccm
 ssid ${design?.company_name?.replace(/\s/g, "-") || "CorpWLAN"}
 station-role root
!
interface BVI1
 ip address dhcp
!
ntp server ${ntp}
ip name-server ${dns}
!
end`;
  }

  if (node.type === "ot") {
    return `# ${hostname} — OT/ICS Device Configuration
# Device: ${node.label.replace(/\n/g, " ")}
# Network: Segregated OT Segment
# ============================================
#
hostname: ${hostname}
ip_address: ${node.ip || "192.168.100.x"}
subnet_mask: 255.255.255.0
gateway: 192.168.100.1
dns:
  - ${dns.split(" ")[0]}
ntp_server: ${ntp}
#
# === Security Controls ===
ingress_firewall: enabled
anomaly_detection: enabled
rate_limiting: enabled
protocol_whitelisting: enabled
#
# === Segmentation ===
vlan: OT-Segment
firewall_zone: ot-dmz`;
  }

  return null;
}

export default function DeviceDetailPanel({ node, design, onClose, onSaveConfig }) {
  if (!node) return null;

  const meta = TYPE_META[node.type] || TYPE_META["switch"];
  const Icon = meta.icon;
  const snippet = generateFullConfig(node, design);
  const displayLabel = node.label.replace(/\n/g, " ");

  const props = [];
  if (node.type === "router") {
    props.push(["Model", design?.router_model || "Generic Router"]);
    props.push(["Protocol", design?.routing_protocol || "—"]);
    props.push(["WAN", design?.wan_technology || "—"]);
    if (design?.device_username) props.push(["Username", design.device_username]);
    if (design?.domain_name) props.push(["Domain", design.domain_name]);
  } else if (node.type === "switch") {
    props.push(["Model", design?.switch_model || "Generic L2/L3"]);
    props.push(["VLANs", design?.num_vlans_per_site ?? "—"]);
    if (design?.vlan_names?.length) props.push(["VLAN Names", design.vlan_names.join(", ")]);
    if (design?.device_username) props.push(["Username", design.device_username]);
  } else if (node.type === "firewall") {
    props.push(["Vendor", design?.firewall_vendor || "—"]);
    props.push(["DMZ", design?.dmz_required ? "Yes" : "No"]);
    props.push(["Redundancy", design?.redundancy_enabled ? "Enabled" : "Disabled"]);
  } else if (node.type === "server") {
    props.push(["Count", design?.num_servers ?? "—"]);
    if (design?.ntp_server) props.push(["NTP", design.ntp_server]);
    if (design?.dns_servers?.length) props.push(["DNS", design.dns_servers.join(", ")]);
  } else if (node.type === "loadbalancer") {
    props.push(["Mode", "Round-Robin / L7"]);
    props.push(["Backend Servers", design?.num_servers ?? "—"]);
  } else if (node.type === "wireless") {
    props.push(["SSID", design?.company_name?.replace(/\s/g, "-") || "CorpWLAN"]);
    props.push(["Security", "WPA2-AES"]);
  } else if (node.type === "workstation" || node.type === "phone") {
    props.push(["Type", displayLabel]);
    props.push(["Total Devices", design?.num_user_devices ?? "—"]);
  } else if (node.type === "internet") {
  props.push(["WAN Tech", design?.wan_technology || "—"]);
  props.push(["Protocol", design?.routing_protocol || "—"]);
  } else if (node.type === "ot") {
  props.push(["Device Type", displayLabel]);
  props.push(["Category", "Operational Technology"]);
  props.push(["Network Segment", design?.ot_network_segment || "Segregated OT Network"]);
  }

  return (
    <div className="bg-card border border-border rounded-xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border" style={{ borderLeftColor: meta.color, borderLeftWidth: 3 }}>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <div className="h-7 w-7 rounded-lg flex items-center justify-center" style={{ backgroundColor: meta.color + "22" }}>
              <Icon className="h-4 w-4" style={{ color: meta.color }} />
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground leading-none">{displayLabel}</p>
              <p className="text-[10px] text-muted-foreground mt-0.5">{meta.title}</p>
            </div>
          </div>

        </div>
        <div className="flex gap-1">
          <Button variant="ghost" size="icon" className="h-6 w-6" onClick={onClose}>
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>
      </div>

      {/* Description */}
      <div className="px-4 py-2 text-xs text-muted-foreground border-b border-border/50">
        {meta.description}
      </div>

      {/* Properties */}
      {props.length > 0 && (
        <div className="px-4 py-3 border-b border-border/50 space-y-1.5">
          <p className="text-[10px] uppercase tracking-widest text-muted-foreground mb-2">Properties</p>
          {props.map(([k, v]) => (
            <div key={k} className="flex justify-between text-xs">
              <span className="text-muted-foreground">{k}</span>
              <span className="text-foreground font-mono font-medium">{String(v)}</span>
            </div>
          ))}
        </div>
      )}

      {/* Full device config */}
      {snippet && (
        <div className="px-4 py-3 border-t border-border/50">
          <div className="flex items-center justify-between mb-2">
            <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Full Device Configuration</p>
            <div className="flex gap-1">
              <button
                onClick={() => {
                  const ext = (design?.router_model || design?.switch_model || "").match(/Juniper|vMX|EX/i) ? "conf" : "cfg";
                  const blob = new Blob([snippet], { type: "text/plain" });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = `${node.label.replace(/\s+/g, "-").replace(/\n/g, "-")}.${ext}`;
                  a.click();
                  URL.revokeObjectURL(url);
                }}
                className="p-1 hover:bg-secondary rounded transition-colors"
                title="Download config"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3 text-muted-foreground hover:text-foreground" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
              </button>
              <button
                onClick={() => navigator.clipboard.writeText(snippet)}
                className="p-1 hover:bg-secondary rounded transition-colors"
                title="Copy config"
              >
                <Copy className="h-3 w-3 text-muted-foreground hover:text-foreground" />
              </button>
            </div>
          </div>
          <pre className="text-[10px] leading-relaxed text-cyan-300 bg-[#0b1120] rounded-lg p-3 overflow-x-auto whitespace-pre-wrap font-mono max-h-[500px] overflow-y-auto">
            {snippet}
          </pre>
        </div>
      )}


    </div>
  );
}