import React,{useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {Router,Network,Shield,Server,Wifi,Monitor,Cloud,Cpu} from "lucide-react";
import {parseConfiguration,buildSnapshot,DEVICE_TYPES} from "./parser";
const icons={router:Router,switch:Network,firewall:Shield,server:Server,wireless:Wifi,workstation:Monitor,cloud:Cloud,plc:Cpu};
const input="w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-base text-white";
const button="rounded-lg border border-cyan-600 bg-cyan-950 px-4 py-3 text-cyan-100 disabled:opacity-40";
function Field({label,children}){return <label className="block"><span className="mb-1 block text-sm text-slate-300">{label}</span>{children}</label>;}
export function SnapshotTopology({snapshot,onSelect}){
 const nodes=snapshot.nodes.map((n,i)=>({...n,x:25+(i%4)*210,y:25+Math.floor(i/4)*130}));
 return <div className="overflow-auto rounded-xl border border-slate-700 bg-slate-950"><svg aria-label="Imported network topology" width="870" height={Math.max(200,Math.ceil(nodes.length/4)*130+35)}>
 {snapshot.links.map(l=>{const a=nodes.find(n=>n.id===l.from),b=nodes.find(n=>n.id===l.to);return a&&b?<g key={l.id}><line x1={a.x+85} y1={a.y+40} x2={b.x+85} y2={b.y+40} stroke={l.confirmed?"#22d3ee":"#fbbf24"} strokeWidth="2" strokeDasharray={l.confirmed?undefined:"6 4"}/><title>{l.label} · {l.provenance}</title></g>:null;})}
 {nodes.map(n=>{const Icon=icons[n.type]||Network;return <foreignObject key={n.id} x={n.x} y={n.y} width="175" height="100"><button onClick={()=>onSelect(n.id)} className="h-full w-full rounded-xl border border-cyan-700 bg-slate-900 p-3 text-left text-white"><Icon size={22}/><span className="block truncate font-bold">{n.label}</span><span className="block truncate text-xs text-cyan-200">{n.vendor||"Vendor unknown"} · {n.type}</span><span className="block truncate text-xs text-slate-300">{n.ip||"Address unknown"}</span></button></foreignObject>;})}
 </svg></div>;
}
export default function NetworkImport({onBack,existing=null}){
 const navigate=useNavigate();
 const initial=()=>{try{return existing?.import_snapshot?JSON.parse(existing.import_snapshot):null;}catch{return null;}};
 const [snapshot,setSnapshot]=useState(initial),[name,setName]=useState(existing?existing.name+" — revision":""),[org,setOrg]=useState(existing?.organization_id||""),[orgs,setOrgs]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[selected,setSelected]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[linkLabel,setLinkLabel]=useState("");
 useEffect(()=>{let live=true;base44.functions.invoke("import-network-design",{action:"organizations"}).then(r=>{if(live){setOrgs(r.data.organizations);if(!org&&r.data.organizations.length===1)setOrg(r.data.organizations[0].id);}}).catch(()=>{if(live)setError("Could not load your organizations. Reload and sign in again.");});return()=>{live=false;};},[]);
 const update=(id,p)=>setSnapshot(s=>({...s,nodes:s.nodes.map(n=>n.id===id?{...n,...p,reviewed:false}:n)}));
 async function upload(files){
 setBusy(true);setError("");setProgress("Reading files locally…");
 try{
 if(!files.length||files.length>30)throw Error("Choose 1–30 files.");
 if(files.some(f=>f.size>2*1024*1024)||files.reduce((a,f)=>a+f.size,0)>8*1024*1024)throw Error("Limit: 2 MB per file and 8 MB total.");
 const devices=[];
 for(let i=0;i<files.length;i++){setProgress("Extracting file "+(i+1)+" of "+files.length);const text=await files[i].text();devices.push(...parseConfiguration(text,files[i].name));}
 const result=buildSnapshot(devices);setSnapshot(result);setSelected(result.nodes[0]?.id||"");if(!name)setName("Imported network");setProgress("Ready for review");
 }catch(e){setError(e.message);setProgress("Import needs attention");}finally{setBusy(false);}
 }
 async function save(){
 setBusy(true);setError("");try{const r=await base44.functions.invoke("import-network-design",{action:"save",name,organization_id:org,parent_id:existing?.id||undefined,snapshot});navigate("/ReviewDesign?id="+r.data.id);}
 catch(e){setError(e.response?.data?.error||"Could not save the reviewed network. Please retry.");}finally{setBusy(false);}
 }
 const current=snapshot?.nodes.find(n=>n.id===selected);
 let changes=null;if(existing&&snapshot){const prev=initial()?.nodes||[];const old=new Map(prev.map(n=>[n.label,n]));const added=snapshot.nodes.filter(n=>!old.has(n.label)).length;const removed=prev.filter(n=>!snapshot.nodes.some(x=>x.label===n.label)).length;const changed=snapshot.nodes.filter(n=>old.has(n.label)&&JSON.stringify([n.type,n.vendor,n.model,n.interfaces,n.protocols,n.vlans,n.routes,n.policies,n.services,n.tunnels])!==JSON.stringify([old.get(n.label).type,old.get(n.label).vendor,old.get(n.label).model,old.get(n.label).interfaces,old.get(n.label).protocols,old.get(n.label).vlans,old.get(n.label).routes,old.get(n.label).policies,old.get(n.label).services,old.get(n.label).tunnels])).length;changes=added+" added · "+removed+" removed · "+changed+" devices changed";}
 return <div className="min-h-screen bg-slate-950 p-5 text-slate-100"><div className="mx-auto max-w-7xl space-y-5">
 <button className={button} onClick={onBack} disabled={busy}>← Back</button>
 <h1 className="text-3xl font-bold">Import Network / Create Digital Twin</h1><p className="text-slate-300">Create a reviewed configuration snapshot. Raw files stay in your browser; only extracted network fields are saved. Credentials, keys, certificates, and raw command scripts are not imported. No AI receives your configuration files.</p>
 <div className="grid gap-4 rounded-xl border border-slate-700 bg-slate-900 p-5 md:grid-cols-2"><Field label="Design name"><input className={input} value={name} maxLength={250} onChange={e=>setName(e.target.value)}/></Field><Field label="Organization"><select className={input} value={org} disabled={!!existing} onChange={e=>setOrg(e.target.value)}><option value="">Select organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>
 <Field label="Configuration files — selection replaces the current import"><input disabled={busy} className={input} type="file" multiple accept=".txt,.cfg,.conf,.config,.xml,.csv" onChange={e=>{upload([...e.target.files]);e.target.value="";}}/></Field>
 <div className="text-sm leading-6 text-slate-300">Cisco IOS text, FortiGate single-VDOM text, pfSense XML, or CSV. Up to 30 files, 2 MB each, 8 MB total, 200 devices. Export encrypted backups as readable configuration first.<br/><a className="text-cyan-300 underline" download="network-inventory.csv" href={"data:text/csv;charset=utf-8,"+encodeURIComponent("name,type,vendor,model,ip,site,protocols,connects_to\nCore,router,Cisco,,10.0.0.1,HQ,OSPF,Access\nAccess,switch,Cisco,,10.0.0.2,HQ,,\n")}>Download inventory template</a></div></div>
 {progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="rounded-lg border border-rose-500 p-4 text-rose-200">{error}</p>}
 {snapshot&&<><div className="rounded-xl border border-amber-700 bg-amber-950/20 p-4"><b>Configuration snapshot · review required</b>{snapshot.warnings.map((w,i)=><p className="mt-2 text-sm text-amber-100" key={i}>{w}</p>)}{changes&&<p className="mt-3">Compared with version {existing.import_version}: {changes}. Connections: {initial()?.links?.length||0} → {snapshot.links.length}. Saving creates a new version; the previous design remains unchanged.</p>}</div>
 <SnapshotTopology snapshot={snapshot} onSelect={setSelected}/>
 <div className="grid gap-5 xl:grid-cols-[1fr_1.3fr]"><section className="space-y-3"><h2 className="text-xl font-bold">Review devices ({snapshot.nodes.length})</h2><button className={button} disabled={snapshot.nodes.length>=200} onClick={()=>setSnapshot(s=>({...s,nodes:[...s.nodes,{id:crypto.randomUUID(),label:"New device",type:"server",vendor:"",model:"",site:"",provenance:"user-confirmed",role_provenance:"user-confirmed",interfaces:[],protocols:[],vlans:[],routes:[],policies:[],services:[],tunnels:[],source_file:"Manual entry",ip:"",x:100,y:100,reviewed:false}]}))}>Add missing device</button>{snapshot.nodes.map(n=><div className="rounded-lg border border-slate-700 bg-slate-900 p-4" key={n.id}><div className="grid gap-2 sm:grid-cols-2"><Field label="Device name"><input className={input} value={n.label} onChange={e=>update(n.id,{label:e.target.value,provenance:"user-confirmed"})}/></Field><Field label={"Device role · "+n.role_provenance}><select className={input} value={n.type} onChange={e=>update(n.id,{type:e.target.value,role_provenance:"user-confirmed"})}>{DEVICE_TYPES.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Primary address (blank = unknown)"><input className={input} value={n.ip} onChange={e=>update(n.id,{ip:e.target.value,interfaces:[{name:n.interfaces[0]?.name||"management",addresses:[e.target.value],provenance:"user-confirmed"},...n.interfaces.slice(1)],provenance:"user-confirmed"})}/></Field><Field label="Protocols (comma separated)"><input className={input} value={n.protocols.join(", ")} onChange={e=>update(n.id,{protocols:e.target.value.split(",").map(x=>x.trim()),provenance:"user-confirmed"})}/></Field>{["vendor","model","site"].map(k=><Field key={k} label={k+" (blank = unknown)"}><input className={input} value={n[k]} onChange={e=>update(n.id,{[k]:e.target.value,provenance:"user-confirmed"})}/></Field>)}</div><div className="mt-3 flex flex-wrap items-center gap-4"><button className="text-cyan-300 underline" onClick={()=>setSelected(n.id)}>Inspect extracted details</button><label><input type="checkbox" checked={n.reviewed} onChange={e=>setSnapshot(s=>({...s,nodes:s.nodes.map(x=>x.id===n.id?{...x,reviewed:e.target.checked}:x)}))}/> Reviewed</label><button className="text-rose-300" onClick={()=>setSnapshot(s=>({...s,nodes:s.nodes.filter(x=>x.id!==n.id),links:s.links.filter(l=>l.from!==n.id&&l.to!==n.id)}))}>Remove</button></div></div>)}</section>
 <section className="space-y-4"><div className="rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">{current?.label||"Select a device to inspect"}</h2>{current&&<DeviceDetails node={current}/>}</div>
 <div className="rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">Connections</h2><p className="my-2 text-sm text-slate-300">No physical links are inferred from shared addresses. Confirm inventory links or add a connection you know exists. Include ports or protocols in the label.</p>
 {snapshot.links.map(l=><div key={l.id} className="my-3 border-b border-slate-700 pb-3"><p>{snapshot.nodes.find(n=>n.id===l.from)?.label} → {snapshot.nodes.find(n=>n.id===l.to)?.label}: {l.label} · {l.provenance}</p><label><input type="checkbox" checked={l.confirmed} onChange={e=>setSnapshot(s=>({...s,links:s.links.map(x=>x.id===l.id?{...x,confirmed:e.target.checked}:x)}))}/> Confirm connection</label><button className="ml-4 text-rose-300" onClick={()=>setSnapshot(s=>({...s,links:s.links.filter(x=>x.id!==l.id)}))}>Remove</button></div>)}
 <div className="space-y-3">{[["From",from,setFrom],["To",to,setTo]].map(([label,value,set])=><Field key={label} label={label}><select className={input} value={value} onChange={e=>set(e.target.value)}><option value="">Select device</option>{snapshot.nodes.map(n=><option value={n.id} key={n.id}>{n.label}</option>)}</select></Field>)}<Field label="Connection label"><input className={input} value={linkLabel} maxLength={250} onChange={e=>setLinkLabel(e.target.value)} placeholder="Gi0/1 to port1 · trunk VLANs 10,20"/></Field><button className={button} disabled={!from||!to||from===to||!linkLabel.trim()} onClick={()=>{setSnapshot(s=>({...s,links:[...s.links,{id:crypto.randomUUID(),from,to,label:linkLabel,provenance:"user-confirmed",confirmed:true}]}));setLinkLabel("");}}>Add confirmed connection</button></div></div></section></div>
 <div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-cyan-700 bg-slate-950 p-4"><p>{snapshot.nodes.filter(n=>n.reviewed).length}/{snapshot.nodes.length} devices reviewed · {snapshot.links.filter(l=>l.confirmed).length}/{snapshot.links.length} connections confirmed</p><button className={button} disabled={busy||!name.trim()||!org||!snapshot.nodes.length||snapshot.nodes.some(n=>!n.reviewed||!n.label.trim())||snapshot.links.some(l=>!l.confirmed)} onClick={save}>{busy?"Saving…":existing?"Save new version":"Save reviewed topology"}</button></div></>}
 </div></div>;
}
export function DeviceDetails({node}){
 return <div className="mt-3 space-y-4 text-sm leading-6"><p>Vendor: {node.vendor||"Unknown"} · Model: {node.model||"Unknown"} · Role: {node.type} ({node.role_provenance})</p><p>Configured protocols: {node.protocols.join(", ")||"Not identified"}</p><p>Source: {node.source_file} · {node.provenance}</p>{["interfaces","vlans","routes","policies","services","tunnels"].map(k=><details key={k}><summary className="cursor-pointer font-bold capitalize text-cyan-200">{k} ({node[k]?.length||0})</summary><div className="max-h-72 overflow-auto">{(node[k]||[]).map((v,i)=><p key={i} className="break-words border-b border-slate-700 py-2">{typeof v==="string"?v:Object.entries(v).map(([key,val])=>key+": "+(Array.isArray(val)?val.join(", "):val)).join(" · ")}</p>)}</div></details>)}</div>;
}
export function SavedNetworkSnapshot({design,onRevise}){
 const [selected,setSelected]=useState("");let s;try{s=JSON.parse(design.import_snapshot);}catch{return <p>Unable to read this configuration snapshot.</p>;}
 // Prefer current diagram positions and links after visual edits; retained import facts remain on each device.
 try{const d=JSON.parse(design.diagram_data);if(d.nodes?.length)s={...s,nodes:d.nodes,links:d.links||[]};}catch{}
 const n=s.nodes.find(x=>x.id===selected);
 return <section className="space-y-4 rounded-xl border border-cyan-800 bg-slate-900 p-5 text-slate-100"><h2 className="text-xl font-bold">Configuration snapshot · version {design.import_version}</h2><p>Imported {new Date(JSON.parse(design.import_snapshot).imported_at).toLocaleString()}. This is a reviewed design snapshot, not live telemetry or an emulated console.</p><SnapshotTopology snapshot={s} onSelect={setSelected}/>{n&&<DeviceDetails node={n}/>}<button className={button} onClick={onRevise}>Import update / create new version</button>{design.parent_design_id&&<a className="ml-4 text-cyan-300 underline" href={"/ReviewDesign?id="+design.parent_design_id}>View previous version</a>}</section>;
}
