import React,{useEffect,useState} from "react";
import {base44} from "@/api/base44Client";
import {toTTXNetwork} from "./toTTXNetwork";
export default function TTXNetworkImport({profile,onChoose}){
 const [orgs,setOrgs]=useState([]),[org,setOrg]=useState(profile.organization_id||""),[designs,setDesigns]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[chosen,setChosen]=useState("");
 useEffect(()=>{let active=true;base44.functions.invoke("import-network-design",{action:"organizations"}).then(r=>{if(active)setOrgs(r.data.organizations);}).catch(()=>{if(active)setError("Network imports are currently unavailable.");});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;setDesigns([]);setChosen("");if(org){setBusy(true);base44.functions.invoke("import-network-design",{action:"designs",organization_id:org}).then(r=>{if(active)setDesigns(r.data.designs);}).catch(()=>{if(active)setError("Could not load this organization's network designs.");}).finally(()=>{if(active)setBusy(false);});}return()=>{active=false;};},[org]);
 const style="rounded-lg border border-slate-600 bg-slate-950 p-3 text-white";
 return <div className="mt-5 rounded-xl border border-cyan-700 p-4"><h3 className="font-bold text-cyan-200">Use an imported network snapshot</h3><p className="my-2 text-sm text-slate-300">Choose a reviewed design for this company. This replaces the draft topology; save the company profile to use it in future exercises. Existing attempts retain their saved networks.</p><div className="flex flex-wrap gap-3"><select aria-label="Network organization" className={style} disabled={!!profile.organization_id} value={org} onChange={e=>{setOrg(e.target.value);setError("");}}><option value="">Select organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><select aria-label="Imported network design" className={style} value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">{busy?"Loading…":"Select configuration snapshot"}</option>{designs.map(d=><option key={d.id} value={d.id}>{d.name} · v{d.version}</option>)}</select><button disabled={!chosen||busy} className={style+" disabled:opacity-40"} onClick={()=>{const d=designs.find(d=>d.id===chosen);if(d)onChoose(toTTXNetwork(d,profile),org);}}>Use snapshot</button><a className="p-3 text-cyan-300 underline" href="/NetworkWizard">Create a network import</a></div>{error&&<p role="alert" className="mt-2 text-rose-300">{error}</p>}{profile.network_model?.import_note&&<p className="mt-3 text-sm text-amber-200">{profile.network_model.import_note}</p>}</div>;
}
