import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, Loader2, ChevronDown, ChevronRight, Terminal } from "lucide-react";
import { base44 } from "@/api/base44Client";
import InteractiveTopology from "@/components/review/InteractiveTopology";
import { generateDeviceConfig, detectVendor, configFileExtension } from "@/components/cyberevents/deviceConfigGenerators";

// --- Legacy local generators kept temporarily below for reference only ---
// All config generation now routes through the shared deviceConfigGenerators module.

function generateCiscoIOS_LEGACY(device, data) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = data.domain_name || "corp.local";
  const ntp = data.ntp_server || "pool.ntp.org";
  const dns = (data.dns_servers || []).join(" ") || "8.8.8.8";
  const username = data.device_username || "admin";
  const password = data.device_password || "cisco";
  const enable = data.enable_password || "enable123";

  let config = `! ${device.label} - Cisco IOS Configuration
! Generated by NetForge EVE-NG Designer
! ============================================
!
hostname ${hostname}
ip domain-name ${domain}
!
! === Security ===
enable secret ${enable}
username ${username} privilege 15 secret ${password}
!
service password-encryption
no ip http server
no ip http secure-server
!
! === SSH ===
crypto key generate rsa modulus 2048
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3
!
! === AAA ===
aaa new-model
aaa authentication login default local
aaa authorization exec default local
!
! === Management ===
line con 0
 login local
 logging synchronous
line vty 0 4
 login local
 transport input ssh
 exec-timeout 10 0
!
! === NTP ===
ntp server ${ntp}
clock timezone UTC 0
!
! === DNS ===
ip name-server ${dns}
!
`;

  if (device.type === "router") {
    config += `! === Routing (${data.routing_protocol || "OSPF"}) ===\n`;
    if (data.routing_protocol === "OSPF" || !data.routing_protocol) {
      config += `router ospf 1\n auto-cost reference-bandwidth 10000\n passive-interface default\n!
`;
    } else if (data.routing_protocol === "BGP") {
      config += `router bgp 65001\n bgp log-neighbor-changes\n no auto-summary\n!
`;
    } else if (data.routing_protocol === "EIGRP") {
      config += `router eigrp 100\n no auto-summary\n!
`;
    }
    if (data.wan_technology === "IPSec VPN") {
      config += `! === IPSec VPN ===
crypto isakmp policy 10
 encr aes 256
 hash sha256
 authentication pre-share
 group 14
!
crypto ipsec transform-set TS esp-aes 256 esp-sha256-hmac
 mode tunnel
!
`;
    }
  }

  if (device.type === "switch") {
    const vlans = data.vlan_names || [];
    config += `! === VLANs ===\n`;
    vlans.forEach((vlan, i) => {
      config += `vlan ${i + 10}\n name ${vlan.replace(/\s+/g, "_")}\n!\n`;
    });
    config += `! === Spanning Tree ===
spanning-tree mode rapid-pvst
spanning-tree portfast default
!
! === Port Security ===
! Apply per-interface as needed
!
`;
  }

  if (device.type === "firewall") {
    config += `! === Firewall / ACL Base Policy ===
ip access-list extended OUTSIDE-IN
 permit tcp any any established
 deny   ip any any log
!
ip access-list extended INSIDE-OUT
 permit ip any any
!
`;
  }

  config += `! === Logging ===
logging buffered 16384 informational
logging console warnings
!
! === SNMP ===
snmp-server community public RO
snmp-server location EVE-NG Lab
snmp-server contact admin@${domain}
!
end
`;
  return config;
}

function generateJuniperJunos(device, data) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = data.domain_name || "corp.local";
  const ntp = data.ntp_server || "pool.ntp.org";
  const username = data.device_username || "admin";
  const password = data.device_password || "Juniper1!";

  let config = `## ${device.label} - Juniper Junos Configuration
## Generated by NetForge EVE-NG Designer
## ============================================
system {
    host-name ${hostname};
    domain-name ${domain};
    time-zone UTC;
    name-server { 8.8.8.8; }
    ntp { server ${ntp}; }
    login {
        user ${username} {
            class super-user;
            authentication {
                encrypted-password "${password}";
            }
        }
    }
    services {
        ssh { protocol-version v2; }
        netconf { ssh; }
    }
    syslog {
        file messages { any notice; }
    }
}
`;

  if (device.type === "router") {
    config += `protocols {
`;
    if (data.routing_protocol === "OSPF" || !data.routing_protocol) {
      config += `    ospf { area 0.0.0.0 { interface all; } }\n`;
    } else if (data.routing_protocol === "BGP") {
      config += `    bgp { group IBGP { type internal; } }\n`;
    }
    config += `}\n`;
  }

  if (device.type === "switch") {
    const vlans = data.vlan_names || [];
    config += `vlans {\n`;
    vlans.forEach((vlan, i) => {
      config += `    ${vlan.replace(/\s+/g, "_")} { vlan-id ${i + 10}; }\n`;
    });
    config += `}\n`;
    config += `protocols { rstp; }\n`;
  }

  if (device.type === "firewall") {
    config += `security {
    policies {
        from-zone trust to-zone untrust {
            policy permit-all {
                match { source-address any; destination-address any; application any; }
                then { permit; }
            }
        }
    }
    zones {
        security-zone trust { interfaces { ge-0/0/0.0; } }
        security-zone untrust { interfaces { ge-0/0/1.0; } }
    }
}
`;
  }

  config += `## End of configuration\n`;
  return config;
}

function generateFortinetOS(device, data) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = data.domain_name || "corp.local";
  const ntp = data.ntp_server || "pool.ntp.org";
  const username = data.device_username || "admin";
  const password = data.device_password || "Fortinet1!";
  const dns1 = (data.dns_servers || ["8.8.8.8"])[0];
  const dns2 = (data.dns_servers || ["8.8.8.8", "8.8.4.4"])[1] || "8.8.4.4";

  let config = `# ${device.label} - FortiGate FortiOS Configuration
# Generated by Xtreme I.C.E. Network Designer
# ============================================

config system global
    set hostname ${hostname}
    set admintimeout 30
    set admin-sport 443
    set timezone 04
end

config system dns
    set primary ${dns1}
    set secondary ${dns2}
    set domain "${domain}"
end

config system ntp
    set ntpsync enable
    set type custom
    config ntpserver
        edit 1
            set server "${ntp}"
        next
    end
end

config system admin
    edit "${username}"
        set password "${password}"
        set accprofile "super_admin"
        set vdom "root"
    next
end

`;

  if (device.type === "firewall") {
    config += `config system interface
    edit "wan1"
        set mode dhcp
        set role wan
    next
    edit "internal"
        set ip 192.168.1.1 255.255.255.0
        set role lan
        set allowaccess ping https ssh
    next
end

config firewall address
    edit "LAN_SUBNET"
        set subnet 192.168.1.0 255.255.255.0
    next
end

config firewall policy
    edit 1
        set name "LAN-to-WAN"
        set srcintf "internal"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
        set logtraffic all
    next
    edit 2
        set name "DENY-ALL"
        set srcintf "any"
        set dstintf "any"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end

`;
    if (data.wan_technology === "IPSec VPN") {
      config += `config vpn ipsec phase1-interface
    edit "VPN-TUNNEL"
        set interface "wan1"
        set ike-version 2
        set peertype any
        set proposal aes256-sha256
        set dhgrp 14
        set psksecret "YourPreSharedKey"
        set dpd on-idle
    next
end

config vpn ipsec phase2-interface
    edit "VPN-P2"
        set phase1name "VPN-TUNNEL"
        set proposal aes256-sha256
        set pfs enable
        set dhgrp 14
    next
end

`;
    }
  }

  config += `config log setting
    set resolve-ip enable
    set resolve-port enable
    set fwpolicy-implicit-log enable
end

# End of FortiOS configuration\n`;
  return config;
}

function generatePaloAltoOS(device, data) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = data.domain_name || "corp.local";
  const ntp = data.ntp_server || "pool.ntp.org";
  const username = data.device_username || "admin";
  const password = data.device_password || "PaloAlto1!";
  const dns1 = (data.dns_servers || ["8.8.8.8"])[0];

  let config = `# ${device.label} - Palo Alto PAN-OS Configuration
# Generated by Xtreme I.C.E. Network Designer
# ============================================

set deviceconfig system hostname ${hostname}
set deviceconfig system domain ${domain}
set deviceconfig system dns-setting servers primary ${dns1}
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address ${ntp}
set deviceconfig system timezone US/Eastern

set mgt-config users ${username} password ${password}
set mgt-config users ${username} permissions role-based superuser yes

`;

  if (device.type === "firewall") {
    config += `# Security Zones
set zone trust network layer3 ethernet1/1
set zone untrust network layer3 ethernet1/2

# Interfaces
set network interface ethernet ethernet1/1 layer3 ip 192.168.1.1/24
set network interface ethernet ethernet1/2 layer3 ip dhcp

# Virtual Router
set network virtual-router default interface [ ethernet1/1 ethernet1/2 ]
set network virtual-router default routing-table ip static-route default-route destination 0.0.0.0/0 nexthop ip-address 0.0.0.0

# Security Policies
set rulebase security rules "Allow-Outbound" from trust
set rulebase security rules "Allow-Outbound" to untrust
set rulebase security rules "Allow-Outbound" source any
set rulebase security rules "Allow-Outbound" destination any
set rulebase security rules "Allow-Outbound" application any
set rulebase security rules "Allow-Outbound" service application-default
set rulebase security rules "Allow-Outbound" action allow
set rulebase security rules "Allow-Outbound" log-end yes

set rulebase security rules "Deny-All" from any
set rulebase security rules "Deny-All" to any
set rulebase security rules "Deny-All" source any
set rulebase security rules "Deny-All" destination any
set rulebase security rules "Deny-All" application any
set rulebase security rules "Deny-All" service any
set rulebase security rules "Deny-All" action deny
set rulebase security rules "Deny-All" log-end yes

# NAT Policy
set rulebase nat rules "NAT-Outbound" source-translation dynamic-ip-and-port interface-address interface ethernet1/2
set rulebase nat rules "NAT-Outbound" from trust
set rulebase nat rules "NAT-Outbound" to untrust
set rulebase nat rules "NAT-Outbound" source any
set rulebase nat rules "NAT-Outbound" destination any

`;
  }

  config += `# Commit configuration
commit

# End of PAN-OS configuration\n`;
  return config;
}

function getVendorForDevice(device, data) {
  if (device.type === "firewall") {
    const fw = (data.firewall_vendor || "").toLowerCase();
    if (fw.includes("fortinet")) return "fortinet";
    if (fw.includes("palo alto")) return "paloalto";
    if (fw.includes("pfsense")) return "cisco"; // fallback to cisco-like
    return "cisco"; // Cisco ASA
  }
  if (device.type === "router") {
    const rm = (data.router_model || "").toLowerCase();
    if (rm.includes("juniper") || rm.includes("vmx")) return "juniper";
    return "cisco";
  }
  if (device.type === "switch") {
    const sm = (data.switch_model || "").toLowerCase();
    if (sm.includes("juniper") || sm.includes("ex")) return "juniper";
    return "cisco";
  }
  return "cisco";
}

function buildDeviceList(data) {
  const devices = [];
  const sites = data.site_names?.length ? data.site_names : Array.from({ length: data.num_sites || 1 }, (_, i) => `Site${i + 1}`);

  sites.forEach((site) => {
    devices.push({ name: `${site}-Router`, label: `${site} Router`, type: "router" });
    devices.push({ name: `${site}-Switch`, label: `${site} Switch`, type: "switch" });
    if (data.firewall_enabled) {
      devices.push({ name: `${site}-Firewall`, label: `${site} Firewall`, type: "firewall" });
    }
    if (data.wireless_enabled) {
      devices.push({ name: `${site}-WAP`, label: `${site} Wireless AP`, type: "wireless" });
    }
  });

  if (data.server_farm) {
    devices.push({ name: "DC-CoreRouter", label: "DC Core Router", type: "router" });
    devices.push({ name: "DC-CoreSwitch", label: "DC Core Switch", type: "switch" });
  }

  if (data.load_balancer) {
    devices.push({ name: "LoadBalancer", label: "Load Balancer", type: "loadbalancer" });
  }

  return devices;
}

export default function StepConfigScripts({ data }) {
  const [configs, setConfigs] = useState({});
  const [generating, setGenerating] = useState(false);
  const [expanded, setExpanded] = useState({});
  const [generated, setGenerated] = useState(false);

  const devices = buildDeviceList(data);

  const handleGenerate = async () => {
    setGenerating(true);
    const result = {};
    // Build a minimal ipAllocs map (wizard doesn't have per-link IPs, use defaults)
    const ipAllocs = {};
    devices.forEach((device, i) => {
      ipAllocs[device.name] = {
        loopback: `1.1.1.${i + 1}/32`,
        wan: `10.0.${i}.1/30`,
        lan: `10.${i + 1}.0.1/24`,
        inside: `10.${i + 1}.0.1/24`,
        outside: `10.0.${i}.2/30`,
        mgmt: `10.${i + 1}.0.10/24`,
        dmz: `10.${i + 1}.254.1/24`,
      };
    });

    for (const device of devices) {
      const vendor = detectVendor(device, data);
      const config = generateDeviceConfig(device, data, ipAllocs, []);
      result[device.name] = { vendor, config };
    }

    // Optionally enhance with LLM for complex scenarios
    if (data.wan_technology === "SD-WAN" || data.topology_type === "full-mesh") {
      try {
        const llmResult = await base44.integrations.Core.InvokeLLM({
          prompt: `Generate additional notes or advanced config snippets for a ${data.topology_type} network using ${data.wan_technology} WAN technology with ${data.routing_protocol} routing. Keep it brief, CLI-format only, no explanations.`,
          response_json_schema: {
            type: "object",
            properties: { notes: { type: "string" } }
          }
        });
        if (llmResult?.notes) {
          for (const key of Object.keys(result)) {
            result[key].config += `\n! === Advanced Notes (${data.wan_technology}) ===\n${llmResult.notes}\n`;
          }
        }
      } catch (_) { /* skip if LLM fails */ }
    }

    setConfigs(result);
    setGenerated(true);
    setGenerating(false);
    if (devices.length > 0) setExpanded({ [devices[0].name]: true });
  };

  const handleDownload = (deviceName, config, vendor) => {
    const extMap = { juniper: "conf", paloalto: "set", server: "sh" };
    const ext = extMap[vendor] || "cfg";
    const blob = new Blob([config], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${deviceName}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadAll = () => {
    devices.forEach((d) => {
      if (configs[d.name]) {
        const { config, vendor } = configs[d.name];
        handleDownload(d.name, config, vendor);
      }
    });
  };

  const vendorColor = (v) => {
    if (v === "juniper") return "bg-red-900/30 text-red-300 border-red-800";
    if (v === "fortinet") return "bg-orange-900/30 text-orange-300 border-orange-800";
    if (v === "paloalto") return "bg-yellow-900/30 text-yellow-300 border-yellow-800";
    if (v === "arista") return "bg-green-900/30 text-green-300 border-green-800";
    return "bg-blue-900/30 text-blue-300 border-blue-800";
  };
  const vendorLabel = (v) => {
    if (v === "juniper") return "Juniper JunOS ✦ Hardened";
    if (v === "fortinet") return "FortiGate FortiOS ✦ Hardened";
    if (v === "paloalto") return "Palo Alto PAN-OS ✦ Hardened";
    if (v === "arista") return "Arista EOS ✦ Hardened";
    return "Cisco IOS ✦ Hardened";
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-foreground">Topology Preview & Config Scripts</h2>
        <p className="text-sm text-muted-foreground mt-1">
          Review and adjust your topology, then generate CLI configs for {devices.length} device{devices.length !== 1 ? "s" : ""}.
        </p>
      </div>

      <InteractiveTopology design={data} readOnly={false} />

      <div className="flex items-center gap-3">
        <Button
          onClick={handleGenerate}
          disabled={generating}
          className="gap-2 bg-primary text-primary-foreground hover:bg-primary/90"
        >
          {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Terminal className="h-4 w-4" />}
          {generated ? "Regenerate" : "Generate All Configs"}
        </Button>
        {generated && (
          <Button variant="outline" onClick={handleDownloadAll} className="gap-2">
            <Download className="h-4 w-4" /> Download All
          </Button>
        )}
      </div>

      {generated && (
        <div className="space-y-2">
          {devices.map((device) => {
            const entry = configs[device.name];
            if (!entry) return null;
            const isOpen = expanded[device.name];
            return (
              <div key={device.name} className="border border-border rounded-xl overflow-hidden">
                <button
                  className="w-full flex items-center justify-between px-4 py-3 bg-secondary hover:bg-secondary/80 transition-colors text-left"
                  onClick={() => setExpanded((prev) => ({ ...prev, [device.name]: !prev[device.name] }))}
                >
                  <div className="flex items-center gap-3">
                    {isOpen ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
                    <span className="text-sm font-medium text-foreground">{device.label}</span>
                    <Badge variant="outline" className={`text-xs ${vendorColor(entry.vendor)}`}>
                      {vendorLabel(entry.vendor)}
                    </Badge>
                  </div>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="gap-1 text-xs h-7"
                    onClick={(e) => { e.stopPropagation(); handleDownload(device.name, entry.config, entry.vendor); }}
                  >
                    <Download className="h-3 w-3" /> Download
                  </Button>
                </button>
                {isOpen && (
                  <pre className="bg-card text-xs text-green-400 font-mono p-4 overflow-x-auto max-h-72 overflow-y-auto whitespace-pre leading-5">
                    {entry.config}
                  </pre>
                )}
              </div>
            );
          })}
        </div>
      )}

      {!generated && (
        <div className="border border-dashed border-border rounded-xl p-8 text-center">
          <Terminal className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
          <p className="text-sm text-muted-foreground">Click "Generate All Configs" to produce CLI scripts for each device.</p>
          <p className="text-xs text-muted-foreground mt-1">Vendor is auto-detected from your device selections.</p>
        </div>
      )}
    </div>
  );
}