
import React,{useEffect,useState,useRef} from "react";
import {base44} from "@/api/base44Client";
import SimulationPanel from "./SimulationPanel";
import IRPlanReport from "./IRPlanReport";
const roles=["CEO","CISO","CIO","CFO","COO","Legal","Communications"];
const defaults=[["leadership","Executive Leadership",["CEO","CFO","COO"]],["security","Security",["CISO"]],["it","IT Operations",["CIO"]],["legal","Legal & Compliance",["Legal"]],["comms","Communications",["Communications"]]].map(([id,name,roles])=>({id,name,roles,responsibilities:"",approval_required:false}));
const categories={preparation_governance:"Preparation & Governance",detection_analysis:"Detection & Analysis",escalation_command:"Escalation & Command",containment:"Containment",eradication_remediation:"Eradication & Remediation",recovery_restoration:"Recovery & Restoration",communications:"Communications",legal_evidence:"Legal, Compliance & Evidence",lessons_improvement:"Lessons & Improvement"};
const input="w-full rounded-lg border border-slate-600 bg-slate-950 p-2.5 text-sm text-slate-100";
const button="rounded-lg border border-cyan-700 bg-cyan-950 px-4 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-900 disabled:opacity-40";
function Card({title,children}){return <section className="rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="mb-4 text-lg font-bold text-white">{title}</h2>{children}</section>}
function Field({label,children}){return <label className="block space-y-1 text-sm text-slate-300"><span>{label}</span>{children}</label>}
const link=(config,session,department)=>"/TabletopExercises?mode=distributed&config="+encodeURIComponent(config)+(session?"&session="+encodeURIComponent(session):"")+(department?"&department="+encodeURIComponent(department):"");
export default function DistributedCommand(){
 const initial=new URLSearchParams(window.location.search);
 const [boot,setBoot]=useState(null),[configId,setConfigId]=useState(initial.get("config")||""),[sessionId,setSessionId]=useState(initial.get("session")||""),[view,setView]=useState(null);
 const [workspace,setWorkspace]=useState(null),[draft,setDraft]=useState(null),[sessions,setSessions]=useState([]),[tab,setTab]=useState(initial.get("session")?"exercise":"dashboard");
 const [error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[stage,setStage]=useState("");
 const [newOrg,setNewOrg]=useState(initial.get("organization")||""),[newProfile,setNewProfile]=useState(""),[choice,setChoice]=useState(""),[handoff,setHandoff]=useState({action:"",impact:"",unresolved:""});
 const [note,setNote]=useState(""),[toDept,setToDept]=useState(""),[reassign,setReassign]=useState(""),[represent,setRepresent]=useState(false);
 const [setup,setSetup]=useState({attack_category:"Ransomware",attack_scenario:"Data encryption and extortion",disaster_type:"Regional power outage",response_minutes:30,training_mode:"practice",entry_node:"",disaster_target:"",department_ids:[],member_ids:[]});
 const generating=useRef(false),currentSession=useRef(sessionId);
 currentSession.current=sessionId;
 const api=async(action,payload={})=>{const res=await base44.functions.invoke("ttx-command",{action,config_id:configId,session_id:sessionId,...payload});return res.data;};
 const problem=e=>setError((e.response?.data?.error||e.message||"Request failed.")+(e.response?.data?.request_id?" Reference: "+e.response.data.request_id:""));
 const act=async(fn)=>{if(busy)return;setBusy(true);setError("");setNotice("");try{await fn();}catch(e){problem(e);}finally{setBusy(false);setStage("");}};
 const bootstrap=async()=>{const data=await api("bootstrap");setBoot(data);return data;};
 useEffect(()=>{bootstrap().catch(problem);},[]);
 const loadConfig=async()=>{if(!configId)return;const w=await api("config");setWorkspace(w);setDraft(structuredClone(w.config));const n=w.profile.network_model?.nodes||[];setSetup(s=>({...s,department_ids:w.config.departments.map(d=>d.id),member_ids:(w.config.members||[]).filter(m=>m.active!==false).map(m=>m.user_id),entry_node:n[0]?.id||"",disaster_target:n.find(n=>n.id==="backup")?.id||n[0]?.id||""}));setSessions((await api("sessions")).sessions);};
 useEffect(()=>{setWorkspace(null);setDraft(null);setView(null);if(configId)loadConfig().catch(problem);},[configId]);
 const refresh=async()=>{const id=sessionId;if(!id)return;const v=await api("view");if(currentSession.current===id)setView(v);return v;};
 useEffect(()=>{if(!sessionId)return;refresh().catch(problem);const timer=setInterval(()=>refresh().catch(problem),8000);return()=>clearInterval(timer);},[sessionId,configId]);
 useEffect(()=>{setChoice("");setHandoff({action:"",impact:"",unresolved:""});},[view?.current?.id]);
 // Any active workspace may advance the shared generation stage. The server canonicalizes concurrent retries.
 useEffect(()=>{if(!view?.needs_generation||!view.can_participate||view.paused||generating.current||busy)return;generating.current=true;setStage("Adapting the next decision and routing it to a department…");api("generate").then(refresh).catch(problem).finally(()=>{generating.current=false;setStage("");});},[view?.needs_generation,view?.timeline?.length,view?.paused,busy]);
 const openSession=id=>{setSessionId(id);setView(null);setTab("exercise");window.history.replaceState(null,"",link(configId,id));};
 const chooseConfig=id=>{setConfigId(id);setSessionId("");setTab("dashboard");window.history.replaceState(null,"",link(id));};
 const updateDept=(id,changes)=>setDraft(d=>({...d,departments:d.departments.map(x=>x.id===id?{...x,...changes}:x)}));
 const updateMember=(id,changes)=>setDraft(d=>({...d,members:d.members.map(x=>x.user_id===id?{...x,...changes}:x)}));
 const nodes=[...(workspace?.profile?.network_model?.nodes||[]),...(draft?.technical_context?.custom_nodes||[])];
 const updateAsset=(id,changes)=>setDraft(d=>({...d,technical_context:{...d.technical_context,assets:[...(d.technical_context?.assets||[]).filter(a=>a.node_id!==id),{...(d.technical_context?.assets||[]).find(a=>a.node_id===id),node_id:id,...changes}]}}));
 const save=()=>act(async()=>{await api("save_config",{...draft,config_id:configId});await loadConfig();setNotice("Organization teams and technical context saved. Existing exercises retain their original snapshots.");});
 const create=()=>act(async()=>{const x=await api("save_config",{organization_id:newOrg,profile_id:newProfile,departments:defaults,members:[],technical_context:{}});await bootstrap();chooseConfig(x.id);setTab("people");});
 const start=()=>act(async()=>{setStage("Validating the roster, permissions, and company snapshot…");const x=await api("start",setup);openSession(x.session_id);});
 const command=(action,extra={})=>act(async()=>{await api(action,{question_id:view?.current?.id,...extra});await refresh();});
 const toggle=(key,id)=>setSetup(s=>({...s,[key]:s[key].includes(id)?s[key].filter(x=>x!==id):[...s[key],id]}));
 const selected=boot?.configs.find(c=>c.id===configId),fac=workspace?.can_facilitate;
 const myDept=view?.my_department;
 const departmentName=id=>view?.session.departments.find(d=>d.id===id)?.name||draft?.departments.find(d=>d.id===id)?.name||id;
 if(!boot)return <div className="bg-slate-950 p-8 text-slate-200">{error||"Loading your authorized organizations…"}</div>;
 return <main className="min-h-screen bg-slate-950 p-4 text-slate-100 md:p-6">
 <header className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">Xtreme I.C.E. · Distributed Command TTX</p><h1 className="mt-2 text-3xl font-bold">One incident. Every department.</h1><p className="mt-2 max-w-3xl text-slate-300">A shared cyber crisis with department decisions, accountable handoffs, and adaptive consequences. Exercise outcomes are independent of CFRS.</p></div><a className={button} href="/AdminPanel">User Management</a></header>
 {error&&<div role="alert" className="mb-4 rounded-xl border border-rose-500 bg-rose-950 p-4">{error}<button className="ml-4 underline" onClick={()=>setError("")}>Dismiss</button></div>}
 {notice&&<p role="status" className="mb-4 rounded-xl border border-emerald-700 p-4">{notice}</p>}
 {stage&&<div role="status" className="mb-4 rounded-xl border border-cyan-700 p-4"><p>{stage}</p><progress aria-label={stage} className="mt-3 w-full accent-cyan-400"/><p className="text-xs text-slate-400">Progress is shown by completed stages; no estimated percentage is fabricated.</p></div>}
 <div className="mb-5 flex flex-wrap items-end gap-4"><Field label="Organization workspace"><select className={input} value={configId} onChange={e=>chooseConfig(e.target.value)}><option value="">Select an organization</option>{boot.configs.map(c=><option key={c.id} value={c.id}>{boot.organizations.find(o=>o.id===c.organization_id)?.name||c.organization_id} · {boot.profiles.find(p=>p.id===c.profile_id)?.company_name||"TTX"}</option>)}</select></Field>
 {configId&&<nav className="flex flex-wrap gap-2">{["dashboard",...(selected?.can_manage?["people","design"]:[]),...(selected?.can_facilitate?["setup"]:[]),"history",...(sessionId?["exercise"]:[])].map(t=><button key={t} className={button+(tab===t?" ring-2 ring-cyan-400":"")} onClick={()=>{setTab(t);if(t==="history"||t==="dashboard")api("sessions").then(d=>setSessions(d.sessions)).catch(problem);}}>{({people:"People & departments",design:"Technical design",setup:"New exercise",dashboard:"Dashboard",history:"History",exercise:"Exercise"})[t]}</button>)}</nav>}</div>
 {!configId&&<Card title="Connect an organization and company profile"><p className="mb-4 text-slate-300">Use your existing organization and a saved TTX company profile. Invite accounts in User Management, then assign their department and exercise responsibilities here.</p>{(boot.user.role==="admin"||boot.user.org_role==="org_admin")?<div className="grid gap-4 md:grid-cols-3"><Field label="Existing organization"><select className={input} value={newOrg} onChange={e=>setNewOrg(e.target.value)}><option value="">Choose organization</option>{boot.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Saved company profile"><select className={input} value={newProfile} onChange={e=>setNewProfile(e.target.value)}><option value="">Choose profile</option>{boot.profiles.filter(p=>!p.organization_id||p.organization_id===newOrg).map(p=><option key={p.id} value={p.id}>{p.company_name}</option>)}</select></Field><button className={button} disabled={busy||!newOrg||!newProfile} onClick={create}>Create command workspace</button><a href="/TabletopExercises" className="text-cyan-300 underline">Create a company profile in Integrated Readiness</a></div>:<p>Your administrator must assign you to an organization workspace and grant TTX access.</p>}</Card>}
 {configId&&!workspace&&<p>Loading organization workspace…</p>}
 {workspace&&["dashboard","history"].includes(tab)&&<><div className="mb-5 grid gap-4 md:grid-cols-3">{[["Completed exercises",sessions.filter(s=>s.status==="completed").length],["Active exercises",sessions.filter(s=>s.status!=="completed").length],["Average readiness",(()=>{const xs=sessions.filter(s=>Number.isFinite(s.score));return xs.length?Math.round(xs.reduce((a,s)=>a+s.score,0)/xs.length)+"/100":"Not assessed";})()]].map(([label,value])=><Card key={label} title={label}><p className="text-3xl font-bold text-cyan-300">{value}</p></Card>)}</div><Card title={tab==="history"?"Exercise history":"Organization readiness and recent exercises"}><p className="mb-4 text-sm text-slate-400">Only exercises assigned to this organization and your access scope appear. Historical results retain their original scoring version.</p><div className="space-y-3">{sessions.map(s=><button key={s.id} className="flex w-full items-center justify-between rounded-lg border border-slate-700 p-4 text-left hover:border-cyan-400" onClick={()=>openSession(s.id)}><span><b>{s.title}</b><span className="block text-sm text-slate-400">{new Date(s.created_date).toLocaleString()} · {s.status} · {s.decisions} decisions</span>{Number.isFinite(s.score)&&<span className="mt-2 block h-2 w-48 rounded bg-slate-800"><span className="block h-2 rounded bg-cyan-400" style={{width:s.score+"%"}}/></span>}</span><b className="text-2xl text-cyan-300">{s.score??"—"}</b></button>)}{!sessions.length&&<p>No exercises in this workspace yet.</p>}</div></Card></>}
 {workspace&&draft&&tab==="people"&&<div className="space-y-5"><Card title="Departments and decision authority"><p className="mb-4 text-slate-300">Map responsibility roles to your own departments. Approval-required departments need a separate approver in the exercise roster.</p>{draft.departments.map(d=><div key={d.id} className="mb-4 rounded-lg border border-slate-700 p-4"><div className="grid gap-3 md:grid-cols-2"><Field label="Department name"><input className={input} value={d.name} onChange={e=>updateDept(d.id,{name:e.target.value})}/></Field><Field label="Responsibilities"><input className={input} value={d.responsibilities} onChange={e=>updateDept(d.id,{responsibilities:e.target.value})}/></Field></div><div className="my-3 flex flex-wrap gap-4">{roles.map(role=><label key={role}><input type="checkbox" checked={d.roles.includes(role)} onChange={()=>updateDept(d.id,{roles:d.roles.includes(role)?d.roles.filter(r=>r!==role):[...d.roles,role]})}/> {role}</label>)}</div><label><input type="checkbox" checked={d.approval_required} onChange={e=>updateDept(d.id,{approval_required:e.target.checked})}/> Require approval before applying decisions</label><button className="ml-4 text-rose-300 underline" onClick={()=>setDraft(v=>({...v,departments:v.departments.filter(x=>x.id!==d.id)}))}>Remove department</button></div>)}<button className={button} onClick={()=>setDraft(v=>({...v,departments:[...v.departments,{id:crypto.randomUUID(),name:"New department",roles:[],responsibilities:"",approval_required:false}]}))}>Add department</button></Card>
 <Card title="People and application permissions"><p className="mb-4 text-slate-300">Accounts and invitations remain in User Management. Assign the TTX feature there before starting an exercise. Deactivate membership here to revoke this workspace without deleting historical actions.</p><Field label="Add an existing account"><select className={input} value="" onChange={e=>{const u=workspace.users.find(u=>u.id===e.target.value);if(u)setDraft(v=>({...v,members:[...v.members,{user_id:u.id,email:u.email,name:u.name,department_id:v.departments[0]?.id,access:"participant",responsibility:"decision_maker",active:true}]}));}}><option value="">Choose user</option>{workspace.users.filter(u=>!draft.members.some(m=>m.user_id===u.id)).map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></Field>
 <div className="mt-4 space-y-3">{draft.members.map(m=><div key={m.user_id} className="grid items-end gap-3 rounded-lg border border-slate-700 p-4 lg:grid-cols-5"><div><b>{m.name}</b><p className="break-all text-sm text-slate-400">{m.email}</p><p className="text-xs text-amber-200">{workspace.granted_emails.includes(m.email)||boot.user.email===m.email&&boot.user.role==="admin"?"TTX access assigned / admin":"Check TTX feature assignment"}</p></div><Field label="Department"><select className={input} value={m.department_id} onChange={e=>updateMember(m.user_id,{department_id:e.target.value})}>{draft.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Application access"><select className={input} value={m.access} onChange={e=>updateMember(m.user_id,{access:e.target.value})}>{["org_admin","facilitator","participant","observer"].map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Exercise responsibility"><select className={input} value={m.responsibility} onChange={e=>updateMember(m.user_id,{responsibility:e.target.value})}>{["decision_maker","approver","contributor","backup","observer"].map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Additional departments (optional)"><select multiple className={input} value={m.department_ids||[]} onChange={e=>updateMember(m.user_id,{department_ids:[...e.target.selectedOptions].map(o=>o.value)})}>{draft.departments.filter(d=>d.id!==m.department_id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><label><input type="checkbox" checked={m.active!==false} onChange={e=>updateMember(m.user_id,{active:e.target.checked})}/> Active</label></div>)}</div><button className={button+" mt-4"} disabled={busy} onClick={save}>Save people & departments</button></Card></div>}
 {workspace&&draft&&tab==="design"&&<Card title="Company-specific technical design"><p className="mb-4 text-slate-300">Describe representative systems and data classifications. These become scenario context, topology details, and ownership cues. Do not enter credentials or actual sensitive records.</p><Field label="Architecture and operational constraints"><textarea className={input} rows={3} value={draft.technical_context?.notes||""} onChange={e=>setDraft(d=>({...d,technical_context:{...d.technical_context,notes:e.target.value}}))}/></Field>
 <div className="mt-4 grid gap-4 xl:grid-cols-2">{nodes.map(n=>{const a=draft.technical_context?.assets?.find(a=>a.node_id===n.id)||{};return <div key={n.id} className="rounded-lg border border-slate-700 p-4"><h3 className="mb-3 font-bold text-cyan-200">{n.name}</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Owning department"><select className={input} value={a.department_id||""} onChange={e=>updateAsset(n.id,{department_id:e.target.value})}><option value="">Choose owner</option>{draft.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>{[["product","Product / platform"],["business_service","Business service"],["data_classification","Data classification"],["recovery_notes","Recovery dependencies and constraints"]].map(([key,label])=><Field key={key} label={label}><input className={input} value={a[key]||""} onChange={e=>updateAsset(n.id,{[key]:e.target.value})}/></Field>)}</div></div>;})}</div><div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={()=>{const name=window.prompt("Name of the additional simulated system");if(name?.trim())setDraft(d=>({...d,technical_context:{...d.technical_context,custom_nodes:[...(d.technical_context?.custom_nodes||[]),{id:"custom-"+crypto.randomUUID(),name:name.trim(),type:"server",quantity:1,unit_cost:0,monthly_unit_cost:0,impact_share:.1,dependencies:["core"]}]}}));}}>Add technical system</button><button className={button} disabled={busy} onClick={save}>Save technical design</button></div><p className="mt-3 text-sm text-slate-400">Additional systems start with zero assumed cost. Set their cost and dependency assumptions below before saving.</p>{(draft.technical_context?.custom_nodes||[]).map(n=><div key={n.id} className="mt-4 grid gap-3 rounded-lg border border-slate-700 p-3 md:grid-cols-4"><b>{n.name}</b>{["quantity","unit_cost","monthly_unit_cost","impact_share"].map(k=><Field key={k} label={k.replaceAll("_"," ")}><input type="number" min="0" step="any" className={input} value={n[k]} onChange={e=>setDraft(d=>({...d,technical_context:{...d.technical_context,custom_nodes:d.technical_context.custom_nodes.map(x=>x.id===n.id?{...x,[k]:Number(e.target.value)}:x)}}))}/></Field>)}<Field label="Depends on"><select multiple className={input} value={n.dependencies} onChange={e=>setDraft(d=>({...d,technical_context:{...d.technical_context,custom_nodes:d.technical_context.custom_nodes.map(x=>x.id===n.id?{...x,dependencies:[...e.target.selectedOptions].map(o=>o.value)}:x)}}))}>{nodes.filter(x=>x.id!==n.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><button className="text-rose-300 underline" onClick={()=>setDraft(d=>({...d,technical_context:{...d.technical_context,custom_nodes:d.technical_context.custom_nodes.filter(x=>x.id!==n.id)}}))}>Remove system</button></div>)}</Card>}
 {workspace&&draft&&tab==="setup"&&fac&&<Card title="Configure a Distributed Command exercise"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["attack_category","Attack category"],["attack_scenario","Attack scenario"],["disaster_type","Recovery disruption factor"]].map(([k,l])=><Field key={k} label={l}><input className={input} value={setup[k]} onChange={e=>setSetup(s=>({...s,[k]:e.target.value}))}/></Field>)}<Field label="Response target (minutes per task)"><input className={input} type="number" min="1" max="240" value={setup.response_minutes} onChange={e=>setSetup(s=>({...s,response_minutes:Number(e.target.value)}))}/></Field><Field label="Training mode"><select className={input} value={setup.training_mode} onChange={e=>setSetup(s=>({...s,training_mode:e.target.value}))}><option value="practice">Practice</option><option value="assessment">Assessment</option></select></Field>{[["entry_node","Attack entry system"],["disaster_target","Recovery disruption target"]].map(([k,l])=><Field key={k} label={l}><select className={input} value={setup[k]} onChange={e=>setSetup(s=>({...s,[k]:e.target.value}))}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Field>)}</div><p className="mt-4 text-slate-300">Region: {workspace.profile.headquarters||workspace.profile.primary_geography}. The selected disaster complicates the cyber incident.</p><h3 className="mt-5 font-bold">Participating departments</h3><div className="my-3 flex flex-wrap gap-4">{draft.departments.map(d=><label key={d.id}><input type="checkbox" checked={setup.department_ids.includes(d.id)} onChange={()=>toggle("department_ids",d.id)}/> {d.name}</label>)}</div><h3 className="font-bold">Exercise roster</h3><div className="my-3 grid gap-3 md:grid-cols-2">{draft.members.filter(m=>m.active!==false).map(m=><label key={m.user_id} className="rounded-lg border border-slate-700 p-3"><input type="checkbox" checked={setup.member_ids.includes(m.user_id)} onChange={()=>toggle("member_ids",m.user_id)}/> {m.name} · {departmentName(m.department_id)} · {m.responsibility}</label>)}</div><p className="mb-4 text-sm text-slate-400">Each department needs a decision-maker or backup; approval-required departments also need an approver. All seven executive responsibility roles must be covered. The saved roster and technical design are frozen for this attempt.</p><button className={button} disabled={busy} onClick={start}>Validate roster & start exercise</button></Card>}
 {tab==="exercise"&&sessionId&&!view&&<p>Loading the shared incident record…</p>}
 {tab==="exercise"&&view&&<><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">{view.session.title}</h2><span className="rounded-full border border-cyan-700 px-4 py-2">{view.completed?"Completed":view.paused?"Paused":view.pending_department?"Awaiting "+departmentName(view.pending_department):"Preparing next decision"}</span></div>
 {view.can_facilitate&&<Card title="Facilitator controls"><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||view.completed} onClick={()=>command(view.paused?"resume":"pause",{reason:"Facilitator control"})}>{view.paused?"Resume":"Pause"}</button><button className={button} disabled={busy||!view.needs_generation||view.paused} onClick={()=>command("generate")}>Retry / generate next decision</button>{view.ready_to_complete&&!view.completed&&<button className={button} disabled={busy} onClick={()=>command("complete")}>Complete & save briefing</button>}{view.completed&&!view.released&&<button className={button} disabled={busy} onClick={()=>command("release")}>Release department results</button>}<button className={button} onClick={()=>window.print()}>Print / save briefing as PDF</button></div><details className="mt-4"><summary className="cursor-pointer">Department links and task reassignment</summary><div className="mt-3 space-y-2">{view.session.departments.map(d=><div key={d.id} className="flex flex-wrap gap-3"><b>{d.name}</b><a className="break-all text-cyan-300 underline" href={link(configId,sessionId,d.id)}>{window.location.origin+link(configId,sessionId,d.id)}</a></div>)}</div><p className="my-3 text-sm text-slate-400">Links require individual login and assigned access. A link never grants membership.</p>{view.current&&<div className="flex flex-wrap gap-3"><select className={input+" max-w-xs"} value={reassign} onChange={e=>setReassign(e.target.value)}><option value="">Choose department</option>{view.session.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><label><input type="checkbox" checked={represent} onChange={e=>setRepresent(e.target.checked)}/> I will represent this department</label><button className={button} disabled={busy||!reassign} onClick={()=>command("reassign",{department_id:reassign,represent,reason:"Facilitator reassigned responsibility"})}>Record reassignment</button></div>}</details></Card>}
 <div className="mt-5 grid items-start gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(380px,0.75fr)]"><div className="space-y-5">
 {view.current&&!view.completed&&<Card title={categories[view.current.phase]}><p className="mb-2 text-sm text-cyan-200">{departmentName(view.current.department_id)} · {view.current.decision_owner} · {view.current.requires_approval?"Approval required":"Department decision authority"}</p><p className="mb-2 text-sm text-slate-400">{view.current.routing_reason}</p><p className="mb-4 text-sm text-amber-200">Response target: {view.session.settings.response_minutes} active minutes from assignment. {view.paused?"Timer paused.":Date.now()>Date.parse(view.current.due_at)?"Check elapsed time; backup or facilitator reassignment is available.":"Assigned "+new Date(view.current.created_date).toLocaleTimeString()+"."}</p><p className="whitespace-pre-wrap leading-7">{view.current.situation}</p><h3 className="my-4 text-xl font-bold">{view.current.question}</h3>{view.can_contribute||view.can_facilitate?<button className={button+" mb-4"} disabled={busy||view.paused} onClick={()=>command("ack")}>Acknowledge handoff</button>:null}
 {(view.can_decide&&!view.paused)&&<><div className="space-y-3">{view.current.choices.map(c=><label key={c.id} className={"block cursor-pointer rounded-lg border p-4 "+(choice===c.id?"border-cyan-400 bg-cyan-950":"border-slate-600")}><input type="radio" name="decision" checked={choice===c.id} onChange={()=>setChoice(c.id)}/> {c.label}</label>)}</div><div className="mt-4 space-y-3">{[["action","Action and handoff instructions"],["impact","Business impact and dependencies"],["unresolved","Unresolved issues / information needed"]].map(([k,l])=><Field key={k} label={l}><textarea className={input} value={handoff[k]} onChange={e=>setHandoff(h=>({...h,[k]:e.target.value}))}/></Field>)}</div><button className={button+" mt-4"} disabled={busy||!choice} onClick={()=>command("answer",{choice_id:choice,handoff})}>{view.current.requires_approval?"Submit for approval":"Submit decision & route next task"}</button></>}
 {view.proposal&&<div className="mt-4 rounded-xl border border-amber-600 p-4"><b>Decision awaiting approval</b><p>{view.current.choices.find(c=>c.id===view.proposal.payload.choice_id)?.label}</p><p className="mt-2">{view.proposal.payload.handoff.action}</p><p>{view.proposal.payload.handoff.impact}</p><p>{view.proposal.payload.handoff.unresolved}</p>{view.can_approve&&<button className={button+" mt-3"} disabled={busy||view.paused} onClick={()=>command("approve",{proposal_id:view.proposal.id})}>Approve & apply decision</button>}</div>}
 {!view.can_decide&&!view.can_approve&&<p className="mt-3 text-slate-400">The assigned decision-maker will submit the department response.</p>}
 {(view.can_contribute||view.can_facilitate)&&<div className="mt-5 flex gap-3"><input className={input} value={note} onChange={e=>setNote(e.target.value)} placeholder="Supporting observation or clarification"/><button className={button} disabled={busy||!note||view.paused} onClick={()=>command("comment",{message:note})}>Add note</button></div>}</Card>}
 {!view.current&&!view.completed&&<Card title="Department workspace"><p>{view.ready_to_complete?"All response categories are complete. The facilitator can resolve remaining requests and save the briefing.":view.needs_generation?"The next decision is being prepared.":"The current decision belongs to "+departmentName(view.pending_department)+". Review the timeline or respond to an information request."}</p>{view.needs_generation&&<button className={button+" mt-3"} disabled={busy||view.paused} onClick={()=>command("generate")}>Retry next decision</button>}</Card>}
 <Card title="Incident timeline and department handoffs"><div className="space-y-4">{view.timeline.map(d=><article key={d.sequence} className="border-l-2 border-cyan-600 pl-4"><p className="text-sm text-cyan-200">Decision {d.sequence} · {departmentName(d.department_id)} · {new Date(d.selected_at).toLocaleString()}</p><h3 className="mt-1 font-bold">{d.choice_label}</h3><p className="mt-2"><b>Action:</b> {d.handoff.action}</p><p><b>Business impact:</b> {d.handoff.impact}</p><p><b>Unresolved:</b> {d.handoff.unresolved}</p><p className="mt-1 text-xs text-slate-400">Submitted by {d.actor}{d.approved_by?" · Approved by "+d.approved_by:""}</p></article>)}{!view.timeline.length&&<p>The incident begins with the first department decision.</p>}</div></Card>
 <Card title="Parallel information and action requests">{!view.completed&&view.can_participate&&<div className="mb-4 flex flex-wrap gap-3"><select className={input+" max-w-xs"} value={toDept} onChange={e=>setToDept(e.target.value)}><option value="">Request from department</option>{view.session.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input className={input} value={note} onChange={e=>setNote(e.target.value)} placeholder="What information or action is needed?"/><button className={button} disabled={busy||!toDept||!note||view.paused} onClick={()=>command("request",{to_department:toDept,message:note})}>Send in-app request</button></div>}<div className="space-y-3">{view.requests.map(r=><div key={r.id} className="rounded-lg border border-slate-700 p-3"><b>{departmentName(r.payload.from_department)} → {departmentName(r.payload.to_department)}</b><p>{r.payload.message}</p>{r.reply?<p className="mt-2 text-emerald-200">{r.reply.kind==="waive"?"Waived":"Response"}: {r.reply.payload.message}</p>:!view.completed&&(view.can_facilitate||view.my_departments?.includes(r.payload.to_department))?<div className="mt-2 flex gap-2"><button className={button} disabled={busy||view.paused} onClick={()=>{const message=window.prompt("Response to this request");if(message)command("reply",{request_id:r.id,message});}}>Respond</button>{view.can_facilitate&&<button className={button} disabled={busy||view.paused} onClick={()=>{const message=window.prompt("Reason for waiving this request");if(message)command("waive",{request_id:r.id,message});}}>Waive with reason</button>}</div>:<p className="text-amber-300">Awaiting response</p>}</div>)}</div></Card>
 </div><aside className="space-y-4 xl:sticky xl:top-4"><SimulationPanel network={view.network} state={view.state} compact/><Card title="Activity record"><div className="max-h-80 space-y-2 overflow-auto">{view.activity.map(e=><p key={e.id} className="border-b border-slate-800 pb-2 text-sm"><b>{e.kind}</b> · {e.actor}<br/>{e.payload.message||e.payload.reason}</p>)}</div></Card></aside></div>
 {view.completed&&!view.result&&<Card title="Exercise completed"><p>Your facilitator is reviewing the after-action briefing. Department results will appear when released.</p></Card>}
 {view.result&&<div className="mt-5 space-y-5"><Card title="Executive readiness briefing"><div className="mb-4 flex justify-between"><b>{view.session.company}</b><b className="text-3xl text-cyan-300">{view.result.overall_score}/100</b></div><p className="whitespace-pre-wrap leading-7">{view.result.end_state_overview}</p><p className="mt-4 text-xs text-slate-400">{view.result.scoring_version}. Effectiveness uses the existing response-category weights. Handoff completeness (required fields provided), acknowledgment, and response-target measures are reported separately and do not change that score.</p></Card>
 <Card title="Incident-response category scores"><div className="grid gap-4 md:grid-cols-3">{Object.entries(view.result.category_scores).map(([k,v])=><div key={k}><p>{categories[k]} · {v??"Not assessed"}</p><div className="my-2 h-2 rounded bg-slate-800"><div className="h-2 rounded bg-cyan-400" style={{width:(v||0)+"%"}}/></div>{view.result.category_narratives[k]&&<details><summary className="cursor-pointer text-sm text-cyan-200">Why this score</summary><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{view.result.category_narratives[k]}</p></details>}</div>)}</div></Card>
 <Card title="Department performance"><div className="grid gap-4 lg:grid-cols-2">{Object.entries(view.result.department_scores).map(([id,d])=><div key={id} className="rounded-lg border border-slate-700 p-4"><h3 className="font-bold text-cyan-200">{d.name} · {d.score==null?"Not assessed":d.score+"/100"}</h3><p className="my-2 text-sm">Decisions: {d.count} · Handoff completeness: {d.handoff??"—"} · Acknowledgment: {d.coordination??"—"} · Timeliness: {d.timeliness??"—"}</p><p className="whitespace-pre-wrap text-sm leading-6 text-slate-300">{d.narrative}</p></div>)}</div></Card>
 {!!Object.keys(view.result.role_scores).length&&<Card title="Role and responsibility"><div className="grid gap-4 md:grid-cols-2">{Object.entries(view.result.role_scores).map(([role,r])=><details key={role} className="rounded border border-slate-700 p-3"><summary>{role} · {r.score??"Not assessed"}</summary><p className="mt-3 text-sm leading-6">{r.narrative}</p></details>)}</div></Card>}
 {view.ir_plan&&<IRPlanReport exercise={{ir_plan_snapshot:view.ir_plan,training_mode:view.session.settings.training_mode}} result={view.result}/>}
 </div>}
 </>}
 </main>;
}
