import React,{useState} from "react";
import InfrastructureDeviceIcon from "@/components/lab/InfrastructureDeviceIcon";
import {environmentCost,money,ROLES} from "./simulation";
const colors={healthy:"#34d399",compromised:"#fb7185",isolated:"#fbbf24",recovering:"#a78bfa",suspicious:"#fb923c",disrupted:"#94a3b8"};
const positions={edge:[80,45],core:[240,45],identity:[400,45],endpoints:[80,155],cloud:[240,155],business:[400,155],data:[400,265],special:[80,265],backup:[240,265],soc:[240,375]};
export default function SimulationPanel({network,state,compact=false}){
 const [selected,setSelected]=useState(null);
 if(!network?.nodes)return null;
 const costs=environmentCost(network),node=network.nodes.find(n=>n.id===selected);
 return <section className="mb-6 rounded-2xl border border-slate-700 bg-slate-900 p-5">
 <h3 className="text-xl font-bold text-white">Company network · {network.industry} · {network.size}</h3>
 <p className="mt-1 text-sm text-slate-300">Simulated environment. Select a device group for details. Lines represent modeled dependencies, not discovered connections.</p>
 <div className="mt-3 overflow-x-auto"><svg className="mx-auto block w-full min-w-[430px] max-w-[660px]" viewBox="0 0 480 440" role="group" aria-label="Interactive company network">
 {network.edges.map((e,i)=>{const a=positions[e.source],b=positions[e.target];return a&&b?<line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke={state?.statuses[e.source]==="compromised"?"#fb7185":"#475569"} strokeWidth="2"/>:null})}
 {network.nodes.map(n=>{const [x,y]=positions[n.id]||[400,375];const status=state?.statuses[n.id]||"healthy";return <foreignObject key={n.id} x={x-73} y={y-33} width="146" height="96"><button onClick={()=>setSelected(n.id)} style={{borderColor:colors[status]}} className="h-full w-full rounded-lg border-2 bg-slate-950 p-2 text-left text-sm text-white focus:ring-2 focus:ring-cyan-300"><InfrastructureDeviceIcon type={n.type} className="float-right h-5 w-5"/><span className="block font-semibold leading-tight">{n.name}</span><span style={{color:colors[status]}} className="mt-1 block text-xs">{status} · {n.quantity}</span>{state?.unavailable?.includes(n.id)&&status==="healthy"&&<span className="block text-xs text-amber-200">Dependency outage</span>}</button></foreignObject>})}
 </svg></div>
 <div className="flex flex-wrap gap-4 text-xs text-slate-200">{Object.entries(colors).map(([s,c])=><span key={s}><span style={{color:c}}>●</span> {s}</span>)}</div>
 {node&&<div role="dialog" aria-label="Device details" className="mt-4 rounded-xl border border-cyan-600 p-4 text-slate-200"><button className="float-right text-cyan-300" onClick={()=>setSelected(null)}>Close</button><b>{node.name}</b><p>{node.quantity} modeled devices / licenses. Dependencies: {node.dependencies.map(id=>network.nodes.find(n=>n.id===id)?.name).join(", ")||"None"}.</p><p>Equipment: {money(node.quantity*node.unit_cost)} · Monthly: {money(node.quantity*node.monthly_unit_cost)}</p></div>}
 <details open={!compact} className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-slate-200">Network budget and assumptions</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{[["Equipment estimate",costs.equipment],["Implementation estimate",costs.implementation],["Monthly operating estimate",costs.monthly]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-950 p-3"><p className="text-sm text-slate-300">{l}</p><b className="text-xl text-cyan-200">{money(v)}</b></div>)}</div>
 <p className="mt-3 text-xs text-slate-400">USD training assumptions, editable in the company profile; these are not vendor quotes or forecasts of actual losses. Infrastructure costs are separate from incident costs.</p></details>
 {state&&<><div className="mt-4 grid gap-3 grid-cols-2">{[["Simulated incident total",state.total],["Outage cost",state.downtime],["Response labor",state.response],["Additional exposure estimate",state.projected_remaining||0]].map(([l,v])=><div className="rounded-xl border border-amber-600/40 p-3" key={l}><p className="text-sm text-slate-300">{l}</p><b className="text-xl text-amber-200">{money(v)}</b></div>)}</div><p className="mt-2 text-sm text-slate-300">Elapsed: {state.hours} simulated hours. Additional exposure is an estimate and is not included in the incident total.</p>{state.timeline?.length>0&&<details className="mt-4 text-sm text-slate-200"><summary className="cursor-pointer font-bold">Decision and cost timeline</summary>{state.timeline.map(t=><p className="mt-2 border-t border-slate-700 pt-2" key={t.sequence}>Decision {t.sequence} · +{money(t.increment)} · Total {money(t.total)} — {t.summary}</p>)}</details>}</>}
 </section>;
}
const field="w-full rounded border border-slate-600 bg-slate-950 p-2 text-sm text-white";
export function NetworkEditor({network,onChange}){
 if(!network)return null;
 const changeNode=(id,key,value)=>onChange({...network,nodes:network.nodes.map(n=>n.id===id?{...n,[key]:Math.max(key==="quantity"?1:0,Number(value)||0)}:n)});
 return <div className="mt-6 space-y-5"><SimulationPanel network={network}/><details className="rounded-xl border border-slate-700 p-4"><summary className="cursor-pointer font-bold">Review network quantities and cost assumptions</summary><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Device group","Quantity","Unit equipment USD","Monthly per unit USD"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{network.nodes.map(n=><tr key={n.id}><td className="p-2">{n.name}</td>{["quantity","unit_cost","monthly_unit_cost"].map(k=><td className="p-2" key={k}><input aria-label={n.name+" "+k} className={field} type="number" min={k==="quantity"?1:0} value={n[k]} onChange={e=>changeNode(n.id,k,e.target.value)}/></td>)}</tr>)}</tbody></table></div><div className="mt-4 grid gap-3 md:grid-cols-3">{[["downtime_per_hour","Full outage cost per hour USD"],["response_hourly_rate","Response labor per hour USD"],["implementation_rate","Implementation fraction (0.2 = 20%)"]].map(([k,l])=><label className="text-sm" key={k}>{l}<input className={field} type="number" min="0" step="any" value={network.assumptions[k]} onChange={e=>onChange({...network,assumptions:{...network.assumptions,[k]:Math.max(0,Number(e.target.value)||0)}})}/></label>)}</div></details><details className="rounded-xl border border-slate-700 p-4"><summary className="cursor-pointer font-bold">Decision roles and company delegates</summary><p className="mt-2 text-sm text-slate-300">Small companies may assign several responsibilities to one person. Role scores reflect decisions owned by that role, not an employee performance assessment.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{ROLES.map(r=><label key={r} className="text-sm">{r}<input className={field} value={network.role_assignments[r]||r} onChange={e=>onChange({...network,role_assignments:{...network.role_assignments,[r]:e.target.value}})}/></label>)}</div></details></div>;
}