/**
 * Device configuration generators for multiple vendors.
 * Supports: Cisco IOS, Juniper JunOS, Palo Alto PAN-OS
 * Includes CIS/STIG-aligned security hardening best practices.
 */

export function parseBase(ipScheme) {
  const m = (ipScheme || "10.0.0.0/8").match(/(\d+)\.(\d+)\.(\d+)\.(\d+)/);
  return m ? [+m[1], +m[2], +m[3], +m[4]] : [10, 0, 0, 0];
}

// ── Detect vendor from design fields ─────────────────────────────────────────
export function detectVendor(device, design) {
  const fw = (design?.firewall_vendor || "").toLowerCase();
  const router = (design?.router_model || "").toLowerCase();
  const sw = (design?.switch_model || "").toLowerCase();

  if (device.type === "firewall") {
    if (fw.includes("palo alto")) return "paloalto";
    if (fw.includes("juniper") || fw.includes("srx")) return "juniper";
    if (fw.includes("fortinet") || fw.includes("fortigate")) return "fortinet";
    return "cisco"; // Cisco ASA / pfSense
  }
  if (device.type === "router") {
    if (router.includes("juniper") || router.includes("vmx")) return "juniper";
    return "cisco";
  }
  if (device.type === "switch") {
    if (sw.includes("juniper") || sw.includes("ex")) return "juniper";
    if (sw.includes("arista")) return "arista"; // EOS is Cisco-like, handled as cisco
    return "cisco";
  }
  return "cisco";
}

// ── Shared hardening comment block ────────────────────────────────────────────
function hardeningNote(vendor) {
  return `
! ┌─────────────────────────────────────────────────────────────┐
! │  SECURITY HARDENING APPLIED (CIS Benchmark / STIG aligned)  │
! │  Vendor: ${vendor.padEnd(51)}│
! │  Review all settings before deploying in production.        │
! │  ⚠️  WARNING: DEFAULT PASSWORDS ARE USED IN THIS CONFIG     │
! │  Change all credentials IMMEDIATELY before deployment       │
! └─────────────────────────────────────────────────────────────┘
`;
}

// ═══════════════════════════════════════════════════════════════
// CISCO IOS / ASA
// ═══════════════════════════════════════════════════════════════
function generateCiscoConfig(device, design, ips, links, b1, b2) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = design?.domain_name || "cyberexercise.local";
  const ntp = design?.ntp_server || "pool.ntp.org";
  const username = design?.device_username || "admin";
  const password = design?.device_password || "Change" + "Me2024!";
  const enable = design?.enable_password || "Enable" + "Me2024!";
  const myLinks = links.filter(l => l.from === device.name || l.to === device.name);

  let cfg = `! ==========================================
! ${device.label} — Cisco IOS Configuration
! Vendor: Cisco IOS / IOS-XE
! Cyber Exercise: ${design?.name || "Cyber Event"}
! Generated by Xtreme I.C.E. Network Designer
! ==========================================
${hardeningNote("Cisco IOS")}
! ⚠️  CRITICAL: These are DEFAULT EXERCISE PASSWORDS
! ⚠️  Username: ${username} | Enable Secret: ${enable}
! ⚠️  Change IMMEDIATELY — never use in production
!
hostname ${hostname}
ip domain-name ${domain}
!
! === PASSWORD & AUTH HARDENING ===
enable algorithm-type scrypt secret ${enable}
username ${username} privilege 15 algorithm-type scrypt secret ${password}
aaa new-model
aaa authentication login default local
aaa authentication enable default enable
aaa authorization exec default local
aaa accounting exec default start-stop group tacacs+
!
service password-encryption
security passwords min-length 12
login block-for 120 attempts 5 within 60
login on-failure log
login on-success log
!
! === DISABLE UNNECESSARY SERVICES ===
no service finger
no service udp-small-servers
no service tcp-small-servers
no ip http server
no ip http secure-server
no ip source-route
no ip bootp server
no ip domain-lookup
no cdp run
no ip proxy-arp
no service config
!
! === SSH HARDENING ===
crypto key generate rsa modulus 4096
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3
ip ssh maxstartups 4
ip ssh dh min size 4096
line vty 0 4
 login local
 transport input ssh
 exec-timeout 10 0
 session-timeout 10
 logging synchronous
!
! === CONSOLE HARDENING ===
line con 0
 exec-timeout 5 0
 login local
 logging synchronous
!
! === LOGGING & MONITORING ===
logging buffered 16384 informational
logging trap informational
logging host ${b1}.${b2}.200.11
service timestamps log datetime msec localtime show-timezone
service timestamps debug datetime msec localtime show-timezone
!
! === NTP & DNS ===
ntp server ${ntp} prefer
ntp update-calendar
ip name-server 8.8.8.8 8.8.4.4
!\n`;

  // ── ROUTER ──
  if (device.type === "router") {
    if (ips.loopback) {
      const lo = ips.loopback.split("/")[0];
      cfg += `interface Loopback0\n description Management Loopback\n ip address ${lo} 255.255.255.255\n no ip proxy-arp\n no shutdown\n!\n`;
    }
    if (ips.wan) {
      const [addr] = ips.wan.split("/");
      cfg += `interface GigabitEthernet0/0\n description WAN Link\n ip address ${addr} 255.255.255.252\n ip access-group ACL-WAN-IN in\n ip nat outside\n no ip proxy-arp\n no ip redirects\n no ip unreachables\n no ip directed-broadcast\n no shutdown\n!\n`;
    }
    if (ips.lan) {
      const [addr, prefix] = ips.lan.split("/");
      const mask = prefix === "24" ? "255.255.255.0" : "255.255.255.252";
      cfg += `interface GigabitEthernet0/1\n description LAN Link\n ip address ${addr} ${mask}\n ip nat inside\n no ip proxy-arp\n no ip redirects\n no ip unreachables\n no ip directed-broadcast\n no shutdown\n!\n`;
    }

    // ACL for WAN ingress
    cfg += `ip access-list extended ACL-WAN-IN\n remark Allow established TCP\n permit tcp any any established\n remark Allow ICMP echo-reply only\n permit icmp any any echo-reply\n permit icmp any any time-exceeded\n permit icmp any any unreachable\n remark Deny and log everything else\n deny   ip any any log\n!\n`;

    // OSPF
    const protocol = design?.routing_protocol || "OSPF";
    if (protocol === "OSPF" || !protocol || protocol === "Static") {
      cfg += `router ospf 1\n router-id ${ips.loopback?.split("/")[0] || "0.0.0.1"}\n auto-cost reference-bandwidth 10000\n passive-interface default\n no passive-interface GigabitEthernet0/0\n`;
      if (ips.lan) { const p = ips.lan.split("/")[0].split("."); p[3] = "0"; cfg += ` network ${p.join(".")} 0.0.0.255 area 0\n`; }
      if (ips.wan) { const p = ips.wan.split("/")[0].split("."); p[3] = "0"; cfg += ` network ${p.join(".")} 0.0.0.3 area 0\n`; }
      cfg += `!\n`;
    } else if (protocol === "EIGRP") {
      cfg += `router eigrp 100\n no auto-summary\n`;
      if (ips.lan) { const p = ips.lan.split("/")[0].split("."); p[3] = "0"; cfg += ` network ${p.join(".")} 0.0.0.255\n`; }
      cfg += `!\n`;
    } else if (protocol === "BGP") {
      cfg += `router bgp 65000\n bgp log-neighbor-changes\n bgp deterministic-med\n no bgp default ipv4-unicast\n!\n`;
    }

    // NAT
    cfg += `ip nat inside source list ACL-NAT interface GigabitEthernet0/0 overload\nip access-list standard ACL-NAT\n permit ${b1}.${b2}.0.0 0.0.255.255\n!\n`;

    // IPSec
    if (design?.wan_technology === "IPSec VPN") {
      cfg += `! === IPSec VPN (IKEv2) ===\ncrypto ikev2 proposal IKE-PROP\n encryption aes-cbc-256\n integrity sha512\n group 21\n!\ncrypto ikev2 policy IKE-POL\n proposal IKE-PROP\n!\ncrypto ipsec transform-set TS esp-aes 256 esp-sha512-hmac\n mode tunnel\n!\n`;
    }
    cfg += `ip route 0.0.0.0 0.0.0.0 GigabitEthernet0/0\n!\n`;
  }

  // ── SWITCH ──
  if (device.type === "switch") {
    cfg += `! === SWITCH HARDENING ===\nspanning-tree mode rapid-pvst\nspanning-tree portfast default\nspanning-tree portfast bpduguard default\nspanning-tree loopguard default\n!\n`;
    cfg += `! Disable unused protocols\nno ip routing\nno lldp run\n!\n`;
    const vlans = design?.vlan_names?.length ? design.vlan_names : ["Management", "Data", "Voice"];
    vlans.forEach((v, i) => { cfg += `vlan ${i + 10}\n name ${v.replace(/\s+/g, "_")}\n!\n`; });
    // Disable VLAN 1
    cfg += `interface Vlan1\n no ip address\n shutdown\n!\n`;
    if (ips.mgmt) {
      const [addr] = ips.mgmt.split("/");
      cfg += `interface Vlan10\n description Management\n ip address ${addr} 255.255.255.0\n no ip proxy-arp\n no shutdown\n!\n`;
    }
    cfg += `interface GigabitEthernet0/0\n description Uplink to Router\n switchport mode trunk\n switchport nonegotiate\n switchport trunk allowed vlan ${vlans.map((_, i) => i + 10).join(",")}\n no shutdown\n!\n`;
    for (let p = 1; p <= 4; p++) {
      cfg += `interface GigabitEthernet0/${p}\n description Access Port ${p}\n switchport mode access\n switchport access vlan 11\n switchport nonegotiate\n spanning-tree portfast\n spanning-tree bpduguard enable\n ip dhcp snooping limit rate 15\n storm-control broadcast level 20\n storm-control action shutdown\n no shutdown\n!\n`;
    }
    cfg += `ip dhcp snooping\nip dhcp snooping vlan 10-19\nip arp inspection vlan 10-19\n!\n`;
  }

  // ── FIREWALL (ASA style) ──
  if (device.type === "firewall") {
    const outside = ips.outside || "dhcp";
    const inside = ips.inside || "192.168.1.1";
    cfg += `! === ${design?.firewall_vendor || "Firewall"} — ASA-Style Policy ===\n`;
    cfg += `! === FIREWALL HARDENING ===\nno http server enable\nno ftp-server\nno snmp-server\nssh version 2\nssh timeout 5\nssh authentication-retries 3\n!\n`;
    cfg += `interface GigabitEthernet0/0\n nameif outside\n security-level 0\n ip address ${outside.split("/")[0]} 255.255.255.252\n no shutdown\n!\n`;
    cfg += `interface GigabitEthernet0/1\n nameif inside\n security-level 100\n ip address ${inside.split("/")[0]} 255.255.255.252\n no shutdown\n!\n`;
    if (design?.dmz_required && ips.dmz) {
      cfg += `interface GigabitEthernet0/2\n nameif dmz\n security-level 50\n ip address ${ips.dmz.split("/")[0]} 255.255.255.252\n no shutdown\n!\n`;
    }
    cfg += `! === ACCESS POLICY ===\naccess-list OUTSIDE-IN extended permit tcp any any established\naccess-list OUTSIDE-IN extended permit icmp any any echo-reply\naccess-list OUTSIDE-IN extended deny ip any any log\naccess-group OUTSIDE-IN in interface outside\n!\n`;
    if (design?.dmz_required) {
      cfg += `access-list DMZ-IN extended permit tcp any host ${b1}.${b2}.200.0 255.255.255.0 eq 80\naccess-list DMZ-IN extended permit tcp any host ${b1}.${b2}.200.0 255.255.255.0 eq 443\naccess-list DMZ-IN extended deny ip any any log\naccess-group DMZ-IN in interface dmz\n!\n`;
    }
    cfg += `nat (inside,outside) dynamic interface\n!\n`;
    cfg += `! === THREAT DETECTION ===\nthreat-detection basic-threat\nthreat-detection statistics\nthreat-detection statistics tcp-intercept\n!\nlogging enable\nlogging trap informational\nlogging host inside ${b1}.${b2}.200.11\n!\n`;
  }

  // ── SERVER ──
  if (device.type === "server") {
    const serverIp = ips.ip || "192.168.200.10";
    const gw = ips.gateway || "192.168.200.1";
    cfg = `# ==========================================
# ${device.label} — Linux Server Hardening Baseline
# Cyber Exercise: ${design?.name || "Cyber Event"}
# ==========================================
# IP Address : ${serverIp}
# Gateway    : ${gw}
# DNS        : 8.8.8.8, 8.8.4.4

# === NETWORK CONFIGURATION ===
ip addr add ${serverIp} dev eth0
ip route add default via ${gw}
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

# === SECURITY HARDENING ===
# Disable unused services
systemctl disable --now telnet rsh rlogin rcp ypserv tftp xinetd 2>/dev/null || true

# SSH hardening (/etc/ssh/sshd_config)
sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
echo "Protocol 2" >> /etc/ssh/sshd_config
echo "MaxAuthTries 3" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 300" >> /etc/ssh/sshd_config
echo "ClientAliveCountMax 2" >> /etc/ssh/sshd_config
systemctl restart sshd

# Password policy (/etc/security/pwquality.conf)
echo "minlen = 14" >> /etc/security/pwquality.conf
echo "dcredit = -1" >> /etc/security/pwquality.conf
echo "ucredit = -1" >> /etc/security/pwquality.conf
echo "ocredit = -1" >> /etc/security/pwquality.conf
echo "lcredit = -1" >> /etc/security/pwquality.conf

# Kernel hardening (/etc/sysctl.conf)
echo "net.ipv4.ip_forward = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.rp_filter = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.send_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.tcp_syncookies = 1" >> /etc/sysctl.conf
sysctl -p

# Firewall (UFW)
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw enable
`;
    return cfg;
  }

  // ── WIRELESS AP ──
  if (device.type === "wireless") {
    const apIp = ips.ip || "192.168.1.10";
    const gw = ips.gateway || "192.168.1.1";
    cfg += `! === Wireless AP Hardening ===\ndot11 ssid CyberExercise\n  authentication open\n  infrastructure-ssid\n  guest-mode\n!\ninterface Dot11Radio0\n ssid CyberExercise\n no short-slot-time\n no shutdown\n!\ninterface FastEthernet0\n ip address ${apIp.split("/")[0]} 255.255.255.0\n no shutdown\n!\nip default-gateway ${gw}\n! Disable weak auth\nno dot11 association mac-list\nno ip http server\n!\n`;
  }

  // ── LOAD BALANCER ──
  if (device.type === "loadbalancer") {
    const vip = ips.vip || "192.168.0.50";
    cfg += `! === Load Balancer ===\nip virtual-server vserver1\n virtual ${vip.split("/")[0]} tcp 443\n real ${b1}.${b2}.200.11 443\n real ${b1}.${b2}.200.12 443\n!\n`;
  }

  // Link table
  if (myLinks.length > 0) {
    cfg += `! ── CONNECTED LINKS ──────────────────────────\n`;
    myLinks.forEach(l => {
      const peer = l.from === device.name ? l.to : l.from;
      const myIface = l.from === device.name ? l.iface_from : l.iface_to;
      const peerIface = l.from === device.name ? l.iface_to : l.iface_from;
      cfg += `! ${myIface || "?"} <--> ${peerIface || "?"} on ${peer}${l.wan ? "  [WAN]" : ""}\n`;
    });
    cfg += `!\n`;
  }

  cfg += `end\n`;
  return cfg;
}

// ═══════════════════════════════════════════════════════════════
// JUNIPER JunOS
// ═══════════════════════════════════════════════════════════════
function generateJuniperConfig(device, design, ips, links) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = design?.domain_name || "cyberexercise.local";
  const ntp = design?.ntp_server || "pool.ntp.org";
  const username = design?.device_username || "admin";
  const password = design?.device_password || "Change" + "Me2024!";
  const myLinks = links.filter(l => l.from === device.name || l.to === device.name);

  let cfg = `## ==========================================
## ${device.label} — Juniper JunOS Configuration
## Vendor: Juniper Networks (vMX / EX / SRX)
## Cyber Exercise: ${design?.name || "Cyber Event"}
## Generated by Xtreme I.C.E. Network Designer
## ==========================================
## SECURITY HARDENING: CIS Junos Benchmark applied
## ⚠️  CRITICAL: DEFAULT EXERCISE PASSWORDS IN USE
## ⚠️  Username: ${username} | Password: ${password}
## ⚠️  Change IMMEDIATELY — never use in production

system {
    host-name ${hostname};
    domain-name ${domain};

    ## === PASSWORD & AUTH HARDENING ===
    login {
        password {
            ## Minimum 12 chars, require mixed case + digits + special
            minimum-length 12;
            change-type character-sets;
            minimum-changes 8;
        }
        retry-options {
            tries-before-disconnect 3;
            backoff-threshold 1;
            backoff-factor 5;
            minimum-time 60;
            lock-period 120;
        }
        class super-user-local {
            login-alarms;
        }
        user ${username} {
            full-name "Exercise Admin";
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "${password}"; ## Use juniper hash in production
            }
        }
    }

    ## === DISABLE UNNECESSARY SERVICES ===
    services {
        ssh {
            root-login deny;
            protocol-version v2;
            max-sessions-per-connection 1;
            connection-limit 5;
            rate-limit 5;
            hostkey-algorithm {
                no-ssh-dss;
            }
            macs [ hmac-sha2-256 hmac-sha2-512 ];
            ciphers [ aes256-ctr aes128-ctr ];
        }
        ## Disable Telnet, FTP, TFTP, HTTP
        telnet { connection-limit 0; }
        ftp { connection-limit 0; }
        netconf { ssh; }
    }
    no-redirects;

    ## === LOGGING ===
    syslog {
        host ${ntp} {
            any info;
            authorization info;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
        time-format year millisecond;
    }

    ## === NTP ===
    ntp {
        server ${ntp} prefer;
        authentication-key 1 type md5 value "ntpkey";
        trusted-key 1;
    }
}

## === INTERFACES ===\n`;

  if (device.type === "router") {
    if (ips.wan) {
      const [addr] = ips.wan.split("/");
      cfg += `interfaces {
    ge-0/0/0 {
        description "WAN Link";
        unit 0 {
            family inet {
                no-redirects;
                address ${addr}/30;
                filter { input WAN-PROTECT; }
            }
        }
    }\n`;
    }
    if (ips.lan) {
      const [addr, prefix] = ips.lan.split("/");
      cfg += `    ge-0/0/1 {
        description "LAN Link";
        unit 0 {
            family inet {
                address ${addr}/${prefix || 24};
            }
        }
    }\n`;
    }
    if (ips.loopback) {
      const lo = ips.loopback.split("/")[0];
      cfg += `    lo0 {
        unit 0 {
            family inet {
                address ${lo}/32;
            }
        }
    }\n`;
    }
    cfg += `}\n`;

    // Firewall filter for WAN
    cfg += `\nfirewall {
    family inet {
        filter WAN-PROTECT {
            term ALLOW-ESTABLISHED {
                from { tcp-established; }
                then accept;
            }
            term ALLOW-ICMP-REPLY {
                from { protocol icmp; icmp-type [ echo-reply unreachable time-exceeded ]; }
                then accept;
            }
            term DENY-ALL {
                then { reject; syslog; }
            }
        }
    }
}\n`;

    // OSPF / routing
    const protocol = design?.routing_protocol || "OSPF";
    if (protocol === "OSPF") {
      cfg += `\nprotocols {
    ospf {
        area 0.0.0.0 {
            interface ge-0/0/0.0 { interface-type p2p; }
            interface ge-0/0/1.0 { interface-type p2p; }
            interface lo0.0 { passive; }
        }
    }
    lldp { interface all; }
}\n`;
    } else if (protocol === "BGP") {
      cfg += `\nprotocols {
    bgp {
        group UPSTREAMS {
            type external;
            peer-as 65001;
        }
    }
}\n`;
    }
    cfg += `\nrouting-options {
    static {
        route 0.0.0.0/0 next-hop ge-0/0/0.0;
    }
    router-id ${ips.loopback?.split("/")[0] || "0.0.0.1"};
    autonomous-system 65000;
}\n`;
  }

  if (device.type === "switch") {
    const vlans = design?.vlan_names?.length ? design.vlan_names : ["Management", "Data", "Voice"];
    cfg += `vlans {\n`;
    vlans.forEach((v, i) => { cfg += `    ${v.replace(/\s+/g, "-")} { vlan-id ${i + 10}; }\n`; });
    cfg += `}\n\ninterfaces {\n`;
    cfg += `    ge-0/0/0 { description "Uplink"; unit 0 { family ethernet-switching { interface-mode trunk; vlan { members [ ${vlans.map(v => v.replace(/\s+/g, "-")).join(" ")} ]; } } } }\n`;
    for (let p = 1; p <= 4; p++) {
      cfg += `    ge-0/0/${p} { description "Access-${p}"; unit 0 { family ethernet-switching { interface-mode access; vlan { members ${vlans[1]?.replace(/\s+/g, "-") || "Data"}; } storm-control default; } } }\n`;
    }
    if (ips.mgmt) {
      const [addr] = ips.mgmt.split("/");
      cfg += `    irb { unit 10 { description "Management SVI"; family inet { address ${addr}/24; } } }\n`;
    }
    cfg += `}\n\nprotocols {\n    rstp;\n    lldp { interface all; }\n    dhcp-snooping { interface all; }\n    arp-inspection { interface all; }\n}\n`;
  }

  if (device.type === "firewall") {
    const outside = ips.outside?.split("/")[0] || "dhcp";
    const inside = ips.inside?.split("/")[0] || "192.168.1.1";
    cfg += `interfaces {
    ge-0/0/0 { description "outside"; unit 0 { family inet { address ${outside}/30; } } }
    ge-0/0/1 { description "inside"; unit 0 { family inet { address ${inside}/30; } } }
${design?.dmz_required && ips.dmz ? `    ge-0/0/2 { description "dmz"; unit 0 { family inet { address ${ips.dmz.split("/")[0]}/30; } } }\n` : ""}}

security {
    zones {
        security-zone untrust {
            interfaces { ge-0/0/0.0 { host-inbound-traffic { system-services { ssh; ping; } } } }
        }
        security-zone trust {
            interfaces { ge-0/0/1.0 { host-inbound-traffic { system-services { all; } } } }
        }
        ${design?.dmz_required ? `security-zone dmz {
            interfaces { ge-0/0/2.0 { host-inbound-traffic { system-services { http; https; } } } }
        }` : ""}
    }
    policies {
        from-zone trust to-zone untrust {
            policy TRUST-TO-UNTRUST {
                match { source-address any; destination-address any; application any; }
                then { permit; log { session-close; } }
            }
        }
        from-zone untrust to-zone trust {
            policy DENY-ALL {
                match { source-address any; destination-address any; application any; }
                then { deny; log { session-close; } }
            }
        }
    }
    nat {
        source {
            rule-set TRUST-TO-UNTRUST {
                from zone trust;
                to zone untrust;
                rule SNAT { match { source-address 0.0.0.0/0; } then { source-nat { interface; } } }
            }
        }
    }
    ## === THREAT PREVENTION ===
    idp { active-policy recommended; }
    utm { default-configuration { anti-virus { mime-pattern { list [ http ftp smtp pop3 imap ]; } } } }
    screen {
        ids-option UNTRUST-SCREEN {
            icmp { ping-death; }
            ip { source-route-option; tear-drop; }
            tcp { syn-flood { alarm-threshold 1024; attack-threshold 200; source-threshold 1024; } land; }
        }
    }
    zones { security-zone untrust { screen UNTRUST-SCREEN; } }
}\n`;
  }

  // Link table
  if (myLinks.length > 0) {
    cfg += `\n## ── CONNECTED LINKS ──────────────────────────\n`;
    myLinks.forEach(l => {
      const peer = l.from === device.name ? l.to : l.from;
      const myIface = l.from === device.name ? l.iface_from : l.iface_to;
      const peerIface = l.from === device.name ? l.iface_to : l.iface_from;
      cfg += `## ${myIface || "?"} <--> ${peerIface || "?"} on ${peer}${l.wan ? "  [WAN]" : ""}\n`;
    });
  }

  return cfg;
}

// ═══════════════════════════════════════════════════════════════
// PALO ALTO PAN-OS (XML set commands)
// ═══════════════════════════════════════════════════════════════
function generatePaloAltoConfig(device, design, ips, links, b1, b2) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = design?.domain_name || "cyberexercise.local";
  const ntp = design?.ntp_server || "pool.ntp.org";
  const username = design?.device_username || "admin";
  const password = design?.device_password || "Change" + "Me2024!";
  const outside = ips.outside?.split("/")[0] || "192.168.0.2";
  const inside = ips.inside?.split("/")[0] || "192.168.1.1";
  const myLinks = links.filter(l => l.from === device.name || l.to === device.name);

  let cfg = `# ==========================================
# ${device.label} — Palo Alto PAN-OS Configuration
# Vendor: Palo Alto Networks (PAN-OS)
# Cyber Exercise: ${design?.name || "Cyber Event"}
# Generated by Xtreme I.C.E. Network Designer
# Apply using: set commands in PAN-OS CLI
# ==========================================
# SECURITY HARDENING: Palo Alto Best Practices applied
# ⚠️  CRITICAL: DEFAULT EXERCISE PASSWORDS IN USE
# ⚠️  Username: ${username} | Password: ${password}
# ⚠️  Change IMMEDIATELY — never use in production

# === DEVICE SETTINGS ===
set deviceconfig system hostname ${hostname}
set deviceconfig system domain ${domain}
set deviceconfig system dns-setting servers primary 8.8.8.8
set deviceconfig system dns-setting servers secondary 8.8.4.4
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address ${ntp}

# === PASSWORD HARDENING ===
set mgt-config password-complexity enabled yes
set mgt-config password-complexity minimum-length 12
set mgt-config password-complexity minimum-uppercase-letters 1
set mgt-config password-complexity minimum-lowercase-letters 1
set mgt-config password-complexity minimum-numeric-letters 1
set mgt-config password-complexity minimum-special-characters 1
set mgt-config password-complexity block-username-inclusion yes
set mgt-config password-expiry-warning-period 14
set mgt-config password-change-period-login-count 3

# === ADMIN USERS ===
set mgt-config users ${username} phash ${password}
set mgt-config users ${username} permissions role-based deviceadmin yes

# === MANAGEMENT INTERFACE HARDENING ===
set deviceconfig system permitted-ip 10.0.0.0/8
set deviceconfig system service disable-http yes
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-icmp no
set deviceconfig system service disable-snmp yes
set deviceconfig system service disable-ssh no
set deviceconfig system ssh cipher aes256-ctr
set deviceconfig system ssh mac hmac-sha2-256
set deviceconfig system login-banner "AUTHORIZED ACCESS ONLY | Cyber Exercise"

# === INTERFACES ===
set network interface ethernet ethernet1/1 layer3 ip ${outside}/30
set network interface ethernet ethernet1/1 comment "outside (untrust)"
set network interface ethernet ethernet1/2 layer3 ip ${inside}/30
set network interface ethernet ethernet1/2 comment "inside (trust)"
${design?.dmz_required && ips.dmz ? `set network interface ethernet ethernet1/3 layer3 ip ${ips.dmz.split("/")[0]}/30\nset network interface ethernet ethernet1/3 comment "dmz"\n` : ""}
# === ZONES ===
set zone untrust network layer3 ethernet1/1
set zone trust network layer3 ethernet1/2
${design?.dmz_required ? `set zone dmz network layer3 ethernet1/3\n` : ""}
# === VIRTUAL ROUTER ===
set network virtual-router default routing-table ip static-route default nexthop ip-address ${outside}
set network virtual-router default interface [ ethernet1/1 ethernet1/2 ]

# === SECURITY POLICIES ===
set rulebase security rules ALLOW-TRUST-OUT from trust to untrust source any destination any application any service application-default action allow log-end yes
set rulebase security rules DENY-ALL from any to any source any destination any application any service any action deny log-end yes

# === NAT ===
set rulebase nat rules SNAT from trust to untrust source any destination any service any source-translation dynamic-ip-and-port interface-address interface ethernet1/1

# === THREAT PREVENTION ===
set profiles virus default action-setting block default quarantine
set profiles spyware strict botnet-domains action sinkhole
set profiles vulnerability strict rules brute-force action block-ip track-by attacker-and-victim duration 300
set profiles url-filtering strict action block categories [ malware phishing command-and-control ]
set rulebase security rules ALLOW-TRUST-OUT profile-setting profiles virus default spyware strict vulnerability strict url-filtering strict

# === LOGGING ===
set deviceconfig system syslog server SIEM transport UDP port 514 server ${b1}.${b2}.200.11
set deviceconfig system syslog server SIEM facility LOG_USER
`;

  // Link table
  if (myLinks.length > 0) {
    cfg += `\n# ── CONNECTED LINKS ──────────────────────────\n`;
    myLinks.forEach(l => {
      const peer = l.from === device.name ? l.to : l.from;
      const myIface = l.from === device.name ? l.iface_from : l.iface_to;
      const peerIface = l.from === device.name ? l.iface_to : l.iface_from;
      cfg += `# ${myIface || "?"} <--> ${peerIface || "?"} on ${peer}${l.wan ? "  [WAN]" : ""}\n`;
    });
  }

  return cfg;
}

// ═══════════════════════════════════════════════════════════════
// FORTINET FORTIOS
// ═══════════════════════════════════════════════════════════════
function generateFortinetConfig(device, design, ips, links, b1, b2) {
  const hostname = device.name.replace(/\s+/g, "-");
  const domain = design?.domain_name || "cyberexercise.local";
  const ntp = design?.ntp_server || "pool.ntp.org";
  const username = design?.device_username || "admin";
  const password = design?.device_password || "Change" + "Me2024!";
  const dns1 = (design?.dns_servers || ["8.8.8.8"])[0];
  const dns2 = (design?.dns_servers || ["8.8.8.8", "8.8.4.4"])[1] || "8.8.4.4";
  const inside = ips.inside?.split("/")[0] || "192.168.1.1";
  const myLinks = links.filter(l => l.from === device.name || l.to === device.name);

  let cfg = `# ==========================================
# ${device.label} — FortiGate FortiOS Configuration
# Vendor: Fortinet FortiOS
# Cyber Exercise: ${design?.name || "Cyber Event"}
# Generated by Xtreme I.C.E. Network Designer
# ==========================================
# SECURITY HARDENING: CIS FortiGate Benchmark applied
# ⚠️  CRITICAL: DEFAULT EXERCISE PASSWORDS IN USE
# ⚠️  Username: ${username} | Password: ${password}
# ⚠️  Change IMMEDIATELY — never use in production

# === SYSTEM GLOBAL HARDENING ===
config system global
    set hostname ${hostname}
    set admintimeout 10
    set admin-ssh-port 22
    set admin-sport 443
    set admin-telnet-port 23
    set admin-telnet disable
    set admin-http-port 80
    set admin-http disable
    set strong-crypto enable
    set fips-mode disable
    set ssh-hostkey-algo ecdsa256 rsa2048
    set timezone 04
    set login-timestamp enable
    set two-factor-bypass-on-reboot disable
end

# === DNS ===
config system dns
    set primary ${dns1}
    set secondary ${dns2}
    set domain "${domain}"
end

# === NTP ===
config system ntp
    set ntpsync enable
    set type custom
    set syncinterval 60
    config ntpserver
        edit 1
            set server "${ntp}"
            set ntpv3 disable
        next
    end
end

# === PASSWORD POLICY HARDENING ===
config system password-policy
    set status enable
    set minimum-length 12
    set min-lower-case-letter 1
    set min-upper-case-letter 1
    set min-non-alphanumeric 1
    set min-number 1
    set change-4-characters enable
    set expire-status enable
    set expire-day 90
    set reuse-password enable
end

# === ADMIN ACCOUNT ===
config system admin
    edit "${username}"
        set password "${password}"
        set accprofile "super_admin"
        set vdom "root"
        set two-factor disable
        set remote-auth disable
        set force-password-change disable
    next
end

# === DISABLE UNNECESSARY ADMIN ACCESS ===
config system interface
    edit "mgmt"
        set allowaccess https ssh ping
        set type physical
    next
end

`;

  if (device.type === "firewall") {
    cfg += `# === INTERFACES ===
config system interface
    edit "wan1"
        set mode dhcp
        set role wan
        set allowaccess ping
    next
    edit "internal"
        set ip ${inside} 255.255.255.0
        set role lan
        set allowaccess ping https ssh
    next
${design?.dmz_required && ips.dmz ? `    edit "dmz"
        set ip ${ips.dmz.split("/")[0]} 255.255.255.0
        set role dmz
        set allowaccess ping
    next
` : ""}end

# === FIREWALL ADDRESS OBJECTS ===
config firewall address
    edit "LAN_SUBNET"
        set subnet ${inside} 255.255.255.0
    next
    edit "ALL"
        set type ipmask
        set subnet 0.0.0.0 0.0.0.0
    next
end

# === SECURITY POLICY ===
config firewall policy
    edit 1
        set name "LAN-to-WAN"
        set srcintf "internal"
        set dstintf "wan1"
        set srcaddr "LAN_SUBNET"
        set dstaddr "ALL"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
        set logtraffic all
        set logtraffic-start enable
        set av-profile "default"
        set ips-sensor "default"
        set application-list "default"
        set ssl-ssh-profile "deep-inspection"
    next
    edit 2
        set name "DENY-ALL-LOG"
        set srcintf "any"
        set dstintf "any"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end

# === THREAT PREVENTION ===
config ips sensor
    edit "default"
        set comment "Default IPS Sensor"
        config entries
            edit 1
                set rule all
                set action block
            next
        end
    next
end

config antivirus profile
    edit "default"
        set comment "Default AV Profile"
        config http
            set options scan
            set av-scan enable
        end
    next
end

`;

    if (design?.wan_technology === "IPSec VPN") {
      cfg += `# === IPSec VPN (IKEv2) ===
config vpn ipsec phase1-interface
    edit "VPN-TUNNEL"
        set interface "wan1"
        set ike-version 2
        set peertype any
        set proposal aes256-sha256
        set dhgrp 14
        set psksecret "ChangeThisPreSharedKey!"
        set dpd on-idle
        set dpd-retryinterval 10
    next
end

config vpn ipsec phase2-interface
    edit "VPN-P2"
        set phase1name "VPN-TUNNEL"
        set proposal aes256-sha256
        set pfs enable
        set dhgrp 14
        set replay enable
    next
end

`;
    }
  }

  // === LOGGING ===
  cfg += `# === LOGGING ===
config log setting
    set resolve-ip enable
    set resolve-port enable
    set fwpolicy-implicit-log enable
    set local-in-policy-log enable
    set log-user-in-upper enable
end

config log syslogd setting
    set status enable
    set server "${b1}.${b2}.200.11"
    set reliable enable
    set port 514
    set facility local7
    set format default
end

`;

  // Link table
  if (myLinks.length > 0) {
    cfg += `# ── CONNECTED LINKS ──────────────────────────\n`;
    myLinks.forEach(l => {
      const peer = l.from === device.name ? l.to : l.from;
      const myIface = l.from === device.name ? l.iface_from : l.iface_to;
      const peerIface = l.from === device.name ? l.iface_to : l.iface_from;
      cfg += `# ${myIface || "?"} <--> ${peerIface || "?"} on ${peer}${l.wan ? "  [WAN]" : ""}\n`;
    });
  }

  cfg += `\n# End of FortiOS configuration\n`;
  return cfg;
}

// ═══════════════════════════════════════════════════════════════
// MAIN DISPATCHER
// ═══════════════════════════════════════════════════════════════
export function generateDeviceConfig(device, design, ipAllocs, links) {
  const ips = ipAllocs[device.name] || {};
  const [b1, b2] = parseBase(design?.ip_scheme);
  const vendor = detectVendor(device, design);

  if (vendor === "paloalto") return generatePaloAltoConfig(device, design, ips, links, b1, b2);
  if (vendor === "juniper") return generateJuniperConfig(device, design, ips, links);
  if (vendor === "fortinet") return generateFortinetConfig(device, design, ips, links, b1, b2);
  return generateCiscoConfig(device, design, ips, links, b1, b2);
}

// ── File extension by vendor ──────────────────────────────────────────────────
export function configFileExtension(device, design) {
  const vendor = detectVendor(device, design);
  if (vendor === "paloalto") return ".set";   // PAN-OS set commands
  if (vendor === "juniper") return ".conf";   // JunOS
  if (device.type === "server") return ".sh"; // Shell script
  return ".cfg";                              // Cisco IOS
}