import { createClientFromRequest } from "npm:@base44/sdk@0.8.40";
Deno.serve(async(req)=>{let active:any=null;try{
 const base44=createClientFromRequest(req);const user=await base44.auth.me();if(!user)return Response.json({error:"Unauthorized"},{status:401});if(user.role!=="admin")return Response.json({error:"Administrator access is required"},{status:403});
 const jobs=(await base44.asServiceRole.entities.CCIEvidenceAnalysisJob.list()).filter((j:any)=>j.status==="queued"||j.status==="processing").sort((a:any,b:any)=>new Date(a.created_date||0).getTime()-new Date(b.created_date||0).getTime());active=jobs[0];if(!active)return Response.json({success:true,status:"idle"});
 const assessment=(await base44.asServiceRole.entities.CCIAssessment.filter({id:active.assessment_id}))[0];if(!assessment)throw new Error("Authorized assessment record was not found.");
 const files=(assessment.report_files||[]).filter((f:any)=>f?.file_url),i=Number(active.file_index||0),results=active.extracted_results||[];
 if(i<files.length){const file=files[i];await base44.asServiceRole.entities.CCIEvidenceAnalysisJob.update(active.id,{status:"processing",current_file:file.name||`Document ${i+1}`,started_at:active.started_at||new Date().toISOString()});await base44.asServiceRole.entities.CCIAssessment.update(assessment.id,{evidence_analysis_status:"processing",evidence_analysis_progress:Math.round(i/files.length*100),evidence_analysis_message:`Analyzing ${i+1} of ${files.length}: ${file.name||"report"}`});
  const out=await base44.integrations.Core.ExtractDataFromUploadedFile({file_url:file.file_url,json_schema:{type:"object",properties:{report_date:{type:"string"},vulnerability_findings:{type:"array",items:{type:"object",properties:{id:{type:"string"},title:{type:"string"},severity:{type:"string"},asset:{type:"string"},evidence:{type:"string"}},required:["title","severity"]}},pentest_findings:{type:"array",items:{type:"object",properties:{id:{type:"string"},title:{type:"string"},severity:{type:"string"},asset:{type:"string"},evidence:{type:"string"},external_management_exposed:{type:"boolean"}},required:["title","severity"]}},attack_evidence:{type:"array",items:{type:"object",properties:{name:{type:"string"},attack_correlation_type:{type:"string"},attack_vector:{type:"string"},mitre_technique_id:{type:"string"},mitre_technique_name:{type:"string"},mitre_tactic:{type:"string"},status:{type:"string",enum:["attempted","successful"]},affected_asset:{type:"string"},outcome:{type:"string"},business_relevance:{type:"string"},evidence:{type:"string"}},required:["name","status","evidence"]}},summary:{type:"string"},warnings:{type:"array",items:{type:"string"}}}}});
  if(out.status!=="success"||!out.output)throw new Error(`Evidence extraction failed for ${file.name||"report"}`);
  await base44.asServiceRole.entities.CCIEvidenceAnalysisJob.update(active.id,{file_index:i+1,extracted_results:[...results,{category:file.category||"report",name:file.name,...out.output}],current_file:""});return Response.json({success:true,status:"processing",processed:i+1,total:files.length});
 }
 const finalized=await base44.functions.invoke("analyzeCCIAssessment",{business_name:assessment.business_name,business_address:assessment.business_address||"",poc_name:assessment.poc_name||"",poc_email:assessment.poc_email||"",poc_phone:assessment.poc_phone||"",organization_id:assessment.organization_id,report_files:assessment.report_files||[],evidence_files:assessment.evidence_files||[],revision_of_id:assessment.id,background_finalize:true,pre_extracted:results});
 await base44.asServiceRole.entities.CCIEvidenceAnalysisJob.update(active.id,{status:"completed",file_index:files.length,current_file:"",completed_at:new Date().toISOString(),error:""});return Response.json({success:true,status:"completed",assessment_id:finalized?.data?.assessment?.id||assessment.id});
}catch(e){try{if(active){const base44=createClientFromRequest(req);await base44.asServiceRole.entities.CCIEvidenceAnalysisJob.update(active.id,{status:"failed",error:e instanceof Error?e.message:String(e),completed_at:new Date().toISOString()});await base44.asServiceRole.entities.CCIAssessment.update(active.assessment_id,{evidence_analysis_status:"failed",evidence_analysis_message:e instanceof Error?e.message:String(e)});}}catch{}return Response.json({error:e instanceof Error?e.message:String(e)},{status:500});}});