// Scenario-specific incident-response playbooks for Beginner SOC drills.
// These rules drive ordered phase gates, expected actions, severity, reporting, and outcomes.

const base = {
  detect: { tabs: ["dashboard", "siem"] },
  triage: { any: ["collect_forensics"] },
  contain: { any: ["isolate_host", "block_ip", "disable_user"] },
  recover: { any: ["patch_system", "remove_persistence", "restore_backup"] },
  document: { report: true },
};

const p = (name, severity, objectives, phases, reportFocus, successMessage, failureMessage, prohibited = []) => ({
  name, severity, objectives, phases: { ...base, ...phases }, reportFocus,
  successMessage, failureMessage, prohibited,
});

export const BEGINNER_PLAYBOOKS = {
  brute_force_vpn: p("VPN Credential Attack", "P1",
    ["Confirm the successful VPN login", "Identify the compromised account", "Terminate attacker access before internal spread"],
    { triage:{all:["collect_forensics","disable_user"]}, contain:{all:["block_ip","reset_password"]}, recover:{any:["update_fw_rule","patch_system"]} },
    ["VPN source and geolocation", "Affected account and session", "Internal activity after login"],
    "Compromised VPN access revoked before material internal impact.",
    "The attacker retained VPN access and progressed to internal discovery or exfiltration.",
    ["restore_backup"]),
  suspicious_login: p("Identity Validation", "P2",
    ["Validate device, location, and user activity", "Determine benign travel versus compromise", "Revoke confirmed malicious access"],
    { triage:{any:["collect_forensics","preserve_evidence"]}, contain:{all:["disable_user","reset_password"]}, recover:{any:["remove_persistence","update_fw_rule"]} },
    ["Authentication timeline", "Device and location evidence", "Mailbox and cloud-session activity"],
    "The login was correctly classified and malicious sessions were revoked.",
    "The account remained exposed and mailbox or SharePoint data was accessed.",
    ["restore_backup","patch_system"]),
  malware_usb: p("Removable-Media Malware", "P2",
    ["Confirm USB execution", "Isolate the endpoint", "Preserve removable-media evidence"],
    { triage:{all:["collect_forensics","preserve_evidence"]}, contain:{all:["isolate_host","quarantine_file"]}, recover:{all:["kill_process","remove_persistence"]} },
    ["USB device history", "Payload hash and path", "Endpoint and network spread"],
    "USB malware eradicated and the source media preserved for investigation.",
    "The payload persisted or spread through shared resources.",
    ["restore_backup"]),
  spam_campaign: p("Malicious Email Campaign", "P2",
    ["Identify sender and attachment pattern", "Determine recipient exposure", "Block delivery and contain infected endpoints"],
    { triage:{any:["collect_forensics","open_ticket"]}, contain:{all:["isolate_host","update_fw_rule"]}, recover:{any:["quarantine_file","kill_process"]} },
    ["Sender infrastructure", "Recipients and attachment opens", "Message and endpoint containment"],
    "The campaign was blocked and exposed endpoints were contained.",
    "Additional recipients executed the attachment and the campaign propagated.",
    ["restore_backup"]),
  password_spray: p("Password Spray", "P1",
    ["Correlate attempts across accounts", "Identify successful authentications", "Block the source without mass lockout"],
    { triage:{all:["preserve_evidence","disable_user"]}, contain:{all:["block_ip","reset_password"]}, recover:{all:["update_fw_rule","open_ticket"]} },
    ["Source IP and attempt pattern", "Successful accounts", "Privileged access review"],
    "The spray source was blocked and affected credentials secured.",
    "A privileged account was compromised and used to access the domain.",
    ["restore_backup"]),
  port_scan: p("External Reconnaissance", "P3",
    ["Identify the scanning source", "Determine exposed services", "Block or rate-limit without disrupting approved access"],
    { triage:{any:["collect_forensics","open_ticket"]}, contain:{any:["block_ip","update_fw_rule"]}, recover:{all:["patch_system"]} },
    ["Scanned ports", "Exposed service ownership", "Firewall and remediation changes"],
    "Reconnaissance was blocked and the exposed service remediated.",
    "The attacker identified and exploited an exposed service.",
    ["disable_user","reset_password","restore_backup"]),
  rogue_wifi: p("Rogue Wireless Access Point", "P1",
    ["Validate SSID and BSSID", "Identify connected corporate devices", "Neutralize the AP and secure exposed credentials"],
    { triage:{all:["collect_forensics","preserve_evidence"]}, contain:{all:["update_fw_rule","disable_user"]}, recover:{all:["reset_password"]} },
    ["SSID/BSSID and physical location", "Connected devices", "Potential credential interception"],
    "The rogue AP was neutralized and exposed identities secured.",
    "Credentials were intercepted and used to pivot into the internal network.",
    ["restore_backup","patch_system"]),
  account_lockout: p("Authentication Denial of Service", "P2",
    ["Identify the lockout source", "Protect reset workflows", "Restore user access safely"],
    { triage:{any:["collect_forensics","open_ticket"]}, contain:{all:["block_ip","update_fw_rule"]}, recover:{all:["reset_password"]} },
    ["Locked-account count", "Attack source", "Business disruption and restoration"],
    "The lockout source was blocked and legitimate access safely restored.",
    "The attacker abused reset workflows and caused widespread service disruption.",
    ["restore_backup"]),
  malicious_macro: p("Office Macro Malware", "P1",
    ["Trace WINWORD-to-PowerShell execution", "Isolate the endpoint", "Remove payload and persistence"],
    { triage:{all:["collect_forensics","kill_process"]}, contain:{all:["isolate_host","block_ip"]}, recover:{all:["quarantine_file","remove_persistence"]} },
    ["Document source", "Process tree and command line", "C2 and lateral-movement scope"],
    "Macro malware and C2 activity were eradicated before lateral movement.",
    "Credentials were dumped and the attacker moved laterally.",
    ["restore_backup"]),
  dlp_alert: p("Regulated Data Exposure", "P1",
    ["Validate PCI data classification", "Determine whether transmission completed", "Preserve evidence and engage compliance"],
    { triage:{all:["collect_forensics","preserve_evidence"]}, contain:{all:["disable_user"]}, recover:{all:["notify_customer","start_coc"]} },
    ["Data classification and record count", "Recipient and transfer status", "Legal and notification determination"],
    "The regulated-data exposure was contained with a defensible evidence trail.",
    "Customer data was exfiltrated without required compliance handling.",
    ["restore_backup","patch_system"]),
  av_detection: p("Multi-Endpoint Malware", "P1",
    ["Validate quarantine status", "Determine patient zero", "Contain every infected endpoint"],
    { triage:{all:["collect_forensics","quarantine_file"]}, contain:{all:["isolate_host"]}, recover:{all:["kill_process","remove_persistence"]} },
    ["Patient zero", "Infected endpoint inventory", "Malware family and persistence"],
    "All infected endpoints were contained and persistence removed.",
    "The malware spread to servers and established persistence.",
    ["restore_backup"]),
  web_phishing_report: p("Reported Phishing", "P2",
    ["Analyze the URL and sender", "Identify recipients and clicks", "Secure exposed accounts"],
    { triage:{any:["collect_forensics","preserve_evidence"]}, contain:{all:["update_fw_rule","disable_user"]}, recover:{all:["reset_password"]} },
    ["Header and URL analysis", "Recipient exposure", "Credential and mailbox activity"],
    "The phishing infrastructure was blocked and exposed accounts secured.",
    "More users submitted credentials and internal phishing began.",
    ["restore_backup"]),
  unusual_process: p("Suspicious Endpoint Process", "P1",
    ["Validate the process path and ancestry", "Identify C2 behavior", "Remove persistence"],
    { triage:{all:["collect_forensics","preserve_evidence","quarantine_file"]}, contain:{all:["isolate_host","block_ip"]}, recover:{all:["kill_process","remove_persistence"]} },
    ["Process tree and hash", "C2 destination", "Persistence artifacts"],
    "The malicious process, C2 channel, and persistence were removed.",
    "The process retained C2 access and dumped credentials.",
    ["restore_backup"]),
  dns_anomaly: p("DNS-Based Command and Control", "P1",
    ["Differentiate DGA from normal DNS", "Identify the originating host", "Block C2 and tunneling"],
    { triage:{all:["collect_forensics","preserve_evidence"]}, contain:{all:["isolate_host","update_fw_rule"]}, recover:{all:["remove_persistence"]} },
    ["Queried domains and entropy pattern", "Originating endpoint", "DNS tunneling volume"],
    "DNS C2 and exfiltration paths were blocked and the host contained.",
    "Credentials or data were exfiltrated through the DNS tunnel.",
    ["restore_backup"]),
  privileged_misuse: p("Privileged Insider Misuse", "P1",
    ["Preserve evidence before containment", "Confirm authorization with management", "Coordinate access restriction"],
    { triage:{all:["preserve_evidence","start_coc"]}, contain:{all:["disable_user","collect_forensics"]}, recover:{any:["reset_password","notify_customer"]} },
    ["Privileged-account timeline", "Files accessed and authorization", "HR/legal coordination and custody"],
    "Privileged misuse was stopped with evidence and custody preserved.",
    "Data was exfiltrated or the investigation became legally indefensible.",
    ["restore_backup","patch_system"]),
  rdp_external: p("Internet-Exposed RDP", "P1",
    ["Confirm exposure and login activity", "Block external RDP", "Patch and validate the server"],
    { triage:{all:["collect_forensics","disable_user"]}, contain:{all:["block_ip","update_fw_rule"]}, recover:{all:["patch_system","reset_password"]} },
    ["Exposed port and source", "Successful RDP sessions", "Firewall and patch verification"],
    "External RDP was closed, credentials secured, and the server remediated.",
    "The attacker gained RDP access and deployed malware.",
    ["restore_backup"]),
  crypto_miner: p("Cryptomining Malware", "P2",
    ["Identify miner process and pool", "Determine the entry vector", "Remove service persistence"],
    { triage:{all:["collect_forensics","kill_process"]}, contain:{all:["isolate_host","update_fw_rule"]}, recover:{all:["remove_persistence","patch_system"]} },
    ["Miner process and wallet/pool", "Resource impact", "Entry vector and persistence"],
    "The miner and persistence were removed and compute capacity restored.",
    "The miner spread or continued consuming production resources.",
    ["restore_backup"]),
  fake_helpdesk: p("Help-Desk Social Engineering", "P1",
    ["Interview the user and identify disclosed information", "Revoke credentials and remote sessions", "Remove remote-access tooling"],
    { triage:{all:["collect_forensics","disable_user"]}, contain:{all:["reset_password","isolate_host"]}, recover:{all:["kill_process","quarantine_file"]} },
    ["Call details and claims", "Credentials disclosed", "Remote sessions and installed tools"],
    "Stolen credentials and remote access were revoked before further compromise.",
    "The attacker used the remote session to steal credentials and target the domain.",
    ["restore_backup"]),
  data_on_pastebin: p("Leaked Corporate Credentials", "P1",
    ["Validate the leaked dataset", "Match active accounts", "Reset exposed credentials and monitor stuffing"],
    { triage:{all:["preserve_evidence","start_coc"]}, contain:{all:["disable_user","reset_password"]}, recover:{all:["update_fw_rule"]} },
    ["Leak source and timestamp", "Matched active accounts", "Credential-stuffing activity"],
    "Exposed credentials were invalidated before privileged compromise.",
    "Leaked credentials were used to compromise active or privileged accounts.",
    ["restore_backup","patch_system"]),
  shadow_it: p("Unsanctioned Cloud Storage", "P2",
    ["Identify users and uploaded data", "Classify the information", "Block the service and preserve governance evidence"],
    { triage:{all:["collect_forensics","preserve_evidence"]}, contain:{all:["update_fw_rule"]}, recover:{any:["disable_user","notify_customer"]} },
    ["Unsanctioned service", "Users and files uploaded", "Classification and governance action"],
    "Unsanctioned transfer was stopped and sensitive-data exposure addressed.",
    "Confidential data remained externally accessible or the cloud account was compromised.",
    ["restore_backup","patch_system"]),
  ransomware_note_found: p("Pre-Encryption Ransomware", "P1",
    ["Identify patient zero", "Stop SMB propagation", "Protect backup infrastructure"],
    { triage:{all:["collect_forensics","kill_process"]}, contain:{all:["isolate_host","block_ip"]}, recover:{all:["remove_persistence","restore_backup"]} },
    ["Patient zero and timeline", "Encryption and share impact", "Backup validation and recovery point"],
    "Ransomware was contained and clean recovery completed before widespread encryption.",
    "Encryption spread to file servers or backup snapshots were destroyed.",
    ["disable_user"]),
};

export function getScenarioPlaybook(scenarioId) {
  return BEGINNER_PLAYBOOKS[scenarioId] || {
    name: "Incident Response", severity: "P1",
    objectives: ["Detect", "Contain", "Eradicate", "Recover", "Document"],
    phases: base, reportFocus: ["Timeline", "Affected assets", "IOCs", "Lessons learned"],
    successMessage: "Incident successfully contained with required response objectives complete.",
    failureMessage: "The incident exceeded containment limits before required objectives were completed.",
    prohibited: [],
  };
}

export function actionRuleComplete(rule, actionIds, context = {}) {
  if (!rule) return true;
  if (rule.tabs && !rule.tabs.every(tab => context.tabsVisited?.has(tab))) return false;
  if (rule.report && !context.reportGenerated) return false;
  if (rule.all && !rule.all.every(id => actionIds.has(id))) return false;
  if (rule.any && !rule.any.some(id => actionIds.has(id))) return false;
  return true;
}

export function getRequiredActionIds(scenarioId) {
  const pb = getScenarioPlaybook(scenarioId);
  const ids = new Set();
  Object.values(pb.phases).forEach(rule => {
    (rule.all || []).forEach(id => ids.add(id));
    (rule.any || []).forEach(id => ids.add(id));
  });
  return [...ids];
}
